### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [xd009642/tarpaulin#1]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Looks like this is blocked by https://github.com/docopt/docopt.rs/issues/128.

**Comment by xd009642** [comment]
Hi dtolnay, I'm aware rustc-serialize has been deprecated. Unfortunately it is currently blocked by docopt. I was hoping in the next docopt release I'd be able to remove rustc-serialize. 

Does serde offer the RustcDecodable trait and if so is it compatible with docopt?

**Comment by dtolnay** [comment]
Serde offers an equivalent of the RustcDecodable trait but unfortunately not in a way that would be compatible with the current version of docopt. The best plan may be to wait for docopt to release their next version and I or someone else will follow up in this issue when it's ready.

**Comment by xd009642** [comment]
Sounds good, I'll keep an eye out myself and consider whether I want to migrate to clap

**Comment by xd009642** [comment]
Issue closed. Replaced docopt with clap and removed the rustc_serialize dependency
