### ISSUE TITLE
Tarpaulin finds no coverage on rust 1.19

### ISSUE THREAD

**Issue by yodaldevoid** [xd009642/tarpaulin#10]
When run using rust 1.19 tarpaulin finishes without printing any errors and all tests that should pass, pass, but no coverage of any files is found.

I should note that this looks to be something with testing programs compiled with rust 1.19 rather than tarpaulin compiled with 1.19.

**Comment by chrisduerr** [comment]
I also get `No coverage results collected.` using nightly or 1.19.
I've downloaded the old 1.18.0 to test and everything works as expected.

**Comment by xd009642** [comment]
yeah I'm looking into this currently, but something changed in 1.19 has changed the dwarf output meaning tarpaulin isn't finding the addresses. I have a feeling this might be the upgrade to LLVM 4.0.1, so there may be more issues hiding as well.

I've done a bit of preliminary debugging and testing and I think I've found the culprit so hopefully there will be a fix out later today

**Comment by xd009642** [comment]
Right this fix appears to have done it. I'm publishing 0.3.7 and I'll try it on travis as a general benchmark, I've closed the issue for now but if it pops up again I'll reopen it. However, I'm feeling optimistic :+1:
