### ISSUE TITLE
[Question] Is it possible to generate the cobertura file from workspace

### ISSUE THREAD

**Issue by eduardonunesp** [xd009642/tarpaulin#1002]
I would like to know if is possible to generate the cobertura.xml file running from the workspace, or in order to generate the xml file it needs to run directly from the project directory.

For instance I'm trying to run from the workspace root dir the following command, and it doesn't generates the cobertura.xml file
```
cargo tarpaulin --all-features --workspace --tests --doc --out Xml
```
Is that correct, the cobertura.xml file only is generated if you run on the project dir? thanks in advance

**Comment by xd009642** [comment]
It should work fine for a workspace, do you have a public project I can try to see what's going on?

**Comment by eduardonunesp** [comment]
Isn't public right now, I'll try to reproduce the error on a public project

**Comment by eduardonunesp** [comment]
Well, figure out that there was some errors happening on the test on some packages, removing `--no-fail-fast`  helped me to find the spot, after fix the issues the file started to generated correctly. Thanks for the support.
