### ISSUE TITLE
A way to list uncovered lines without verbose flag

### ISSUE THREAD

**Issue by Kile-Asmussen** [xd009642/tarpaulin#1010]
After a close reading of the documentation and `--help` printout, it would appear there is not a way to get the list of uncovered lines without specifying `--verbose`.

If this feature is indeed available already, the documentation in the readme should be updated to reflect it.

**Rationale:**

Specifying `--verbose` subjects the user to the very long printout of all `rustc` invocations, which is very noisy.

Viewing the uncovered lines is useful in the context of deliberately writing tests to achieve high code coverage.

**Comment by xd009642** [comment]
I figured the mention of different reporting types was evidence enough of how to get the specific uncovered lines. For example codecov.io and coveralls.io show the project coverage in that form and support of them is explicitly mentioned. And going from console output to source files always felt a bit fiddly versus generating a HTML report and opening it locally.

Maybe I could make the explicit stdout report type print more info as it's always active anyway :thinking:

**Comment by Kile-Asmussen** [comment]
Sounds good!

**Comment by xd009642** [comment]
I've implemented this and will do a release tonight so after today `--out stdout` will give you the same uncovered lines printout that `--verbose` gives you but without all the other verbose logs
