### ISSUE TITLE
Code coverage for macros

### ISSUE THREAD

**Issue by jeremydavis519** [xd009642/tarpaulin#102]
Do you know if it would be possible to trace code coverage in procedural macros when they're being expanded? I'm currently making a procedural macro crate and would like to use tarpaulin to keep track of code coverage, but it just shows that my test cases are running and nothing else--probably because everything else (i.e. the macro expansions) runs at compile time. I haven't looked into it yet, but I expect that if tarpaulin can trace rustc's execution, it'll be able to report on the code coverage in procedural macros.

It might also work for declarative macros, but I doubt it. Probably worth a try, though.

**Comment by xd009642** [comment]
Tarpaulin only traces the test binaries at run time so I'm afraid I can't be much use. As for tracing rustc tarpaulin could only trace what lines in the rustc source are being hit which means you'd need to rely on knowledge of compiler internals to be able to reason in any form.

This is an interesting problem in terms of testing. If the macro generates code you could use it to make said code, then test that code and get coverage of that. If that's useful at all?

**Comment by jeremydavis519** [comment]
I figured it would be more complicated than it seemed at first. I'll tinker with things and see if I can get something working.

Yes, tarpaulin is telling me how many lines in my tests cases, after macro expansion, are being used, but what I really want to know is whether the tests are covering every possible way the macro could be expanded, since that's the bulk of my crate's logic.

It is possible to run the macro's code at run time if I put the tests in the same file as the macro (or a module included in that file). I'll see if I can emulate the expansion by turning my other test cases into `TokenStream`s and passing those to the macro. I'll let you know if it works and if it's general enough that you might want to include it in tarpaulin, at least as documentation to make people aware of the workaround.

**Comment by jeremydavis519** [comment]
Well, that idea didn't work. Apparently, the parsing can only work at compile time because it needs to know where the macro expansion is in the code (even though that should only be necessary for error messages >.>). It panics whenever I try to parse anything at run time. I'll close the issue; feel free to reopen it if you have any ideas, but it looks like it's not possible without going deep into the compiler's internals. And I'll be back if I come up with a solution.

**Comment by jeremydavis519** [comment]
It looks like I spoke too soon. That error I was getting was actually related to using the `proc-macro2` crate with its `nightly` feature activated, which (with a little bit of tweaking in my own code) it turns out I didn't need. Now that I've done that, my project is successfully testing the parsing at run time! 🎉

I'll probably submit a PR later today, now that I've figured out how to do it. The solution isn't perfect--it needs to know how the macro will be referenced in the file, since we can't tell if `foo!` refers to `bar::foo` or `baz::foo`, or if the programmer will choose to use `bar::foo!` instead--but the person writing the tests should know that ahead of time.
