### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by juliays** [xd009642/tarpaulin#1047]
**Describe the bug**

Mac with M1Chip, Installed Focal Ubuntu Desktop and tried running the following - 

 "cargo install cargo-tarpaulin" in terminal

received the following errors - 

error[E0412]: cannot find type `Persona` in this scope
  --> /home/songy/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.20.1/src/process_handling/linux.rs:25:26
   |
25 | const ADDR_NO_RANDOMIZE: Persona = 0x004_0000;
   |                          ^^^^^^^ not found in this scope

error[E0412]: cannot find type `Persona` in this scope
  --> /home/songy/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.20.1/src/process_handling/linux.rs:26:20
   |
26 | const GET_PERSONA: Persona = 0xFFFF_FFFF;
   |                    ^^^^^^^ not found in this scope

error[E0412]: cannot find type `Persona` in this scope
  --> /home/songy/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.20.1/src/process_handling/linux.rs:75:25
   |
75 | fn personality(persona: Persona) -> nix::Result<c_int> {
   |                         ^^^^^^^ not found in this scope

error[E0425]: cannot find value `INT` in this scope
  --> /home/songy/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-tarpaulin-0.20.1/src/process_handling/breakpoint.rs:60:21
   |
60 |         intdata |= (INT << self.shift) as i64;
   |                     ^^^ not found in this scope

Some errors have detailed explanations: E0412, E0425.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `cargo-tarpaulin` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-tarpaulin v0.20.1`, intermediate artifacts can be found at `/tmp/cargo-installkkBgJi`

**Comment by xd009642** [comment]
So arm64 support will come via #549, ptrace is beyond broken in MacOS so previous experiments to get it work went nowhere. So if you follow that issue I'll close this one as a duplicate
