### ISSUE TITLE
Trace down into launched binaries.

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#107]
This is a big change and probably quite challenging but here it goes.

Given a test or program that uses a function like `Command::spawn()` or something like `assert-cli` which launches a new binary follow that binary down and get coverage of it's code. The steps to do this (as far as I can tell are)

1. When an exec event comes in identify if the binary is in the target folder (use procfs) if it isn't detach ptrace otherwise:
2. Run them through `test_loader.rs` to get a tracemap for them. Merge with existing tracemap (maybe after the next step)
3. Catch the binary when it's launched and instrument it 
5. Carry on running as normal (but may need a way to distinguish which process a breakpoint belongs to)

This is just an initial impression, it may be missing details or not quite work. It's just a record of my thoughts and feelings regarding an initial approach. It does complicate the run time logic of tarpaulin so may involve a substantial redesign of numerous modules as well!

**Comment by xd009642** [comment]
I've got a prototype of following process exec's on https://github.com/xd009642/tarpaulin/pull/615 if you want to try it out. So far I've just tried it on a very simple toy project so more people testing it is appreciated 😄

**Comment by Ch00k** [comment]
@xd009642 Thanks so much for looking into this. I got the coverage calculated on my integration tests, that call the executable with `process:Command`. Here is the codecov report: https://codecov.io/gh/Ch00k/orthanc-cli/tree/d30f584c8494231a3330f30e5afbafef50432046/src

Let me me know if you need me to perform any more specific tests before you can merge the PR.

**Comment by xd009642** [comment]
Right I've done some more testing and merged, forks don't work but exec does which I feel is the most important part anyway. I'll close this and tackle any issues as they arise when people upgrade :+1:

**Comment by xd009642** [comment]
Following forks covered by this issue https://github.com/xd009642/tarpaulin/issues/616
