### ISSUE TITLE
README suggests using GitLab setting that was removed in GitLab 15.0

### ISSUE THREAD

**Issue by finnbear** [xd009642/tarpaulin#1070]
**Describe the bug**
The README currently suggests using a GitLab setting to configure a coverage parsing regex. That setting was [removed in GitLab 15.0](https://gitlab.com/gitlab-org/gitlab/-/issues/17633).

**To Reproduce**
https://github.com/xd009642/tarpaulin/blob/a802a1c56bf07a7dc3254791db8305f56bc6ff08/README.md?plain=1#L462-L471

**Expected behavior**
README.md doesn't suggest using features that were [removed](https://gitlab.com/gitlab-org/gitlab/-/issues/17633).

The second method listed in the README (`.gitlab-ci.yml`) is necessary and sufficient to get this to work.

Alternatively, there could be a note that the feature was removed in GitLab 15.0.

**Comment by xd009642** [comment]
Ah I don't use gitlab so the docs largely rely on gitlab users PRing it or raising an issue. I'll have a look at removing it and replacing with the current state of things after work (unless a PR comes before then of course :smile: )
