### ISSUE TITLE
Cargo tarpaulin --run-types Doctests fails "toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed"

### ISSUE THREAD

**Issue by tomasro27** [xd009642/tarpaulin#1074]
**Describe the bug**
I'm trying to run "cargo tarpaulin --run-types Doctests" with a custom toolchain, for which I'm using the `RUSTC_BOOTSTRAP=1` environment variable to leverage nightly features. So even though I have all the nightly features, running Doctests fails. Is there a way to force or specify a toolchain?
running cargo tarpaulin --run-types Tests works fine.

**To Reproduce**
cargo tarpaulin --run-types Doctests

**Expected behavior**
Be able to run Doctests with stable toolchain and `RUSTC_BOOTSTRAP=1` flag.

**Comment by xd009642** [comment]
I've done a PR for it here if you want to test it https://github.com/xd009642/tarpaulin/pull/1075 for some reason it seems to work on my host system without it but I think that's just because nightly is my default and +stable seems to not override it as I'd expect :thinking:

**Comment by tomasro27** [comment]
Thank you. Let me give it a try

**Comment by xd009642** [comment]
CI failing seems to suggest it doesn't work :thinking:  i'll have to have a look tomorrow most likely

**Comment by xd009642** [comment]
OH I might have spotted it, if you try latest commit hopefully there's something good there

**Comment by tomasro27** [comment]
Last commit works well! Thanks a lot

**Comment by xd009642** [comment]
Cool I'll merge that then, you'll have to use develop branch for a bit (or develop docker images), but I'm aiming on cutting a new release this week or next week so hopefully not for long :+1:
