### ISSUE TITLE
Can't run on rootless podman

### ISSUE THREAD

**Issue by rlpowell** [xd009642/tarpaulin#1087]
I do all my Rust development inside a rootless podman container; think Docker but (1) no server and (2) everything runs as my own user.

Attempting to run tarpaulin gives:
```
   Compiling zero2prod v0.1.0 (/src/zero2prod)
    Finished test [unoptimized + debuginfo] target(s) in 40.04s
Sep 05 04:21:58.330  INFO cargo_tarpaulin::process_handling::linux: Launching test
Sep 05 04:21:58.330  INFO cargo_tarpaulin::process_handling: running /src/zero2prod/target/debug/deps/zero2prod-bc2e565627450988
Sep 05 04:21:58.330 ERROR cargo_tarpaulin: Failed to run tests: ASLR disable failed: ENOSYS: Function not implemented
Error: "Failed to run tests: ASLR disable failed: ENOSYS: Function not implemented"
Sep 05 04:22:05.834 ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Unexpected signal when starting test
Error: "Failed to get test coverage! Error: Failed to run tests: Unexpected signal when starting test"
```

I poked around online a bit, and it seems like it's normal/expected to not be able to disable ASLR inside a container (see for example https://security.stackexchange.com/questions/214923/disable-aslr-inside-docker-container ).  So I disabled it on the running system; here's the outer system and the container:

```
rlpowell@stodi> sudo sysctl kernel.randomize_va_space
kernel.randomize_va_space = 0
root@a7f0bda449f1:/src/zero2prod# sysctl kernel.randomize_va_space
kernel.randomize_va_space = 0
```

I suspect the issue is something like "tarpaulin can't detect the ASLR state properly from inside the container".  Unless tarpaulin actually requires running as root on the real kernel, in which case yeah this isn't gonna work.

Here's full debug output:

https://gist.github.com/05e704c84daa0633c26f6741f8a991cc

**Comment by xd009642** [comment]
so in docker (which ime is normally the same as podman) the normal approach is to use `--security-opt seccomp=unconfined`. Tarpaulin does use the personality syscall to change the ASLR flag for a binary so I guess the security options prevent that syscall from succeeding and cause the failure.

If there's an easy way to check if ASLR is disabled for the system and then skipping the personality call that _should_ hopefully solve the issue. I can look into this after work or if you're interested I can point at where in the code you'd add it (process_handling/linux.rs most likely, just grep for personality)

**Comment by rlpowell** [comment]
Oh!  No, `--security-opt seccomp=unconfined` totally worked just fine.  I couldn't find anywhere *saying* that that would work, or I would have tried it.  :)

**Comment by rlpowell** [comment]
I definitely see that the docs say to do that, but I wasn't searching on `seccomp`, I was searching on the error, so it might be worth mentioning ASLR in the docs somewhere?

Also, `--security-opt seccomp=/tmp/seccomp.json` works, where /tmp/seccomp.json is https://github.com/moby/moby/blob/master/profiles/seccomp/default.json with the following diffs ; this is a much safer option.

Thanks for the help!

```diff
--- /tmp/seccomp.json.orig      2022-09-05 10:14:53.781705007 -0700
+++ /tmp/seccomp.json   2022-09-05 10:14:56.109701729 -0700
@@ -424,66 +424,7 @@
                        "names": [
                                "personality"
                        ],
-                       "action": "SCMP_ACT_ALLOW",
-                       "args": [
-                               {
-                                       "index": 0,
-                                       "value": 0,
-                                       "op": "SCMP_CMP_EQ"
-                               }
-                       ]
-               },
-               {
-                       "names": [
-                               "personality"
-                       ],
-                       "action": "SCMP_ACT_ALLOW",
-                       "args": [
-                               {
-                                       "index": 0,
-                                       "value": 8,
-                                       "op": "SCMP_CMP_EQ"
-                               }
-                       ]
-               },
-               {
-                       "names": [
-                               "personality"
-                       ],
-                       "action": "SCMP_ACT_ALLOW",
-                       "args": [
-                               {
-                                       "index": 0,
-                                       "value": 131072,
-                                       "op": "SCMP_CMP_EQ"
-                               }
-                       ]
-               },
-               {
-                       "names": [
-                               "personality"
-                       ],
-                       "action": "SCMP_ACT_ALLOW",
-                       "args": [
-                               {
-                                       "index": 0,
-                                       "value": 131080,
-                                       "op": "SCMP_CMP_EQ"
-                               }
-                       ]
-               },
-               {
-                       "names": [
-                               "personality"
-                       ],
-                       "action": "SCMP_ACT_ALLOW",
-                       "args": [
-                               {
-                                       "index": 0,
-                                       "value": 4294967295,
-                                       "op": "SCMP_CMP_EQ"
-                               }
-                       ]
+                       "action": "SCMP_ACT_ALLOW"
                },
                {
                        "names": [
```

**Comment by xd009642** [comment]
Ah yeah I'll adapt the docs accordingly, also thanks for that snippet I'll add it to the ever increasing readme :sweat_smile:

**Comment by rlpowell** [comment]
Awesome thank you!  And thank you for the tool!

**Comment by xd009642** [comment]
Updated the readme
