### ISSUE TITLE
Mention the recompilation thing in the docs maybe?

### ISSUE THREAD

**Issue by rlpowell** [xd009642/tarpaulin#1088]
I wrote a very long bug report about tarpaulin recompiling everything and then I decided to search *closed* issues and found https://github.com/xd009642/tarpaulin/issues/1076 :D 

It might be nice to mention "rebuild" or "recompile" in the docs and point to that or something.

**Comment by rlpowell** [comment]
FYI not only does setting RUSTFLAGS to the flags used by tarpaulin *not* solve the problem, but running `export RUSTFLAGS="-Cdebuginfo=2 --cfg=tarpaulin -Clink-dead-code"` , in fact, causes `cargo check` to recompile all dependencies even when I change a single character in a comment in a single file. :D

In fact, `export RUSTFLAGS="-Cdebuginfo=2"` is sufficient to make `cargo check` do complete recompilations.  Weeee!

`cargo tarpaulin --target-dir target/tarpaulin-target/ --skip-clean`  totally works, though, and cargo check and tarpaulin both separately work the way I want.

**Comment by Plebshot** [comment]
Also mentioned that yesterday in #1086
