### ISSUE TITLE
Tarpaulin build fails because quick-xml-0.23.0 was yanked

### ISSUE THREAD

**Issue by maxburke** [xd009642/tarpaulin#1089]
The 0.23.0 version of the `quick-xml` package was recently yanked, which is causing version resolution issues when trying to build tarpaulin 0.21.0:

```
error: failed to compile `cargo-tarpaulin v0.21.0`, intermediate artifacts can be found at `/home/max/target`

Caused by:
  failed to select a version for the requirement `quick-xml = "^0.23"`
  candidate versions found which didn't match: 0.25.0, 0.24.1, 0.22.0, ...
  location searched: crates.io index
  required by package `cargo-tarpaulin v0.21.0`
```

**Comment by xd009642** [comment]
So there's some breaking changes in the APIs which I'll try to look at tomorrow to get a new version out. But otherwise does `cargo install --locked` work?

**Comment by xd009642** [comment]
I've just updated the quick-xml in tarpaulin so it's in the develop branch if you want to install from there until released. I'll either release a new version today or tomorrow most likely to see if I can land some other features before the end of monday

**Comment by maxburke** [comment]
Thank you very much! (btw, Tarpaulin is awesome, thank you for all your work on it!)
