### ISSUE TITLE
Inconsistent Failed to instrument test executable error

### ISSUE THREAD

**Issue by kaimen-sano** [xd009642/tarpaulin#1094]
**Describe the bug**
Running on WSL 1 (ubuntu), and sometimes tarpaulin works fine, but most of the time the tests run successfully and then I receive this error:
```
ERROR cargo_tarpaulin: Failed to get test coverage! Error: Failed to run tests: Failed to instrument test executable
Error: "Failed to get test coverage! Error: Failed to run tests: Failed to instrument test executable"
```

**To Reproduce**
Run tarpaulin under WSL 1
```
cargo tarpaulin --frozen --locked --out=html --no-fail-fast --follow-exec
```
I am running in a Cargo workspace, not sure if that affects tarpaulin.

Often after running the same command 5 or 6 times will finally result in tarpaulin succeeding once, sometimes tarpaulin never will.

**Comment by xd009642** [comment]
I've recently done a lot of windows improvements, in the latest tarpaulin release. Not sure if they'll hit WSL but if you have time to test it again I'd be interested in hearing back!

**Comment by kaimen-sano** [comment]
> I've recently done a lot of windows improvements, in the latest tarpaulin release. Not sure if they'll hit WSL but if you have time to test it again I'd be interested in hearing back!

Great work! Running
```
cargo tarpaulin --frozen --locked --out=html --no-fail-fast --engine llvm
```
has worked beautifully for me.

Thanks for all your work!
