### ISSUE TITLE
Spurious segfaults when running cargo-tarpaulin 0.22

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [xd009642/tarpaulin#1114]
We experience spurious segfaults in our coverage runs on our GitHub CI as well as locally.

This is one example:
https://github.com/geo-engine/geoengine/actions/runs/3233572540/jobs/5295594939

It ran through the second time in this case.
All tests work in our non-tarpaulin runs.

Unfortunately, I cannot generate a minimal example to reproduce it in a smaller setting.
But I am wondering if other projects experience similar problems.

We currently went back to 0.21 to have our CI working again.

**Comment by xd009642** [comment]
That's pretty odd, as 0.22.0 didn't touch the ptrace tracing at all, the only change that could impact it is setting `--ignore-tests` as default. 

You could always try `--engine llvm` to use the llvm coverage but some projects are reporting spurious failures in CI I can't recreate (but only one person)

**Comment by xd009642** [comment]
Closing as inactive
