### ISSUE TITLE
Release has unconventional name

### ISSUE THREAD

**Issue by nstinus** [xd009642/tarpaulin#1129]
The latest release is named  cargo-tarpaulin-0.22.0-travis.tar.gz  which does not show the target triple.
It seems to be a x86_64-unknown-linux-gnu arch. It should be named cargo-tarpaulin-0.22.0-x86_64-unknown-linux-gnu.tar.gz

This has the bad consequence of tricking `cargo binstall` into thinking that it is fine for a musl executable.

**Comment by xd009642** [comment]
This has now changed, whole release stuff is reworked
