### ISSUE TITLE
Offer a release for x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by nstinus** [xd009642/tarpaulin#1130]
For users living on old distros (e.g. CentOs 7), a musl release would be very helpful!

**Comment by xd009642** [comment]
So I've tried a release today and it looks like it didn't work if you don't mind having a look as the person who did the PR :eyes:  https://github.com/xd009642/tarpaulin/actions/runs/3498060423

**Comment by nstinus** [comment]
https://github.com/xd009642/tarpaulin/pull/1136

**Comment by xd009642** [comment]
Okay that didn't fix it but I've gone through 5 iterations of CI "fixes" and it looks like it will work next time there's a release. Github actions seems to only checkout current commit so it failed on the command to get the current tag but built fine. 

I'll try and smash through a few issues over the weekend to justify another release to test it :smiling_face_with_tear:

**Comment by nstinus** [comment]
I'm sorry it was so difficult, to be honest, I have zero experience with actions... Thank you!

**Comment by xd009642** [comment]
It's okay, I should have been smarter than trusting sensible looking changes in CI would "just work". And as long as it adds something useful for users it's worth the hassle in the end :sweat_smile:
