### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SkyfallWasTaken** [xd009642/tarpaulin#1133]
**Describe the bug**
Okay, so this is probably a dumb question, but when I try to use `cargo-tarpaulin` it errors with this:

```
❯ cargo tarpaulin
/home/skyfall/.cargo/bin/cargo-tarpaulin: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I'm not sure what I'm doing wrong, because `apt` says that `libssl-dev` is already installed:

```
❯ sudo apt install libssl-dev
sudo: unable to resolve host hypex-pc: Name or service not known
[sudo] password for skyfall: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libssl-dev is already the newest version (3.0.2-0ubuntu1.7).
0 to upgrade, 0 to newly install, 0 to remove and 10 not to upgrade.
```

Also, running `fd` successfully finds `libssl.so`:

```
❯ fd libssl.so
usr/lib/i386-linux-gnu/libssl.so.3
usr/lib/x86_64-linux-gnu/libssl.so
usr/lib/x86_64-linux-gnu/libssl.so.3
```

**To Reproduce**
Just running `cargo-tarpaulin`.

**Expected behavior**
`cargo-tarpaulin` finds `libssl.so` successfully.

**Comment by xd009642** [comment]
So the error says `libssl.so.1.1` but you have 3. Maybe try installing with the `vendored-openssl` feature  and see if that solves the ssl issue? So `cargo install --features vendored-openssl cargo-tarpaulin`

**Comment by SkyfallWasTaken** [comment]
Hey,

Thanks for the help! I can confirm that using the vendored-openssl feature works.

**Comment by xd009642** [comment]
Cool I'll close this as resolved then :+1:

**Comment by ofersadan85** [comment]
Hey @xd009642 , Just encountered this error on two machines running Ubuntu 22.04 and one more on WSL (Ubuntu 22.04 as well) and running `cargo install cargo-tarpaulin` fixed it. The error came only by installing with `binstall`... you might want to check that
