### ISSUE TITLE
[Windows] Unsanitized file path in lcov.info

### ISSUE THREAD

**Issue by dkudlek** [xd009642/tarpaulin#1146]
# Describe the bug
The generated `lcov.info` contains unsanitized file paths. 
- Expected: `SF:C:\Workspace\challenge-rust\explore_dungeon\src\main.rs` 
- Actual: `SF:\\?\C:\Workspace\challenge-rust\explore_dungeon\src\main.rs` 

# To Reproduce
- Checkout e.g. https://github.com/dkudlek/challenge-rust
- Run `cargo tarpaulin --ignore-tests --out Lcov --workspace`

# [Workaround :link:](https://github.com/dkudlek/tarpaulin/commit/78815b9af5f7fb5a29f7be6da98f18c30adc487a)
I ran `fix_unc_path` from `use crate::path_utils::fix_unc_path;` in `src/report/lcov.rs`. Ideally, the path should be sanitized when read from the OS. As far as I can see `fix_unc_path` is only applied for the path of the output file. 

# Software versions
- rustc 1.64.0 (a55dd71d5 2022-09-19)
- cargo 1.64.0 (387270bc7 2022-09-16)
- cargo-tarpaulin version: 0.23.1
- Windows 10: 21H2 (Build 19044.2251)
- VS Code:  1.73.1
- Coverage Gutters v2.10.2

**Comment by xd009642** [comment]
sorry for silence, I am working on this and your other issue. Just tackling an issue where it happens only on windows and via CLI but not running on windows via my integration tests, so fiddlier than I hoped to solve

**Comment by AntoniosBarotsis** [comment]
Weirdly enough I seem to also be getting something similar?

```rs
error: could not compile `unicode-general-category` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Jan 03 19:07:54.718 ERROR cargo_tarpaulin: Failed to compile tests!
error: couldn't read \\?\C:\Users\anton\Documents\Github\qr-rs\target\debug\build\unicode-general-category-f010f3245611d5fa\out/category.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)
 --> C:\Users\anton\.cargo\registry\src\github.com-1ecc6299db9ec823\unicode-general-category-0.6.0\src\category.rs:1:1
  |
1 | include!(concat!(env!("OUT_DIR"), "/category.rs")); // generated by build.rs
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
```

My situation is a bit different as I am just trying to run it with no args locally but I get this error which also includes the `?` in the path, wasn't sure what that was.

Is this related?

**Comment by xd009642** [comment]
@AntoniosBarotsis maybe slightly but only in the way cargo et al work on windows as the `OUT_DIR` is set by rustc when compiling and I don't have any influence over it from tarpaulin. This part of the pipeline is just `cargo test --no-run` at work with some env vars and other args but it mostly all comes from cargo metadata or passing on user arguments directly

**Comment by AntoniosBarotsis** [comment]
I see, it's weird because I have used tarpaulin before on other projects and it worked fine there, not sure what causes it to break

**Comment by xd009642** [comment]
So the issue with this seems to be somewhere an unc path is returned, either when parsing CLI args on windows, or cargo metadata or something before I build tests and is set as the CWD when building. And then when the build happens there's a dummy path like `/?//C://` and because that's what the CWD looks like cargo kinda applies it elsewhere and then things break. Just working on fixing this by normalising paths everywhere and we'll see how it goes from there.

**Comment by xd009642** [comment]
Okay it looks like I've fixed this if anyone wants to give the `fix/unc-paths-in-report` branch a spin just to make sure i didn't miss anything

**Comment by xd009642** [comment]
Okay I'm now very confident on this, I'll hold off on merging for a couple of days to give people time to test it but then I'll merge. Hopefully this banishes all the path issues including if someone is insane enough to provide an absolute path like `/?//C://` as a CLI arg

**Comment by AntoniosBarotsis** [comment]
Just tried it locally and it does indeed work, nice!

I didn't quite get where the issue was but just making sure that (in case it was not in the code from this repo) you opened an issue for it 😄

**Comment by AntoniosBarotsis** [comment]
Ah ok just saw #1150, hope you escape path hell soon ❤️
