### ISSUE TITLE
Failed to generate coverage report if protobuf is added as dependeccy

### ISSUE THREAD

**Issue by DCMinds** [xd009642/tarpaulin#1176]
I have created a simple project "Hello World".  and written a test case for it.
In cargo.toml file added protobuf as depedendency.

When i am running "**cargo tarpaulin  --release --out Xml"** command it is giving below error
==========================================================
   Compiling protobuf-support v3.2.0
error: The pipe is being closed. (os error 232)
warning: build failed, waiting for other jobs to finish...
error: could not compile `protobuf` due to 2 previous errors
Jan 10 15:54:05.813 ERROR cargo_tarpaulin: Failed to compile tests!
error: couldn't read \\?\C:\WS\AXP\axp-agent\target\release\build\protobuf-cc46779d5f1c28ee\out/version.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)        
   --> C:\Users\chaudhd\.cargo\registry\src\art-bobcat.autodesk.com-97db0ae37873e380\protobuf-3.2.0\src\lib.rs:108:1
    |
108 | include!(concat!(env!("OUT_DIR"), "/version.rs"));
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)

Error: "Failed to compile tests!\nerror: couldn't read \\\\?\\C:\\WS\\AXP\\axp-agent\\target\\release\\build\\protobuf-cc46779d5f1c28ee\\out/version.rs: The filename, directory name, or volume label syntax is incorrect. (os error 123)\n   --> C:\\Users\\chaudhd\\.cargo\\registry\\src\\art-bobcat.autodesk.com-97db0ae37873e380\\protobuf-3.2.0\\src\\lib.rs:108:1\n    |\n108 | include!(concat!(env!(\"OUT_DIR\"), \"/version.rs\"));\n    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    |\n    = note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)\n\n"
================================================================

**Note:** Without protobuf as dependency test coverage reports are getting generated

running 1 test
test tests::main_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

**Comment by xd009642** [comment]
It looks like this is the same issue as #1146 and as such if you try the `fix/unc-paths-in-report` branch that may solve it. TL;DR on the issue, windows path canonicalization is horribly broken in that it makes things an UNC path which while valid most filesystem APIs don't handle correctly. This then means when I set all the env cargo needs when spawning as a process like CWD the rust compiler ends up processing a bunch of unc paths and falling over in some places

**Comment by DCMinds** [comment]
@xd009642 , Thanks for the quick response.
Looks like this issue is with latest version of protobuf crate -> 3.2.0 and 3.1.0
When i switched to version 3.0.3, I did not get this issue

**Comment by DCMinds** [comment]
I am getting this issue for mutliple dependency, now for bingen

**Comment by DCMinds** [comment]
@xd009642 thanks for the suggestion https://github.com/xd009642/tarpaulin/issues/1146
It solved the issue

**Comment by xd009642** [comment]
Cool it's now been merged, waiting for a PR to drop to fix the release pipelines and then there'll be a new release - otherwise you can install from develop branch

**Comment by xd009642** [comment]
And released! C'est fin
