### ISSUE TITLE
Mentioned travis-install.sh not found in repository

### ISSUE THREAD

**Issue by jennydaman** [xd009642/tarpaulin#1184]
https://github.com/xd009642/tarpaulin/blob/79a9720ca75f6415c85bb963ba27088e921e7d74/README.md?plain=1#L423

**Comment by xd009642** [comment]
Ah right, that was deprecated a bit ago, time to purge it from docs and recommend other install methods

**Comment by xd009642** [comment]
Updated the readme to remove mention
