### ISSUE TITLE
Support for procedural macros

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#120]
So I have [one crate](https://github.com/djc/askama) where most of the code is actually compiled and executed at compile-time (through a `proc_macro_derive()` function). Do you think this should work with tarpaulin? If not, how hard would it be to make it work?

**Comment by xd009642** [comment]
So there is a way to do this, if you check the **Procedural Macros** section in the README.md. There's a [runtime macros crate](https://crates.io/crates/runtime-macros) which evaluates compile time macros at run time so you can test them!

**Comment by djc** [comment]
Ohh, sorry I missed that. It won't work out of the box for my derive-based macros, but I'll see about getting that fixed.

**Comment by xd009642** [comment]
It might be worth raising an issue on the runtime macros repo to see if
they'll add support!
