### ISSUE TITLE
Add run-to-run coverage changes reporting

### ISSUE THREAD

**Issue by RadicalZephyr** [xd009642/tarpaulin#123]
This would be really useful for when bringing an untested codebase under test.  It would require storing some data on disk after every run but I think the strategy that [Criterion.rs] uses would work for tarpaulin as well.

[criterion]: https://github.com/japaric/criterion.rs

**Comment by xd009642** [comment]
So run-to-run coverage diffs are implemented in other tools like [coveralls.io](https://coveralls.io), [codecov.io](https://codecov.io) and if someone just wants to run on their local pc they can generate xml reports and diff them with [pycobertura](https://github.com/aconrad/pycobertura). Based on this I'm not sure about adding it to tarpaulin, though as we branch out to other types of coverage it may become more desirable

**Comment by xd009642** [comment]
I'll add something to the readme later on and close this once it's done :+1:

**Comment by xd009642** [comment]
I've added this on a feature branch I've not yet merged. It only stores the previous run to avoid bloating the target folder. If you're interested/have-any-feedback it makes the report look like so:

```
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/xd009642/code/rust/tarpaulin/tests/data/simple_project/target/debug/deps/simple_project-3b89eb02ba44d908

running 2 tests
..
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/lib.rs: 4/5 +0%
|| src/unused.rs: 5/5 +100%
|| 
90.00% coverage, 9/10 lines covered, +50% change in coverage
```
