### ISSUE TITLE
Parsing failed on Windows 11

### ISSUE THREAD

**Issue by strowk** [xd009642/tarpaulin#1282]
**Describe the bug**
I run `cargo tarpaulin` and receive error `Error: "Parsing failed"`.
I am using Windows 11 and run this from Git Bash. 

Complete ouptut (skipping compilation):
```
    Finished test [unoptimized + debuginfo] target(s) in 51.35s
May 11 00:51:58.814  INFO cargo_tarpaulin::process_handling: running C:\work\probranchinator\target\debug\deps\probranchinator-5c461d614048b00c.exe
May 11 00:51:58.815  INFO cargo_tarpaulin::process_handling: Setting LLVM_PROFILE_FILE

running 5 tests
test tests::analysis_test::test_analysis_one_branch ...
 ███████████████████████████████████████████████████ 0/1 branches analysed in 0s                              
ok
test tests::analysis_test::test_analysis_unrelated_branches ... ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░2 branches analysed in 0s                              
ok
test tests::analysis_test::test_analysis_up_to_date_and_fast_forward ... ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░2 branches analysed in 0s                              
ok
test tests::repo_test::test_delete_remote_branch ... Pruning origin
URL: file:///C:/Users/strow/AppData/Local/Temp/.tmppCMm2h/my-repo.git/
 * [pruned] origin/test-branch
ok
test tests::repo_test::test_get_repo ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.21s

May 11 00:52:00.254  INFO cargo_tarpaulin::statemachine::instrumented: For binary: target\debug\deps\probranchinator-5c461d614048b00c.exe
May 11 00:52:00.254  INFO cargo_tarpaulin::statemachine::instrumented: Generated: target\tarpaulin\profraws\probranchinator-5c461d614048b00c.exe_12256345248713744009_0-25344.profraw
May 11 00:52:00.254  INFO cargo_tarpaulin::statemachine::instrumented: Merging coverage reports
May 11 00:52:00.260 ERROR cargo_tarpaulin: Parsing failed
```

I did not pass "--engine", not sure if it is ptrace or llvm instrumentation.

**To Reproduce**
I am getting it on this repository - https://github.com/strowk/probranchinator

Attached from "target/tarpaulin/profraws":
[probranchinator-5c461d614048b00c.exe_12256345248713744009_0-25344.zip](https://github.com/xd009642/tarpaulin/files/11446534/probranchinator-5c461d614048b00c.exe_12256345248713744009_0-25344.zip)

**Expected behavior**
No errors, result of coverage analysis.

**Comment by strowk** [comment]
Note, that the output is OK when I run same project via docker like this: 

```
docker run --security-opt seccomp=unconfined -ti -v "$(pwd -W):/volume" xd009642/tarpaulin bash -c " git config --global user.name 'Test Fella' && git config --global user.email 'justfortest@domain.example' &&  cargo tarpaulin"
```
(`pwd -W` is specific for combination of Mingw and docker in Windows, `git config` is  for tests as they use git CLI a little bit)

I get "10.40% coverage, 99/952 lines covered" and more output, so this seems a success (barring low coverage, but that's why I want to measure it in the first place).
This run via `docker` utilizing wsl 2, which is basically linux in VM, so basically same as real linux AFAIK. 

This make me think that the issue I have is potentially Windows specific.

**Comment by xd009642** [comment]
Sorry it's taken a while, I did just download the file you uploaded to test to see if there was anything i could glean from it. Running with the llvm tools I get:

```
error: probranchinator-5c461d614048b00c.exe_12256345248713744009_0-25344.profraw: malformed instrumentation profile data: function name is empty
```

There's a chance this may be OS specifc as these tools aren't designed to parse files generated on different architectures to the host and I'm running on Linux. I'll get access to a windows machine some point next week and test it there as the project works fine on linux for me in tarpaulin.

**Comment by jgardona** [comment]
It happens to me also.

![image](https://github.com/xd009642/tarpaulin/assets/146892539/44b21a5c-8455-48c7-8480-fd6edb0cb1a1)

**Comment by Sewer56** [comment]
I reproduced this on Linux.
It seems that this is broken on Nightly rust, on Stable, things work just fine.

**Comment by xd009642** [comment]
So releasing a new version today that may solve this, let me know how it works - sorry for the delay

**Comment by Sewer56** [comment]
I re-ran a workflow that previously failed on one of my personal FOSS projects.
I can confirm this now runs.

Thank you a lot.
