### ISSUE TITLE
Does tarpaulin support code coverage without unit tests?

### ISSUE THREAD

**Issue by tmakatos** [xd009642/tarpaulin#1284]
I'm testing my application using component testing (in addition to unit testing) by talking to it's external API and would like to see which  code paths are excercised. It doesn't look like tarpaulin can provide code coverage in this case?

**Comment by tmakatos** [comment]
> So if you have a program that spins up a server and then sends a bunch of requests to it, closes down the server and then exits you can get coverage for it.

It's not as simple because the process under test needs to run in a separate directory (requires some mocked directory structure).

> If the API is built separately to building the tests you may have to do cargo tarpaulin --print-rust-flags as well as your other flags to get the RUSTFLAGS variable to build the server with beforehand.

Do you mean that I should do `cargo build` using whatever `RUSTFLAGS` `cargo tarpaulin --print-rust-flags` spits out? And then  simply run the process under test directly? E.g. `target/debug/foo`?

**Comment by xd009642** [comment]
Well as long as your directory is within the project directory it's fine, it can be a subdirectory.

And yes you should cargo build with those rustflags

**Comment by tmakatos** [comment]
> And yes you should cargo build with those rustflags

I've switched to a hello world example to keep things simple:
```
$ cargo clean
$ RUSTFLAGS="-Cdebuginfo=2 --cfg=tarpaulin -Clink-dead-code" cargo build
   Compiling llvm-tools v0.1.1
   Compiling hello_cargo v0.1.0 (.../tmp/hello_cargo)
    Finished dev [unoptimized + debuginfo] target(s) in 0.86s
$ target/debug/hello_cargo
Hello, world!
``` 
Am I supposed to see any code coverage information?

As opposed to:
```
$ cargo clean
$ cargo tarpaulin --skip-clean --command build --bin hello_cargo
May 16 10:44:41.644  INFO cargo_tarpaulin::config: Creating config
May 16 10:44:41.743  INFO cargo_tarpaulin: Running Tarpaulin
May 16 10:44:41.744  INFO cargo_tarpaulin: Building project
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
May 16 10:44:41.829  INFO cargo_tarpaulin::process_handling::linux: Launching binary
May 16 10:44:41.829  INFO cargo_tarpaulin::process_handling: running 
.../tmp/hello_cargo/target/debug/hello_cargo
Hello, world!
May 16 10:44:42.137  INFO cargo_tarpaulin::report: Coverage Results:
|| Uncovered Lines:
|| Tested/Total Lines:
|| src/main.rs: 2/2
||
100.00% coverage, 2/2 lines covered
```
Which seems to be doing what I want.

**Comment by xd009642** [comment]
> If the API is built separately to building the tests you may have to do cargo tarpaulin --print-rust-flags

The point of the building with Rust flags is if you tests spawn a process or something which is already built and building+running the acceptance tests won't build all the artefacts used for the tests. You may not need it

**Comment by tmakatos** [comment]
> The point of the building with Rust flags is if you tests spawn a process or something which is already built

My tests do spawn the already built process under test, so that's the behavior I want. However, in the hello world example I posted earlier, I don't seem to get any coverage? Do I still need to run the process under test via some specific `cargo tarpaulin` command?

**Comment by xd009642** [comment]
So you run it via tarpaulin if you want coverage, so something like:

```
RUSTFLAGS="-Cdebuginfo=2 --cfg=tarpaulin -Clink-dead-code" cargo build  
cargo tarpaulin --skip-clean --command build --bin hello_cargo
```

The first step is just for building things which aren't `hello_cargo` but are spawned by it

**Comment by xd009642** [comment]
Maybe `--root` might do it, not 100% sure. 

Also I don't think it's worth adding this to the readme tbh, it's a niche use case maybe refining the help text for `--command` but I'm not fussed enough to spend time bikeshedding it. If a PR was raised that was a clear improvement though I would merge

**Comment by xd009642** [comment]
Going to close this as solved
