### ISSUE TITLE
Unknown Error During Run

### ISSUE THREAD

**Issue by piperRyan** [xd009642/tarpaulin#129]
Rust Version: 1.27.1
Cargo Version: 1.27.0
Tarpaulin Version: 0.6.3
OS: Arch Linux

What I did to produce the error: 

```
env RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force cargo-tarpaulin
cargo tarpaulin -o Xml -v
```

Error Returned: 

```
Error during run
```

Other Info: 

Worked fine with rust 1.26. I'll see if I can reproduce the issue in a docker container later today.

**Comment by xd009642** [comment]
Can you also provide the project it happened with so I can investigate myself?

**Comment by piperRyan** [comment]
Sorry, I can't provide the project as it company owned code, but I'll try to figure out a simplified example that  wont' break any IP agreements. If there is any more debugging you want from me let me know.

**Comment by piperRyan** [comment]
Yup it was a test that failed (forgot to save the file :slightly_frowning_face: ) so I have to chalk this up to ignorance on my part. Thanks for the quick response!

**Comment by xd009642** [comment]
No problem, happens to all of us from time to time :+1:
