### ISSUE TITLE
Mismatches between tarpaulin output and codecov imports

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#130]
I'm looking at my [last build for wayland-rs](https://travis-ci.org/Smithay/wayland-rs/jobs/404906115)

tarpaulin's stdout offers me this:

```
Coverage Results
Tested/Total Lines:
wayland-client/src/cursor.rs: 0/74
wayland-client/src/display.rs: 21/61
wayland-client/src/egl.rs: 0/27
wayland-client/src/event_queue.rs: 24/103
wayland-client/src/globals.rs: 21/69
wayland-client/src/proxy.rs: 65/172
wayland-commons/src/lib.rs: 2/10
wayland-scanner/src/c_code_gen.rs: 314/350
wayland-scanner/src/c_interface_gen.rs: 83/84
wayland-scanner/src/common_gen.rs: 134/142
wayland-scanner/src/lib.rs: 8/8
wayland-scanner/src/parse.rs: 142/161
wayland-scanner/src/protocol.rs: 33/35
wayland-scanner/src/side.rs: 4/4
wayland-scanner/src/util.rs: 14/16
wayland-server/src/client.rs: 16/54
wayland-server/src/display.rs: 29/99
wayland-server/src/event_loop.rs: 22/108
wayland-server/src/globals.rs: 13/21
wayland-server/src/resource.rs: 45/195
wayland-server/src/sources.rs: 10/93
wayland-sys/src/client.rs: 7/13
wayland-sys/src/common.rs: 0/8
wayland-sys/src/cursor.rs: 0/13
wayland-sys/src/server.rs: 17/47
52.06% coverage, 1024/1967 lines covered
Tarpaulin finished
```

This the report [once uploaded to codecov](https://codecov.io/gh/Smithay/wayland-rs/list/8111f3bc4b1b85c9a4408fcbbbc1590f583cb0e2/) is missing almost half of the files, and only displays a total coverage of 890/1471 (as opposed to tarpaulin's 1024/1967 output in the logs).

It seems to me that there must be some kind of mismatch, either in tarpaulin's XML output, or in the way it is imported by codecov. If this a known problem? Did I likely misconfigure something?

**Comment by xd009642** [comment]
It's down to #127 sorry meant to release an update on this the other day! I'll release 0.6.4 now and that will sort it!

**Comment by xd009642** [comment]
Right it's all pushed, travis usually takes around 30 minutes to go through the whole cargo publish etc for a new release so you should see this issue disappear within the hour! Gonna close this issue now though feel free to comment if you observe the same issue again and I'll reopen it :smile:

**Comment by vberger** [comment]
Are you sure this is the same issue?

In my case tarpaulin does correctly report the coverage of all files in stdout, and they also all correctly appear in the XML it generates, but for some reason they do not appear on codecov website... After some digging, it seems awfully similar to https://github.com/codecov/codecov-python/issues/136 so I'm suggesting it might actually be a issue of codecov... ?

**Comment by xd009642** [comment]
huh, I figured it would have been the same issue as stdout reports were missing lines. Maybe not though

**Comment by vberger** [comment]
Anyway, I'll still restart my build as soon as 0.6.4 is on crates.io, to be sure

**Comment by vberger** [comment]
Nope, does not solve it.

Though, I tried downloading the data from codecov, and the XML I get does contain the coverage for all files. So it looks like the issue is really codedov deciding that for some reason some files don't really exist...

**Comment by xd009642** [comment]
Well that's definitely a strange one. Wonder if it can't find the corresponding source files in the repo..

I'm tempted to close this if it's literally just codecov being strange. Have you raised an issue with codecov?

**Comment by vberger** [comment]
Yes, this is likely 100% a codecov issue, this can be closed. I'm investigating it.

**Comment by vberger** [comment]
Well, I think I've understood the core of the issue, and it might actually be a tarpaulin problem:

The files that are missing from the codecov UI are exactly the files where there exists in my repository an other file with the same filename in an other directory.

I suspect this is because tarpaulin only puts the filename rather than the complete relative path from the project root in its `<class name="..." filename="file.rs">` definitions.

I don't know much the cobertura format, so I can't say if its tarpaulin not generating it properly or codecov not parsing it properly, though.
