### ISSUE TITLE
Missing github release for `0.26.1`

### ISSUE THREAD

**Issue by FirelightFlagboy** [xd009642/tarpaulin#1341]
Hello, the release for `0.26.1` is missing from the [github releases](https://github.com/xd009642/tarpaulin/releases)

Could you add it ?

**Comment by xd009642** [comment]
Ah yeah something went wrong with CI there (doofus here messed up changelog and cargo release action didn't work as a result). I've moved the tag to another commit so once CI finishes it should upload

**Comment by xd009642** [comment]
Aaa didn't mean to close - there is a chance crates.io failing to upload because the release already exists will screw up the release CI. I'll keep watching it with bated breath

**Comment by xd009642** [comment]
Okay it seems to be working and things are uploading - so I'll keep this closed as completed :tada:

**Comment by FirelightFlagboy** [comment]
One last thing is to mark the new release as latest :wink:

**Comment by xd009642** [comment]
Done!
