### ISSUE TITLE
Skipping module won't work

### ISSUE THREAD

**Issue by Aeradriel** [xd009642/tarpaulin#138]
`#[cfg_attr(tarpaulin, skip)]` allows according to the documentation to skip either a function or a module from the coverage. It works great when putting it directly on a function but if I want to ignore a whole module it won't work.
Let's say I have my `main.rs` file which declares a `ignore_me` module located at `./ignore_me.rs`, this following snippet won't achieve the skip.

```rust
#[cfg_attr(tarpaulin, skip)]
mod ignore_me;
```

The problem is that no module is redefined in the target file because thanks to how rust namespacing works, you are already in the right module. So there is no way to put the macro "directly" on to the module other that the way I showed above (or maybe there is, so I would love to hear about it !) and putting the macro on top of every single function/trait in the module is very heavy.

To be clear, tarpaulin will still work well and report everything that needs to be, it just won't ignore the targeted modules.

**Comment by xd009642** [comment]
Ah it must only work on inline modules then. I'll look at the work to update the source analysis to ignore external modules and let you know when it's done.

**Comment by xd009642** [comment]
So I'm working on this now. But I did remember tarpaulin has an `--exclude-files` command for the `#[cfg_attr(tarpaulin, skip)]` on a `mod x;` use-case. 

Still working on this but it could help you out in the meantime.

**Comment by xd009642** [comment]
So sorry about the delay but I've just got this finished, tested and added into tarpaulin! You can try it out on the develop branch and let me know if there are anymore issues :+1:

**Comment by Aeradriel** [comment]
I'll test this today and give you some feedbacks.

**Comment by Aeradriel** [comment]
It looks good to me ! Can you comment here again when it will be published ?

**Comment by xd009642** [comment]
So I pushed the release out now, so it'll be published once the travis build finishes. So given past experience roughly half an hours time :+1:
