### ISSUE TITLE
Tarpaulin removed -v shorthand for --verbose in 0.27

### ISSUE THREAD

**Issue by msrd0** [xd009642/tarpaulin#1388]
**Describe the bug**
I used to use `-v` flag for tarpaulin. It stopped working on the latest version.

**To Reproduce**
Install version 0.27 of tarpaulin and try running tarpaulin with the `-v` flag:

 - <pre>sudo pacman -Sy cargo-tarpaulin=0.27.0-2</pre>
 - <pre>cargo tarpaulin -v</pre>

**Expected behaviour**
Tarpaulin runs with verbose logging.

**Actual behaviour**
```
error: unexpected argument '-v' found

  tip: to pass '-v' as a value, use '-- -v'

Usage: cargo tarpaulin [OPTIONS] [-- <ARGS>...]

For more information, try '--help'.
```

**Comment by xd009642** [comment]
@MiniaczQ do you mind having a look at this if you have time as it's related to the clap 2 -> 4 migration. If not I can try and find some time after work some day this week

**Comment by msrd0** [comment]
This turned out to be pretty easy to fix

**Comment by MiniaczQ** [comment]
Sorry for that 😅
