### ISSUE TITLE
new travis.yml's "after-succes" snippet not cached

### ISSUE THREAD

**Issue by zbraniecki** [xd009642/tarpaulin#139]
Since the new snippet was offered for travis.yml, each build of stable takes much longer.

Here's an example of a crate that takes ~1-2m per build on beta/nightly and close to 22m on stable: https://travis-ci.org/projectfluent/fluent-rs/builds/406926386

Here's another: https://travis-ci.org/zbraniecki/annotate-snippets-rs
And another: https://travis-ci.org/unclenachoduh/pluralrules/builds

If I understand correctly the crate is rebuilt and not cached. Is there any way to cache the crate to avoid the cost per-build?

**Comment by xd009642** [comment]
Well if the crate is installed thanks to the cache I think cargo install shouldn't do anything (unless you have the `--force` flag). This makes me think maybe things done after the ci run has succeeded aren't cached?

Tarpaulin returns -1 if a test fails so you could always replace `cargo test` with installing tarpaulin and a tarpaulin run (using `--verbose` if you want the test output as well).

I'll have a brief look into this playing with travis in case I'm wrong this is just based on my understanding of travis!

**Comment by xd009642** [comment]
I had a look in the travis docs on caching. https://docs.travis-ci.com/user/caching/ Notable line is:

`Travis CI uploads the cache after the script phase of the build, but before either after_success or after_failure.`

So if you move the tarpaulin install to a different tag it should fix the caching issue. I'm looking into what I think the best approach is right now so I can update the README accordingly.

**Comment by zbraniecki** [comment]
I moved to `before_cache` and it did fix it: https://travis-ci.org/projectfluent/fluent-locale-rs/builds :)

**Comment by xd009642** [comment]
Excellent, I've updated the readme accordingly so I'm going to close this now :+1:
