### ISSUE TITLE
`--out` casing changed with release 0.27

### ISSUE THREAD

**Issue by sosthene-nitrokey** [xd009642/tarpaulin#1392]
This may not be a bug, but it's not mentioned the release notes or in the commit message that introduced this so I'm not sure it's intentional.

The casing of the arguments of the `--out` parameter changed with the migration to Clap v4 in https://github.com/xd009642/tarpaulin/commit/d1bd48ea2ac1356ea3087b5d2d197ee58702dbd0. This means that old scripts using `--out Html` will fail (expecting `--out html`).
This is changed because [`ValueEnum` defaults to `kebab-case`](https://docs.rs/clap/latest/clap/_derive/index.html#valueenum-attributes).

This is not necessarily a bug, but it is an undocumented breaking change.

If this is not intentional (or even if it is), I think it would be great to support both casing for a while to ease the transition, maybe with a deprecation warning. This makes it easier for scripts to migrate to the new version progressively.

**Comment by MiniaczQ** [comment]
This is unintentional

**Comment by xd009642** [comment]
reverted so it should work as before and releasing a new version as we speak
