### ISSUE TITLE
Skipping a module doesn't work?

### ISSUE THREAD

**Issue by zbraniecki** [xd009642/tarpaulin#140]
I have a codegenerated module `src/rules.rs` which I want to skip in my output.

I tried placing `#[cfg_attr(tarpaulin, skip)]` at the top of the rules.rs and the result still incorporates rules.rs - https://coveralls.io/builds/18202798

Then I tried to place this line above `mod rules;` in `src/lib.rs` and the output still incorporates them: https://coveralls.io/builds/18203157

What am I doing wrong?

**Comment by xd009642** [comment]
Currently, `#[cfg_attr(tarpaulin, skip)]` only works on blocks so `mod x {}`. Issue #138 raises this and handling `mod x;` will be supported after it's implemented. So nothing wrong but above `mod rules;` will be the correct way once it's implemented!

**Comment by zbraniecki** [comment]
Thanks!

Closing as dupe of #138.

**Comment by xd009642** [comment]
Commented this on #138 but in case you didn't spot it.

"So I'm working on this now. But I did remember tarpaulin has an `--exclude-files` command for the `#[cfg_attr(tarpaulin, skip)]` on a `mod x;` use-case. 

Still working on this but it could help you out in the meantime."
