### ISSUE TITLE
Tests fail with tarpaulin, cargo test works

### ISSUE THREAD

**Issue by Michaelschnabel-DM** [xd009642/tarpaulin#1406]
**Describe the bug**
Hi, i am running my tests with this command on a machine running ubuntu:
`cargo tarpaulin --workspace --timeout 600 --out Xml --jobs 1 --engine llvm`

Especially one test keeps failing which starts up a tokio runtime because there is parallel stuff going on.
When I run just a basic `cargo test` everything is fine.

How can I get a bit more information why the test is failing with tarpaulin?
Right now this is not very helpful:
![image](https://github.com/xd009642/tarpaulin/assets/97694159/859986af-9ace-4475-8e84-2b17e345e085)

**Comment by xd009642** [comment]
You can use `--verbose` or `--debug` to get more output. If your test is using unix signals potentially it's causing some issues or something else that doesn't work well with ptrace. If that's the case `--engine llvm` may fix the issue.

**Comment by Michaelschnabel-DM** [comment]
Ill try that, thanks for the quick response!
