### ISSUE TITLE
Add --target-dir option

### ISSUE THREAD

**Issue by dpypin** [xd009642/tarpaulin#141]
Cargo [supports](https://github.com/rust-lang/rust/blob/master/RELEASES.md#cargo-1) `--target-dir` parameter which allows you to specify a different directory than target for placing compilation artifacts.
Please consider adding this parameter to `tarpaulin`.

**Comment by dpypin** [comment]
It does require a cargo update at least to version 0.28. I tried to update and got a bunch of build errors due to changes in cargo API.
Also I didn't realize, that I can use CARGO_TARGET_DIR environment variable as a workaround to set target directory and it seems working fine with `cargo tarpaulin` command.

**Comment by xd009642** [comment]
Hmm if you can use CARGO_TARGET_DIR I think I'll just close this, no need to make the tarpaulin options more complicated when there's an easier solution :+1:
