### ISSUE TITLE
Return an error if the coverage is decreasing

### ISSUE THREAD

**Issue by nikgul** [xd009642/tarpaulin#1411]
**Describe the feature**
It would be nice if tarpaulin would return an error if the coverage percentage is decreasing, kinda like you set a threshold with --fail-under with a set percentage.

**Comment by xd009642** [comment]
Closed as wontfix for reason mentioned in PR (replicated here)

> I've thought about this more and I've decided it's not something I'm looking to merge into tarpaulin, there's some complexity in the behaviour RE times when fail-decreasing doesn't fail if coverage decrease and also the vast majority of users are running in CI and then this type of functionality is provided by other services like coveralls etc.
