### ISSUE TITLE
Machine readable summary

### ISSUE THREAD

**Issue by szabgab** [xd009642/tarpaulin#1415]
While experimenting with tarpaulin I ran it on https://github.com/dtolnay/unicode-ident using the following command:

```
cargo tarpaulin --workspace --out html --out json
```

It created the two output files as expected and printed the following to the screen:

```
INFO cargo_tarpaulin::report: Coverage Results:
|| Tested/Total Lines:
|| diagram/src/main.rs: 0/15 +0.00%
|| generate/src/main.rs: 0/84 +0.00%
|| generate/src/output.rs: 0/6 +0.00%
|| generate/src/parse.rs: 0/35 +0.00%
|| generate/src/write.rs: 0/52 +0.00%
|| src/lib.rs: 12/13 +0.00%
|| src/tables.rs: 0/20 +0.00%
|| 
5.33% coverage, 12/225 lines covered, +0.00% change in coverage
```

I looked in the resulting json file, but could not see this summary.

I wonder if there is a way to get this summary in a machine-readable format (e.g. as json)?

If there is no such way yet, then IMHO it would be a good idea to either add it to the json file.

**Comment by xd009642** [comment]
I've added this in via #1522 and it will be available in the next release!
