### ISSUE TITLE
Ability to measure code coverage of any binary

### ISSUE THREAD

**Issue by untitaker** [xd009642/tarpaulin#144]
My usecase is to run my program under tarpaulin, run some tests (from a Python process which should not be observed) against it, then kill my process and see how much of its code was used.

I had a quick look at tarpaulin's code and it doesn't seem like there's something fundamentally blocking it. I'll try to make a PR -- any input on the implementation would be apprechiated.

(ref getsentry/semaphore#76)

**Comment by xd009642** [comment]
It sounds doable, depends how the python controls the process. One option might be to look at what functions are publicly exported from tarpaulin and use tarpaulin as a library so you can write a simple test harness program.

If you want any advice or help just let me know and I'll see what I can do :smile:

**Comment by untitaker** [comment]
Thanks, I am almost there. Do you know of a way to forward SIGTERM to the process, but still record coverage? tarpaulin appears to handle sigterm and not generate any coverage.

**Comment by xd009642** [comment]
the `--forward` arg forwards some signals to the binary docs, not sure if it forwards SIGTERMs though

**Comment by untitaker** [comment]
@xd009642 I see that you have a bunch of special casing for various signals. I actually don't mind if it's SIGTERM that I have to send to tarpaulin, I just need some signal that would stop the child process, and make tarpaulin process coverage.

**Comment by untitaker** [comment]
FWIW @xd009642 I decided not to pursue this any further... I had a working implementation but ran into severe performance problems when running under coverage. Feel free to close this issue.

**Comment by xd009642** [comment]
The performance issues do make sense due to how tarpaulins update loop functions, shame it wasn't usable. Closing the issue now.
