### ISSUE TITLE
Publish lock file

### ISSUE THREAD

**Issue by breeswish** [xd009642/tarpaulin#147]
When using `cargo install` to install a specified tarpaulin version, if lock file is not present, cargo will not use dependency versions exactly specified in Cargo.toml. So installing the same tarpaulin version may not work after some time.

See also:

- https://doc.rust-lang.org/cargo/reference/unstable.html#publish-lockfile
- https://github.com/rust-lang/cargo/issues/2263

**Comment by xd009642** [comment]
I wasn't aware this was an issue, I expected cargo publish to factor in the lock file if it was configured. I see from the referenced issue that this caused tarpaulin to fail to build but I couldn't see a link to a failed CI run. Don't suppose you could link me one so I can see what failed?

Part of me is loathe to force users to use nightly but I'll probably have to do it until this becomes stable in tarpaulin.

**Comment by breeswish** [comment]
@xd009642 Cargo by default won't publish lock file even if you have not explicitly ignored it. In my referenced issue, our CI has been broken for several days (here are some examples [1](https://circleci.com/gh/tikv/tikv/13806?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) [2](https://circleci.com/gh/tikv/tikv/13800?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). As you can see, although version specified in Cargo.toml is proc-macro2 0.4.6, because it is "^0.4.6" implicitly, actually Cargo will install proc-macro2 0.4.8 and 0.4.9 if lock file is not present. However proc-macro2 0.4.8 and 0.4.9 utilize some latest rustc features or changes, so it won't compile any more for the project's current rustc.

**Comment by xd009642** [comment]
So I've changed my `Cargo.tom` to publish the lock file and my `.travis.yml` to only run on nightly. But something's changed which is messing up tarpaulin builds on the latest nightly (#148) so it might be a while before I publish an update since I really need to fix that issue first.

I'll keep this issue open for now just so I can message you when the next version is out if you want me to let you know :+1:

**Comment by xd009642** [comment]
So I had to update my Cargo dependency to get this fully working with my tests. Once my travis run on the develop branch reports as good I'll merge into master and release a new version with a published lockfile!

**Comment by xd009642** [comment]
And it's published! Closing the issue
