### ISSUE TITLE
proc_macro_link fails on nightly

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#148]
Unfortunately, due to some changes coming in proc-macro2 https://github.com/alexcrichton/proc-macro2/issues/132 and issues with cargo lock files #147 tarpaulin is going to be moving to nightly only. I forgot I ignored errors in nightly so when I switched travis to be only nightly found that `proc_macro_link` now fails on nightly :cry: 

@yodaldevoid I know I always bug you with linker based issues but I did a git blame and saw you added the test and I have only a vague recollection of it. So if you don't mind helping out that would be appreciated :+1:

**Comment by xd009642** [comment]
I've gotten a bit deeper into it, it actually seems to be an issue caused by my Cargo dependency being out of date. I'm updating it now and seeing if that fixes it, if it doesn't and it is a linker issue I'll ping you again :+1:  

Ah thanks for refreshing my mind, I did twig today it was for testing crates that use proc-macro build I forgot about all the `--no-pie` faff though

**Comment by xd009642** [comment]
Just confirmed it was the cargo dependency being out of date given a cargo.toml change I did recently. No coverage results returned currently with the update but that's a different kettle of fish..

**Comment by xd009642** [comment]
Fixed this and it's now in develop!

**Comment by softprops** [comment]
What's the recommended ci path for installing on stable? I think I'm caught on this same error

**Comment by xd009642** [comment]
So syn made some changes that mean it won't compile on 1.29 stable with the features I use. So Rust 1.28 and tarpaulin 0.6.6. But because publishing the lockfiles is an unstable feature of cargo to prevent getting a newer version of proc-macro2 which breaks my source analysis you'd have to actually pull the git repo and build it yourself.

Or use one of the old docker images (speaking of which just realised I needed to update my dockerfile for 0.6.7 release)

**Comment by softprops** [comment]
Cool. I'll try pinning to 1.28 for now. Thanks @xd009642 !
