### ISSUE TITLE
Codecov support

### ISSUE THREAD

**Issue by sunjay** [xd009642/tarpaulin#15]
Hi!
I wrote the [definitive guide to Rust code coverage](http://sunjay.ca/2016/07/25/rust-code-coverage) and am also responsible for Rust support in Codecov (I added the [example repository](https://github.com/codecov/example-rust)). As someone who has personally gone through all the trouble of using 3rd party, non-Rust specific software to do code coverage, I am super excited for this project! This is exactly what I've been looking for/hoping for. As this matures, I'll be happy to add it to the guide and it's future versions. :)

In the meantime, do you think it would be possible to add codecov support to this tool? I personally prefer that to coveralls and I know a lot of other people use it too. 

See [my guide](http://sunjay.ca/2016/07/25/rust-code-coverage#codecov-integration) for more on this, but the way it works now is that kcov outputs an appropriate coverage xml file and then codecov uploads it using their bash script. I bet the codecov documentation would have something about what you need to do to upload the data. 

Some example output from a build (copied from [my guide](http://sunjay.ca/2016/07/25/rust-code-coverage#codecov-integration)):
```
==> Travis CI detected.
    project root: .
==> Running gcov disable via -X gcov
    -> Running gcov in .
==> Searching for coverage reports under:
    +  .
    -> Found 2 reports
==> Python coveragepy not found
==> Detecting git/mercurial file structure
==> Reading reports
    + ./target/cov/lion-d992d5a006a939c3/lion-d992d5a006a939c3/cobertura.xml bytes=63276
    + ./target/cov/lion-ffbc62e55890c961/lion-ffbc62e55890c961/cobertura.xml bytes=608
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=b6e5d84873cc5702080470f5a2546edd4da247ea&build=41.1&build_url=&tag=&slug=sunjay/lion&yaml=&service=travis&flags=&pr=false&job=143150794
    -> Pinging Codecov
    -> to S3 https://codecov.s3.amazonaws.com
    -> View reports at http://codecov.io/github/sunjay/lion/commit/b6e5d84873cc5702080470f5a2546edd4da247ea
Uploaded code coverage
```

This is after running:
```
bash <(curl -s https://codecov.io/bash)
```

Notice how it automatically finds `cobertura.xml`.

If codecov isn't viable for some reason, at least producing a similar coverage xml file as kcov would really help because then this would be suitable for every coverage service. 

Again, thanks for making this! I'm really excited that someone is working on it!

**Comment by xd009642** [comment]
Hi @sunjay, glad you're interested in tarpaulin! Codecov is on my list and cobertura is on my project trello following a reddit comment on my introducing tarpaulin blog post. I'm hoping to have something by the end of this week or next week and will let you know then :)

**Comment by xd009642** [comment]
Hi @sunjay it's been a while but cobertura reports and implemented and working. Tested on my keygraph-rs crate so I know it works. A few more features I want to get in before publishing the next version to cargo but it's ready if you want to install from git :smile:

**Comment by sunjay** [comment]
This is awesome! Thanks for all your work!
