### ISSUE TITLE
tracking issue for necessity of cargo +nightly tarpaulin

### ISSUE THREAD

**Issue by softprops** [xd009642/tarpaulin#150]
something that keeps popping up when I get pulls in my crates that use tarpaulin is the newish  dependency on +nightly. I'm now familiar with this as a work around I wanted to open an issue that can maybe use as a tracking issue to get notified when this is no longer necessary.

**Comment by djc** [comment]
Also it would be nice if the README was updated to correct the example Travis config.

**Comment by xd009642** [comment]
@djc done :+1:

**Comment by softprops** [comment]
Awesome thanks for being in top of this @xd009642 and thanks for your hard work on filling this gap in the rust ecosystem.

**Comment by djc** [comment]
@xd009642 much thanks! Could have saved me a few iterations when I tried to get it to work. 😁

**Comment by softprops** [comment]
https://blog.rust-lang.org/2018/10/25/Rust-1.30.0.html looks like 1.30 is out with more macro stabilizations. Does that move this gh issue forward?

**Comment by xd009642** [comment]
Doesn't seem to all the Span methods are still marked as unstable

**Comment by xd009642** [comment]
So brief update. I've still got `publish-lockfile` in the `Cargo.toml` necessitating nightly. However, with that commented out tarpaulin can now run and pass on stable. There's a change to the stable dockerfile courtesy of @AnderEnder so now you can get tarpaulin on stable via docker.

Proc-macro2 probably still has the issue where it only works with the version of rustc it was compiled with. This is what necessitated `publish-lockfile` but given the rate stable updates I don't see this having a big effect on stable users.

**Comment by softprops** [comment]
awesome Ill give this a shot

**Comment by xd009642** [comment]
So due to some changes in source analysis and some stablisations in procedural macros you no longer need nightly to run tarpaulin so I'm closing this issue :tada:
