### ISSUE TITLE
tarpaulin doesn't work with edition = "2018" in Cargo.toml

### ISSUE THREAD

**Issue by deifactor** [xd009642/tarpaulin#151]
This happens with any project with it present, even if it's just the empty `cargo init` project (which has `edition = "2018"` as of sometime recently.

```
hi@flare-burn /t/twentyeighteen> uname -a
Linux flare-burn 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
hi@flare-burn /t/twentyeighteen> rustc --version
rustc 1.31.0-nightly (2bd5993ca 2018-10-02)
hi@flare-burn /t/twentyeighteen> cargo tarpaulin -v
Error during run
```

**Comment by xd009642** [comment]
I guess tarpaulin needs to be moved to the latest edition to fix this, are editions nightly only currently? And if so do you know when they are expected to be stabilised?

**Comment by deifactor** [comment]
It's supported in beta and nightly, but not stable. According to [this page](https://rust-lang-nursery.github.io/edition-guide/editions/index.html) 2018 lands in stable on December 6, 2018.

**Comment by xd009642** [comment]
Great news all I had to do was call a cargo function to enable nightly features I'm just doing an update, pushing it to my CI. Once the tests are all proven to pass there I'll release a new patch that sorts this

**Comment by xd009642** [comment]
passes on CI, merged into master and travis is releasing it as we speak!

**Comment by deifactor** [comment]
Awesome, thanks!
