### ISSUE TITLE
New nightly compile error on proc_macro_def_site

### ISSUE THREAD

**Issue by softprops** [xd009642/tarpaulin#153]
Sorry to be the bearer of bad news again but it looks like I'm getting a errored Travis build on stable even with

`RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install --force cargo-tarpaulin`

It's becoming unfcomfortable have stable builds error on tarpaulin newish nightly dependency. I realize this is not tarpaulins fault but I typically have high expectations for stability on the stable channel builds. Is there anything that can be done to insulate tarpaulin from a nightly dependency on stable?

Below is the error I see in Travis.

```
error[E0658]: use of unstable library feature 'proc_macro_def_site' (see issue #54724)
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.4.19/src/unstable.rs:481:27
    |
481 |             Span::Nightly(proc_macro::Span::def_site())
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(proc_macro_def_site)] to the crate attributes to enable
error: aborting due to previous error
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `proc-macro2`.
```

**Comment by xd009642** [comment]
It is annoying I agree. Though procmacro will be stabilised for 1.30 so it should just be until then.

At least this change is relatively simple. I won't get onto my pc till after work but if you submit a PR (on the develop branch) I'll merge it in

**Comment by softprops** [comment]
Awesome. Thanks @xd009642

**Comment by xd009642** [comment]
This might actually be a case of proc-macro2 not keeping up with the compiler updates, adding the feature to the crate attributes doesn't change anything :confused: looking into a proc-macro2 PR now

**Comment by xd009642** [comment]
Submitted the proc-macro2 PR hopefully that'll be merged tonight and tarpaulin will be all good again tomorrow

**Comment by xd009642** [comment]
It's merged, once it's built latest develop will work again and once my CI passes I'll publish another version to crates.io
