### ISSUE TITLE
When using `--print-rust-flags` in combination with `release = true`, `[reports]` is interpreted as config

### ISSUE THREAD

**Issue by sivizius** [xd009642/tarpaulin#1555]
**Describe the bug**
When using `release = true` in one config and `release = false` (or omit it) in another, the `RUSTFLAGS` will be different and thus [`print_flags`](https://github.com/xd009642/tarpaulin/blob/d536d1801f1e2ae8b3d6ac6df799144fd94ea04c/src/main.rs#L57) will print two different lines for each config. However, at this point, `print_flags` is unaware that `[report]` is not actually a config but a special section and will print `INFO cargo_tarpaulin: RUSTFLAGS for configs ["report"]`.

**To Reproduce**

`tarpaulin.toml`:

```toml
[foo]
release = true

[report]
out = ["Stdout"]
```

**Fix**
`print_flags` should ignore the section `report`.

**Comment by xd009642** [comment]
nice catch, I've just opened a PR which fixes that so it'll be in the next release!
