### ISSUE TITLE
Nicer failure modes would be nice

### ISSUE THREAD

**Issue by CAD97** [xd009642/tarpaulin#157]
https://travis-ci.com/nafi-lang/rust-nafi/jobs/151598084

```
$ cargo +nightly tarpaulin --verbose --out Xml
Error during run


The command "cargo +nightly tarpaulin --verbose --out Xml" exited with 1.
```

I _suspect_ this is failing at

https://github.com/xd009642/tarpaulin/blob/e13823e9143591fb83a0fd08d8f76203ff3d85dd/src/lib.rs#L86-L87

due to using `edition="2018"`, but I am uncertain due to the very uninformative error message of "Something went wrong (1)".

**Comment by xd009642** [comment]
That's sorted on the develop branch already! It now prints out the cargo error message. 

You need the cargo-features = ["edition"] at the top of your Cargo.toml to sort it, if it's the editions based issue

**Comment by CAD97** [comment]
https://travis-ci.com/nafi-lang/rust-nafi/jobs/151640129

It was indeed a need to turn on the cargo feature. Surprisingly, the cargo-features warning isn't denied by `-D warnings`, so I'll leave it on for a bit and just live with the warnings. I'm closing the issue since the root issue (report manifest errors) is fixed locally.

The edition requiring feature opt-in will just have to wait for the version of cargo-as-a-crate to support editions without the feature flag.
