### ISSUE TITLE
tarpaulin vs kcov comparison

### ISSUE THREAD

**Issue by asomers** [xd009642/tarpaulin#158]
How do tarpaulin's capabilities compare to kcov's?  Does it have any practical advantages, now or in the future?  It would be nice if this information were in the README.  I would be willing to add FreeBSD support, but only if there were some compelling advantage over kcov.

**Comment by xd009642** [comment]
The main advantage is it's a lot easier to install and run - even with the current need for nightly and `RUSTFLAGS="--cfg procmacro2_semver_exempt"`. It also has easy report uploads for coveralls.io and codecov.io. 

Also other tools like kcov are designed for C and often flag up false negatives for some rust language features i.e. marking `#[derive(..)]` attributes as uncovered code. Tarpaulin also shows unused inline and templated functions as uncovered whereas as they don't generate code if they aren't used kcov doesn't mark them as coverable.

Generally, the aim is easier to install and use and by being designed specifically for rust provide more accurate statistics. Though there are still some misses in parts of coverage so some parts are better, other parts aren't 100% there yet.

**Comment by asomers** [comment]
Hm, it sounds like kcov is easier to install.  Sure, it's two steps (`sudo pkg install kcov && cargo install cargo-kcov`), but runs on stable rust and doesn't need `RUSTFLAGS`.  The accuracy problems are interesting.  I'd noticed kcov's problems with `#[derive(Debug)]`; I didn't know about the problem with unused generic functions.  Would this be appropriate to document in a Github wiki page?

**Comment by xd009642** [comment]
Should have said install + run. Though admittedly last time I used kcov was pre `cargo-kcov` so I had to run cargo test, get the list of test executables, run kcov on all of them and merge the results which I guess cargo-kcov handles for you.

I hadn't thought about a wiki page, I've just been using blog posts and the readme. Definitely worth considering though.

**Comment by xd009642** [comment]
There's a wiki page now which can be filled in with more details comparing the two (also since procmacro stabilisation there's been no need for the RUSTFLAGS). I'm just goin gto close this issue as it's rather old but if you have any other questions let me know
