### ISSUE TITLE
Travis CI coverage fails after rebuild

### ISSUE THREAD

**Issue by sphinxc0re** [xd009642/tarpaulin#159]
When tarpaulin is run on Travis the first time, it works as expected. However when travis loads the tarpaulin binary from cache, this error occurs on execution:

```shell
$ cargo tarpaulin --out Xml
/home/travis/.cargo/bin/cargo-tarpaulin: error while loading shared libraries: libproc_macro-96beb1d4c9789a6b.so: cannot open shared object file: No such file or directory
```

**Comment by xd009642** [comment]
That'll be because `libproc_macro` needs recompiling for each version of the compiler because of the unstable features. Unfortunately, there's no way around it until those features are stabilised.

**Comment by sphinxc0re** [comment]
So... I need to recompile every time?

**Comment by xd009642** [comment]
Yeah, or add another rust compiler instance for one specific nightly and run tarpaulin on that one only

**Comment by sphinxc0re** [comment]
Oh, I actually did that. BUt despite that, it didn't work

**Comment by sphinxc0re** [comment]
https://github.com/bakervm/melon/pull/41

This particular PR. Ignore the latest build. One of the previous builds has the error in it

**Comment by xd009642** [comment]
So rebuilding every time worked or not?

**Comment by sphinxc0re** [comment]
It worked, but it more than doubled the build time 😕

**Comment by xd009642** [comment]
Yeah it's a pain, but once proc macro is stabilised caching should work again and the nightly restriction should be lifted! I'll close this issue but if you're interested you can follow how this situation evolves via #150

**Comment by Cogitri** [comment]
Maybe the need for `-f` should be added to the travis example thingie in README.md

**Comment by xd009642** [comment]
Not a bad shout. I've just pushed an update to the develop branch so it will pop into the readme on my next release!

**Comment by Cogitri** [comment]
Great, thanks :)
