### ISSUE TITLE
Failure of tests run by tarpaulin doesn't cause CI failure

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#160]
See here:

https://travis-ci.org/djc/quinn/jobs/452733819#L845

This got us confused for a bit by reported massively reduced code coverage. Seems similar to #46, but our project already installs the latest cargo-tarpaulin from crates.io.

**Comment by xd009642** [comment]
Hi sorry I haven't gotten back to you sooner I've been away from home and unable to put any time in. I'm just jumping back into tarpaulin and I'll see what's going on :+1:

**Comment by djc** [comment]
No problem, I know how it goes! Thanks for any investigation you can do.

**Comment by xd009642** [comment]
So this is really weird I seemed to recreate it once out of about 10 times trying it. I also can't see a reason looking at the rust std code why it should fail :confused: 

Just tried it a few more times before sending this, couldn't get it to happen. Beginning to wonder if my one recreation was a user mistake

**Comment by xd009642** [comment]
Ok I've come up with a solution of sorts which will improve instances tarpaulin fails. I've switched to tarpaulins main returning a result as added in rust 1.26. It also now returns an error type. 

So if an error is returned it prints the enum value i.e. TestFail, TestCompileFailed etc and the return value is 1.

Hopefully the different way of returning an error code and the more descriptive exit will sort this and also improve general UX

**Comment by xd009642** [comment]
Do you want to try this out first or are you happy for me to close the issue?

**Comment by djc** [comment]
If you've found what could be the root cause and fixed something, I'm happy to accept that. If I catch it failing again, I'll open a new issue (or reopen this one).

Did you release your fix on crates.io?

**Comment by xd009642** [comment]
No it's just on the develop branch. I'm going to try to get a few more things done before another release but I'm hoping in the next week or so
