### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by szabgab** [xd009642/tarpaulin#1615]
In the open source project I am working on `cargo test` takes 4 minutes while `cargo tarpaulin --ignore-tests -o Html -o Lcov --timeout 240` takes 17 min. Using `--engine llvm` reduced that to 14 minutes and out of that 14 min the compilation takes 4.

It is still 2.5 times longer than running the tests alone. It would be nice if the speed could be further improved.

If you are interested this is the [first run with llvm](https://github.com/szabgab/meet-os.rs/actions/runs/10664005795)

**Comment by xd009642** [comment]
Closing as duplicate - there are existing issues for performance of the LLVM coverage and the ptrace engine is expected to be slow based on how process instrumentation based tracing works.
