### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by Cogitri** [xd009642/tarpaulin#163]
I've recently had to debug why tarpaulin would fail on Travis but not locally, which was a pain because all tarpaulin prints if it fails to run is `Error during run` which is... very not so helpful. I'd suggest using `env_logger` instead of plain `println`. If you want to I can take a look at it and open a PR for it later on.

**Comment by xd009642** [comment]
Error reporting is a bit improved from work undertaken for #160 but I'm open to any improvements to the user experience. My only concern is that some of the printouts of the test binaries I can't stop so the formatting may end up looking strange with `env_logger` printouts combined with the test binary printouts

**Comment by xd009642** [comment]
@Cogitri so I've decided moving to `env_logger` is the right call if you're still willing to do the PR? If not I can have a look at it

**Comment by Cogitri** [comment]
I already did some work, sorry for not updating this. I'll post something till this weekend :)

**Comment by xd009642** [comment]
Oh that's alright, I was half expecting to have to do it myself so that's good news :+1:
