### ISSUE TITLE
Adding an --include-files flag to execute only a specific set of tests (excludes all by default)

### ISSUE THREAD

**Issue by alt440** [xd009642/tarpaulin#1666]
Say we have a big Rust project with 300,000 lines of code through hundreds of files.

Running test code coverage through the entire project would take a while...

We want to run only a specific set of files related to the files' names to save some time. However, the `--exclude-files` flag does not allow us to do that: it supports the wildcard character (*), but it doesn't allow us to say 'exclude all but X and Y files'.

Also, it cannot be a source code configuration, because we would like the CI/CD pipeline to run all tests at once to determine the code coverage on the entire project.

Something like:
`cargo tarpaulin --include-files src/x/y.rs src/v/z.rs`

Would exclude all files by default, except the ones specified after the --include-files

**Comment by alt440** [comment]
#1667 Pull request ready

**Comment by xd009642** [comment]
Merged
