### ISSUE TITLE
Consider allowing exclusion of lines and lines ranges

### ISSUE THREAD

**Issue by malbarbo** [xd009642/tarpaulin#17]
See https://github.com/SimonKagstrom/kcov/issues/180

It would be great if lines where `unreacheable!` macro is called be automatically excluded.

**Comment by xd009642** [comment]
I agree this is a desirable feature so it's been added to my future feature list, I'll update you when there's any progress.

**Comment by xd009642** [comment]
Heads up this is now implemented in 641f2912f4375e20cadaca10f1b4a9f40ecf0335 I'm going to be adding a few more features to sort out line filtering etc. I'm still working on adding more filtering features but this will definitely make it to the next release!
