### ISSUE TITLE
Tarpaulin incorrectly detecting coverage of multi-project crates

### ISSUE THREAD

**Issue by Cogitri** [xd009642/tarpaulin#176]
Hello,

I have a project that contains both a lib and bin and as such as two test suites. It appears that tarpaulin doesn't detect coverage for the binary correctly: https://codecov.io/gh/Cogitri/tmplgen/tree/master/src/bin. I understand that tarpaulin doesn't detect the tests run by `assert_cmd`, but the tests from [line 77](https://codecov.io/gh/Cogitri/tmplgen/src/master/src/bin/tests/mod.rs#L77) on should be detected, shouldn't they?

**Comment by xd009642** [comment]
All tests that get run when you run `cargo test` should be detected and ran. Could you link the repository as well so I can clone it and try it out myself? I can't seem to find a link to it on codecov.

**Comment by Cogitri** [comment]
Ah, sure. The link to the repo is

https://github.com/Cogitri/tmplgen

**Comment by xd009642** [comment]
Hmm well this is odd, when I run it on my own machine I get 32/35 lines covered on the file in question just running `cargo tarpaulin` Just 3 of the`.success();` calls are missed and everything else is marked as covered. I'll look deeper into it but it might be a tricky one.

**Comment by Cogitri** [comment]
Hm, the output of it when I run it locally:

https://gist.github.com/97cf1367df4894626378d77c93b7796a

**Comment by xd009642** [comment]
hmm what OS and rust version are you using?

**Comment by Cogitri** [comment]
Void Linux (x86_64), rust stable (so 1.31.0). I compiled tarpaulin with the latest nightly though. Dunno what Travis CI (usually does coverage for me) runs

**Comment by xd009642** [comment]
I think travis is normally pretty good at keeping nightly up-to-date I don't think the cache effects it too much. Checking the travis log it was `rustc 1.32.0-nightly (4a45578bc 2018-12-07)` so pretty recent (2 days more recent than mine).

I'll update my nightly and check again

**Comment by Cogitri** [comment]
> I think travis is normally pretty good at keeping nightly up-to-date 

Yes, I think they run rustup update before build.

**Comment by xd009642** [comment]
@Cogitri I know it's been a while but is this still an issue?

**Comment by Cogitri** [comment]
Ah, no worries. Seems like it works now: https://codecov.io/gh/Cogitri/tmplgen/tree/eb8e52d45453a7a8d396a451ecae4d07521fa8f6/src
