### ISSUE TITLE
Updated tarpaulin docker image

### ISSUE THREAD

**Issue by Cogitri** [xd009642/tarpaulin#178]
Hello,

I'm currently switching my stuff from Travis CI to Drone CI and as such would like to use the [tarpaulin docker image](https://hub.docker.com/r/xd009642/tarpaulin/), but the latest build is some 2 months old. Could you update it, so it uses tarpaulin 0.6.10?

**Comment by xd009642** [comment]
Oh crikey the install instruction is wrong on the docker file! 

I'll update that now for develop branch and when your PR is merged I'll be releasing 0.6.11 (no pressure) so a new release image will be made then.

**Comment by Cogitri** [comment]
Alright, thanks for looking into it :)

**Comment by Cogitri** [comment]
Ah, one more thing, could you ping me once you've updated the docker file? I'll just use the develop one until 0.6.11 has been released then :)

**Comment by xd009642** [comment]
@Cogitri  It is done

**Comment by phillyfan1138** [comment]
Has anyone actually gotten tarpaulin to work in drone?  I keep getting operation not permitted errors:

https://cloud.drone.io/phillyfan1138/binomial_tree_rust/4/1/2

**Comment by Cogitri** [comment]
WFM, what's your drone.yml?

**Comment by Cogitri** [comment]
I think that's more on drone,

see https://cloud.drone.io/phillyfan1138/binomial_tree_rust/4/1/3 line 17. Tarpaulin generates the coverage data just fine in https://cloud.drone.io/phillyfan1138/binomial_tree_rust/4/1/2, but it seems that the upload-coverage plugin thingie expects GNU coreutils when in actually it has busybox. Please report this at drone upstream and not here :)

**Comment by Cogitri** [comment]
See https://github.com/Cogitri/tmplgen/pull/29/files#diff-3216dfff0ed3e301453e6799e8c367e2R77 for the privileged switch.

**Comment by phillyfan1138** [comment]
Thanks that helps!
