### ISSUE TITLE
Please add cargo-features rename-dependencies

### ISSUE THREAD

**Issue by Cogitri** [xd009642/tarpaulin#179]
```
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/home/rasmus/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.10/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

**Comment by xd009642** [comment]
Have you tried adding `cargo-features = ["rename-dependency"]` to your `Cargo.toml`? I remember that being needed for editions before they were stable

**Comment by Cogitri** [comment]
Yes, but that would case my app to only be build-able with Rust nightly, which I'd prefer to avoid just for this when it can be fixed by adding this to tarpaulin which needs nightly anyway.

**Comment by xd009642** [comment]
Good point, I'll look into this again and try to find a solution

**Comment by Cogitri** [comment]
Thanks, I'll pin rustc-demangle to 0.1.9 for now then :)

**Comment by thedavidmeister** [comment]
fwiw i stopped seeing these errors in `0.6.11` but started seeing other issues (#190 )
