### ISSUE TITLE
Exclude Debug

### ISSUE THREAD

**Issue by newpavlov** [xd009642/tarpaulin#18]
In my code the main source of "uncovered" code is `#[derive(Debug)]` on structs. I don't think it makes much sense to test it, so I think it's worth to remove related lines from the coverage report.

**Comment by xd009642** [comment]
So this issue is related to #16, instructions that map to source lines that aren't covered. Currently working out a solution that solves all instances of this more gracefully than accruing a list of regular expressions. I'll let you know when there's an update :+1:

**Comment by newpavlov** [comment]
Great! Thank you!

**Comment by xd009642** [comment]
Hi @newpavlov just an update, I've implemented this in 7aa369ae6e40c28462f6b06a2fbc61c130cc7c07 `#[derive(..)]` is now ignored in coverage as well as struct members which also don't make sense to cover!

I'll be adding more rules to filter out similar issues (#16 and #17) and it'll be in the next update. Sorry it's taken so long!
