### ISSUE TITLE
Release/debug_assertions for tests

### ISSUE THREAD

**Issue by daxpedda** [xd009642/tarpaulin#181]
**Comparison between kcov and tarpaulin**
tarpaulin: [link](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/b94637633c8c4bd5246375102b06e0b48c29e893/src/lib.rs#L47...78)
kcov: [link](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/c4f7173099c2ec2b882229b9209dd791e80436f2/src/lib.rs#L47...78)

**Problem**
Tarpaulin is right about the uncovered lines because this code only runs in release mode.
I made two test files, one that is supposed to be run in debug and one in release, but tarpaulin doesn't support building tests with `--release`.

**Solution**
- Implement a flag that builds in release mode but retains debug info.
- Implement a flag that disables `debug_assertions`.

**Notes**
- I'm actually not sure if the test results can be combined in a useful way.
- I tried to write a patch for it but didn't succeed (https://github.com/daxpedda/tarpaulin):
  - I tried doing this: `copt.build_config.release = config.release`, which does enable release mode but doesn't disable `debug_assertions`.
  - I also couldn't figure out how to enable debug info at the same time.
  - Woud love to help out and make a PR for it, but I really need some pointers for the Cargo API.

**Comment by xd009642** [comment]
It looks like profiles are automatically loaded from the Cargo.toml and added to the workspace and you can set `debug_assertions` and whether debug info is included [docs.rs link](https://docs.rs/cargo/0.32.0/cargo/core/profiles/struct.Profile.html). 

I'm wondering if the solution is a mix of an extra cargo flag and also something added to the cargo.toml under `[profile.test]`. Try the test profile and a release flag to see what happens. I looked but can't find a way in the docs or cargo source to change the profiles via the API. 

```
[profile.test]
debug = 2
debug-assertions = false
```

The fact that `#[cfg(feature = "debug_checks")]` appears as a missing line is concerning to me. Tarpaulin should filter all of them out. But I'll look into that myself.

Also, I noticed looking at your tarpaulin fork you were working on the master branch. I only use that for releases and any pressing README updates - actual work is done on the develop branch or feature branches coming off develop. So if you do submit a PR if you could change to work on develop or a feature branch that would be appreciated :+1:

**Comment by daxpedda** [comment]
> Try the test profile and a release flag to see what happens.

I get very weird behaviour with what you posted:
> ```
> [profile.test]
> debug = 2
> debug-assertions = false
> ```

Trying that it executed the right tests: [link](https://travis-ci.org/daxpedda/unchecked_unwrap/jobs/470276270#L575-L591)
```
Launching test
running /home/travis/build/daxpedda/unchecked_unwrap/target/debug/deps/debug-aa6c8c8b28e96e8e
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Launching test
running /home/travis/build/daxpedda/unchecked_unwrap/target/debug/deps/release-fe1c5731f89cb108
running 4 tests
....
test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
Coverage Results
Tested/Total Lines:
src/lib.rs: 8/35
```
It passed `#![cfg(not(debug_assertions))]` inside of the test file, but for some reason, it still only executed the debug code from `lib.rs`.
I even tested it with this here: [link](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/d59798f9ed707c643d2818bcc9d09c8526dbdcf1/src/lib.rs#L136...146)
```rust
    unsafe fn unchecked_expect(self, msg: &str) -> T {
        if cfg!(debug_assertions) {
            #[cfg(feature = "debug_checks")]
            return self.expect(msg);
        }
        panic!("asd");
        if let Ok(x) = self {
            x
        } else {
            core::hint::unreachable_unchecked()
        }
```
This should have panicked in the test execution, but it didn't.
I'm not sure if tarpaulin actually runs the tests, but the code coverage still shows that only the debugging part was executed.
Hope that helped.
> I looked but can't find a way in the docs or cargo source to change the profiles via the API.

Same, just can't figure out a way. I asked in Discord too, let's see if I get an answer.

> So if you do submit a PR if you could change to work on develop or a feature branch that would be appreciated

No problemo.

**Comment by xd009642** [comment]
Hmmm, I wonder if that means it doesn't use the test profile but another one.. If you pull upstream changes on develop I did make it so the attributes on the return statements aren't incorrectly included in the results (need to add so that's true for attributes on all statements still).

**Comment by daxpedda** [comment]
[Codecov link](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/0591788df36356d901c7b6afcf876f54c5984beb/src/lib.rs#L48)
There is still `if cfg!(debug_assertions)` which seems to be marked as untested.
I was still searching in the Cargo API to figure out a way to switch to release mode with no avail.
