### ISSUE TITLE
`cfg!` macro and `#[cfg(..)]` attributes are marked as uncovered.

### ISSUE THREAD

**Issue by daxpedda** [xd009642/tarpaulin#184]
Sample report: [codecov link](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/c0bf72b18ca7bf27ce687bf7401b9a2e3a7b7958/src/lib.rs#L79...86)

Lines like `if cfg!(debug_assertions)` or `#[cfg(feature = "example_feature")]` are marked as untested.
Not sure if the solution is to test better for them or to just remove them completly.

**Comment by daxpedda** [comment]
I found some other issue that may be related to this:
[Covered](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/08205ac16a61e8a0d27dd635b60f6f197d3e738e/src/lib.rs#L50) vs [Uncovered](https://codecov.io/gh/daxpedda/unchecked_unwrap/src/c0bf72b18ca7bf27ce687bf7401b9a2e3a7b7958/src/lib.rs#L113) `self.unwrap()`.

Not sure why it changed, but the only thing I changed is `if { .. } if { .. } else { .. }` to  `if { .. } else if { .. } else { .. }`. Also in one of them `#[cfg(feature = "debug_checks")]` is covered and in the other it is not, thats why I though there may be a relation.
Or maybe `#[allow(clippy::result_unwrap_used)]` is affecting it?

I will do further testing on my own when I find time.

**Comment by xd009642** [comment]
I've added stuff to ignore `cfg!` as it's compile time so doesn't generate any traceable run-time code as well as refining my attribute coverage handling.

I'm not currently sure about the uncovered `self.unwrap()`. I'm also going to add some debug logging to help with debugging source analysis issues.

**Comment by xd009642** [comment]
And I've cracked the covered unwrap, it was down to the attributes making me get the start of the actual method call code wrong.

**Comment by daxpedda** [comment]
Okay, was just about to try and figure it out myself, thanks!

**Comment by daxpedda** [comment]
I played around with it a bit today, couldn't find any issues so far. Close?

**Comment by xd009642** [comment]
Sure thing :+1:
