### ISSUE TITLE
Fails to build report

### ISSUE THREAD

**Issue by Gerschtli** [xd009642/tarpaulin#186]
Hello,

`cargo tarpaulin --out Xml` fails to generate the coverage reports:

```
Building project
error: internal compiler error: src/librustc/traits/codegen/mod.rs:68: Encountered error `Unimplemented` selecting `Binder(<animation::PixbufSimpleAnim as glib::translate::ToGlibPtr<*mut <animation::PixbufAnimation as glib::wrapper::Wrapper>::GlibType>>)` during codegen
thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.33.0-nightly (14b96659e 2018-12-25) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 -C relocation-model=dynamic-no-pic -C link-dead-code -C opt-level=0 --crate-type lib
note: some of the compiler flags provided by cargo are hidden
Tarpaulin finished
Error: TestCompileFailed
```

For the complete travis build, see https://travis-ci.org/Gerschtli/dwm-status/jobs/472219925

Thank you!

**Comment by xd009642** [comment]
So that's an error in the rust compiler not tarpaulin. Have you opened an issue on the compiler like the error suggested?

I have heard there was a regression introduced in yesterday's nightly app it might be that. Or if you're using proptest currently there's a compiler issue with proptest and tarpaulin

**Comment by Gerschtli** [comment]
I did not yet, will build it one more time with full backtrace and then open a ticket, if not already done.

Yeah, there was a problem with yesterdays nightly which resulted in many failed builds, but now the builds are passing so I thought it has to be another problem.

**Comment by Gerschtli** [comment]
Is fixed by now, see https://github.com/rust-lang/rust/issues/58375
