### ISSUE TITLE
build error due to version update

### ISSUE THREAD

**Issue by sallyyu0** [xd009642/tarpaulin#189]
I'm getting following error during due to rustup version update. Could you update to latest and give a new release? Thank you in advance!

# cargo build
   Compiling ring v0.13.5
   Compiling serde_derive v1.0.83
   Compiling failure_derive v0.1.3
   Compiling tokio-fs v0.1.4
   Compiling parking_lot v0.7.0
   Compiling redis v0.9.1
error[E0658]: `crate` in paths is experimental (see issue #45477)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.5/src/bssl.rs:15:5
   |
15 | use crate::{c, error};
   |     ^^^^^

error[E0658]: the `#[repr(transparent)]` attribute is experimental (see issue #43036)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.13.5/src/bssl.rs:22:1
   |
22 | #[repr(transparent)]
   | ^^^^^^^^^^^^^^^^^^^^

**Comment by xd009642** [comment]
I'm just pushing out a new release with the Cargo version updated that may solve this. It's the current develop version because I haven't done a release as soon as I was expecting due to waiting on some other features. Let me know if this doesn't solve the issue and I'll look more into it!

**Comment by sallyyu0** [comment]
It fixed. Thanks a lot!
