### ISSUE TITLE
0.7:latest Docker build fails

### ISSUE THREAD

**Issue by Cogitri** [xd009642/tarpaulin#200]
Thanks for the recent development! Seems like the docker image of latest fails though, see https://hub.docker.com/r/xd009642/tarpaulin/builds

**Comment by xd009642** [comment]
I honestly have zero clue why this failed the log ends with:

```
---> 30520f40ee49
Successfully built 30520f40ee49
Successfully tagged xd009642/tarpaulin:latest
Pushing index.docker.io/xd009642/tarpaulin:latest...
Done!
Build finished
```

In truth I've never managed to get docker properly working... @robinst  @AnderEnder both you have done docker based PRs. Could either of you have a look and see if anything is overtly wrong?

In the meantime I've retriggered the build just in case it was some docker hub issue like a temporary outage.

**Comment by AnderEnder** [comment]
@xd009642 Looks like it was a Docker Hub infrastructure issue.

**Comment by xd009642** [comment]
Sweet, just saw it succeeded on retry. :tada:

**Comment by Cogitri** [comment]
Ah nice. Thanks for looking into it
