### ISSUE TITLE
feat: outreach: Tarpaulin badge

### ISSUE THREAD

**Issue by sesam** [xd009642/tarpaulin#202]
Define some initial tarpaulin badge and get it included here https://shields.io/#/examples/coverage
That would improve outreach.

**Comment by xd009642** [comment]
I'm not sure how relevant a tarpaulin branch would be there, those seem to mostly be services like codecov and coveralls or ci-servers that can return the results of a coverage tool to a client.

**Comment by sesam** [comment]
Ok with me. I wasn't well versed in shields.io when opening this issue. Outreach can be done in various ways. Maybe better track outreach efforts separately - leaving that up to you and others for now and closing this.
