### ISSUE TITLE
bug: broken link [outreach]

### ISSUE THREAD

**Issue by sesam** [xd009642/tarpaulin#203]
The link submitted here https://www.reddit.com/r/rust/comments/6ohd9y/introducing_tarpaulin_a_code_coverage_tool_for/ is broken due to spelling fixes. Since the github repo containing your github pages appears to be private, I made the error report here.

Suggestion: either add a redirect if github pages supports that, or add a specific "Welcome, redditor!"  page that gives a few sentences about what's new/awesome with tarpaulin compared to how it was in July 2017 when that reddit discussion thread happened.

**Comment by xd009642** [comment]
Oh yeah I realised that would happen when I fixed the typo. I was kind of hoping that it being so long ago people wouldn't find it via the reddit link. I'll look into if a redirect is possible.

I don't think the github pages repo is private? You should be able to find it here https://github.com/xd009642/xd009642.github.io

**Comment by xd009642** [comment]
I've just popped the old one back there with the typo, I can live with there being two instances of the same post
