### ISSUE TITLE
Can you add credential options to the docker image?

### ISSUE THREAD

**Issue by abbychau** [xd009642/tarpaulin#208]
```
Caused by:
  failed to clone into: /usr/local/cargo/git/db/protobuf_definitions-ca489d32c7290e5c

Caused by:
  failed to authenticate when downloading repository
attempted to find username/password via git's `credential.helper` support, but failed

Caused by:
  failed to acquire username/password from local configuration
```
It will be useful on private repos

**Comment by xd009642** [comment]
I could do if I knew how. Are you sure this is a tarpaulin issue? Googling it looks similar to this https://github.com/rust-lang/cargo/issues/3487 which is an issue with cargo unable to download private repos and complaining about git credentials.

**Comment by abbychau** [comment]
actually cargo can do it normally with installed credentials in the OS.
It is not a bug for either cargo or tarpaulin but it cannot be done without modifying the docker image. 
So if with added perimeters to the image we don't have to wrap the tarpaulin's docker image and pass all parameters.

If you want it to be minimal, I may just wrap tarpaulin with build-arg to pass arguments in this case then.

**Comment by xd009642** [comment]
No that's fine I was just unsure of what to do. If you could send some documentation on what I'm doing I'll make the modifications

**Comment by xd009642** [comment]
@abbychau I'm still not 100% sure what I'd have to do to fix this issue, I tend not to use docker so am a docker novice. If you can link any examples it would be helpful

**Comment by abbychau** [comment]
Sorry I rethought it again and it seems it makes more sense to keep this image minimal :D 
because it is docker's philosophy :)
