### ISSUE TITLE
cobertura output doesn't appear to be compatible with azure pipelines

### ISSUE THREAD

**Issue by dgriffen** [xd009642/tarpaulin#209]
The cobertura Xml output doesn't appear to be compatible with azure pipelines cobertura engine. You can see a build example here: https://dev.azure.com/dgriffen/nestor/_build/results?buildId=42. The linux job is unable to load the coverage xml. Looking at this bug in azure seems to indicate that there may be some fields it expects that tarpaulin does not set. https://github.com/Microsoft/azure-pipelines-tasks/issues/2186

**Comment by xd009642** [comment]
Okay it looks like it expects the `lines-valid` and `lines-covered` attributes. I'll try to add them in at some point hopefully this weekend. 

I am questioning the need of cobertura to have `lines-valid`, `lines-covered` and `line-rate` as `line-rate` is just `lines-covered/lines-valid`. In reality having optional attributes to show the same thing in different ways just makes it harder for people to generate cobertura reports that everything plays nicely with.

**Comment by xd009642** [comment]
Okay I might have fixed it, if you can try the version on this branch https://github.com/xd009642/tarpaulin/tree/issue-209 and let me know if it works that would be grand :+1:

**Comment by xd009642** [comment]
Awesome, I'll merge it into the develop branch. Not sure how long it'll be till my next release as I'd like to close a couple more issues but until then you'll be able to install from develop or the develop docker image
