### ISSUE TITLE
Test coveralls with other CI services.

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#213]
This stems from https://github.com/xd009642/coveralls-api/issues/1 currently the code is implemented but I ideally need people using these ci tools to try it out and see if it works better with coveralls.

Listed CI services are:

* [x] Travis
* [x] TravisPro
* [x] Circle
* [ ] Semaphore
* [x] Jenkins
* [ ] Codeship
* [x] gitlab CI
* [x] github actions

**Comment by Mossop** [comment]
FWIW I've managed to use this to upload to coveralls from Azure pipelines (https://github.com/FractalBrew/file-store-rs/blob/master/azure-pipelines.yml#L61)

**Comment by jonhoo** [comment]
The biggest issue with this is that the codecov token needs to be made available to pull requests, but that's an issue with Azure, not with tarpaulin. See also the re-useable Azure Pipelines component here https://github.com/crate-ci/azure-pipelines/blob/master/azure/coverage.yml and the coverage over at https://crate-ci.github.io/azure-pipelines/setup.html#code-coverage.

**Comment by xd009642** [comment]
Oooh I'll put a link to the azure repo you linked in the readme @jonhoo :+1:

**Comment by mathstuf** [comment]
I have Tarpaulin running under GitLab-CI here: <https://gitlab.kitware.com/ben.boeckel/rust-git-workarea/-/jobs/4684893>. [Here's the diff](https://gitlab.kitware.com/ben.boeckel/rust-git-workarea/commit/e895c2e2b9f6c1bb7992c74c426b2bcc416aff28) to add support. Haven't done the work to get it to show up anywhere else yet.

**Comment by xd009642** [comment]
I've got gitlab mentioned in the readme now though that might be just how to get gitlab coverage working I found getting tarpaulin working on it was as easy as Travis

**Comment by samueldple** [comment]
I have it working on GitHub Actions in samueldple/date_time if that's of interest to anyone using [this workflow](https://github.com/samueldple/date_time/blob/master/.github/workflows/coverage.yml)

**Comment by xd009642** [comment]
See personally I'd think of that as pretty self-explanatory no weird things or things to trip you up. Compared to for instance running tarpaulin from docker or the fact that travis needs you to set `sudo: required`. But I am starting to wonder if this project could benefit from a folder with a collection of bare bones config files for various CI services that people could refer to as a starting point.

But then it's work to maintain them and I only use travis or github actions personally so I won't spot any updates that are required so it relies on people having the examples not work anyway...

Anyone have any thoughts?

**Comment by mathstuf** [comment]
Maybe just pointing to example repos is good enough? I suggest only taking volunteers rather than seeking out examples (that way if they change CI backend, there's a chance there'd be a signal back here to update links).

**Comment by xd009642** [comment]
confirmed circle can work via docker by talking to a tarpaulin user

**Comment by xd009642** [comment]
Closing because it's been 3 years with no issues reported on other CI platforms
