### ISSUE TITLE
Ungraceful exit in case of failed (unimplemented!) tests

### ISSUE THREAD

**Issue by eddyp** [xd009642/tarpaulin#214]
I have a stupid ignored and unimplemented! case, but it seems tarpaulin fails to gracefully handle the failed test:

```
eddy@feodora:~/usr/src/rust/c_unit_test_parser$ cargo tarpaulin -v --ignored
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s                                                                                                                                                                                                  
[DEBUG tarpaulin] Processing c_unit_test_parser
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eddy/usr/src/rust/c_unit_test_parser/target/debug/deps/c_unit_test_parser-4b06c55333827aa1

running 6 tests
test eunit_tests::check_empty_suite ... ok
test eunit_tests::check_fail_testcase ... ok
test eunit_tests::check_non_empty_suite ... ignored
test eunit_tests::check_pass_testcase ... ok
test eunit_tests::check_skip_testcase ... ok
test test_get_cases_from_string ... ok

test result: ok. 5 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/eddy/usr/src/rust/c_unit_test_parser/target/debug/deps/c_unit_test_parser-4b06c55333827aa1

running 1 test
test eunit_tests::check_non_empty_suite ... FAILED

failures:

---- eunit_tests::check_non_empty_suite stdout ----
thread 'eunit_tests::check_non_empty_suite' panicked at 'not yet implemented: Need to see exactly the declarations of EUnit', src/main.rs:157:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:353
   7: c_unit_test_parser::eunit_tests::check_non_empty_suite
             at src/main.rs:157
   8: c_unit_test_parser::eunit_tests::check_non_empty_suite::{{closure}}
             at src/main.rs:156
   9: core::ops::function::FnOnce::call_once
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:238
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1471
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/ops/function.rs:238
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
  11: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102


failures:
    eunit_tests::check_non_empty_suite

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 5 filtered out

[ERROR tarpaulin] Failed to get test coverage! Error: Failed to get test coverage! Error: Test binary exited with non-zero return code
```

**Comment by xd009642** [comment]
So `--ignored` runs your tests with the `#[ignore]` attribute and without, here it's done the run of the tests not including the ignored test and then gone for a second go at just the ignored tests. The test panicking when it hits the `unimplemented!` means that tarpaulin thinks the test has crashed and aborted the run because the results are in-theory incomplete/wrong.

 The easiest way to solve this is to remove the `--ignored` flag, if the test isn't implemented you probably don't want to run it anyway. I think the should panic attribute on the test may help? But I can't recall testing tarpaulin with it.

**Comment by xd009642** [comment]
I can of course change tarpaulin to report results even if they're potentially bad. But for people who send results to a coverage service it might mess up their metrics if faulty reports are uploaded and cause them some CI/PR based grief

**Comment by eddyp** [comment]
@xd009642 I am a little confused, since tests are implemented with assert macros which panic out the assertion fails, wouldn't that mean in case of any failed test tarpaulin would fail the same way as in the unimplemented! case?

**Comment by xd009642** [comment]
Yeah it would, I could change it so it reports the values despite test failure I think that might have been the behaviour before. But that raises the question of what's the worth of coverage data for tests that fail because either the code will have to change or the tests will? I'll go back at some point and add a flag so you can still get the results if it fails and make a decision on the default behaviour.

Also, I don't think tarpaulin fails to gracefully handle the exit case, as you have the verbose flag set it prints out the rustc-test stack trace to help you diagnose the test failure. The only bit I don't like is the silly nested error messages `[ERROR tarpaulin] Failed to get test coverage! Error: Failed to get test coverage! Error: Test binary exited with non-zero return code`

**Comment by eddyp** [comment]
> But that raises the question of what's the worth of coverage data for tests that fail because either the code will have to change or the tests will?

Yes, I agree, but since a panic is the expected way for any failure case and regular treating doesn't crash, it just "eats" the panic traces, I think tarpaulin should do similarly by default and warm with some message like "X test cases failed, coverage information its probably inaccurate". If that info includes the code covered by the failed test, it's up to you to decide, but some option to list the coverage in the other case (e.g. if by default it lists just passed, the non default would list passed and failed tests' coverage).

At least that's my thinking

**Comment by xd009642** [comment]
Yeah I agree, I've now changed tarpaulin and merged the change into master. Here's some new example output:

```
cargo run -- tarpaulin -r ../metatarp/failing_test/
   Compiling cargo-tarpaulin v0.7.0 (/home/xd009642/code/rust/tarpaulin)
    Finished dev [unoptimized + debuginfo] target(s) in 8.38s
     Running `target/debug/cargo-tarpaulin tarpaulin -r ../metatarp/failing_test/`
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/xd009642/code/rust/metatarp/failing_test/target/debug/deps/failing_test-54078d9bae45e4b6

running 1 test
F
failures:

---- tests::it_works stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `6`,
 right: `4`', src/lib.rs:5:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::it_works

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/lib.rs: 2/2
|| 
100.00% coverage, 2/2 lines covered
[ERROR tarpaulin] Test failed during run
```

This should only affect failing tests so if there are other run-time issues that suggest that something is wrong internally or the coverage results are fundamentally wrong tarpaulin still won't give any results. But tbh any instances in the past like that the results were normally 0% anyway :+1:
