### ISSUE TITLE
Not all doctests show up crate source files in the debug line info.

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#215]
This may be a side effect of macro usage or down to the auto-generated source files created for the doc-tests but for [serde_with](https://github.com/jonasbb/serde_with) none of the DWARF debug line information mentions files in the crate source. There are however some source files that aren't rust source files i.e. `./<::core::macros::try_macros>:[++]` which is also a relative not absolute path.

The next question is, how to trace coverage when the DWARF information doesn't provide any instrumentable points?

Original discussion was on #13

**Comment by jonasbb** [comment]
I tested if this issue still applies with the new tarpaulin 0.9 release.
I used Rust in version `rustc 1.40.0-nightly (032a53a06 2019-10-03)` with `serde_with` git tag 1.3.1.

Overall I now do get line coverage results:

```
$ cargo +nightly tarpaulin --run-types Doctests --out Html --all-features
...
[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/chrono.rs: 31/64
|| src/duplicate_key_impls/error_on_duplicate.rs: 10/20
|| src/duplicate_key_impls/first_value_wins.rs: 8/26
|| src/flatten_maybe.rs: 12/14
|| src/json.rs: 16/18
|| src/lib.rs: 3/7
|| src/rust.rs: 134/172
|| src/with_prefix.rs: 27/143
|| 
51.94% coverage, 241/464 lines covered
```

The reported line coverage results for the doc tests have the wrong offset. In this case, for the `json.rs` file, the green lines are too early. It seems that the coverage line numbers are offset to the start of the file, but they should be relative to the markdown code block.
![Screenshot_2019-10-04 Screenshot(1)](https://user-images.githubusercontent.com/273459/66204010-17d25580-e6aa-11e9-92ac-130d1f34516e.png)

**Comment by xd009642** [comment]
Just because it occurred to me now, what tarpaulin should do if doc tests are being ran is parse doc comments for inline code that should be ran, create an offset and also run the source analysis module on the doc comment code. I'm seeing some lines there that would be ignored normally like the derive attributes etc

**Comment by xd009642** [comment]
@jonhoo here's the other doctest issue

**Comment by kellpossible** [comment]
I'm not sure if this is related, but I only get doctests results showing up after running cargo-tarpaulin twice

**Comment by xd009642** [comment]
@jonasbb just revisiting doctest issues. Is serde_with a proc macro crate or is there actual runtime code executed? Just making sure

**Comment by jonasbb** [comment]
@xd009642 There are two crates in the repo. `serde_with_macros` is the proc macro crate. It exposes a single proc macro. Then there is the `serde_with` crate, which re-exports the proc macro. In addition, it contains a bunch of other public functions, most of which are fully generic. Since the functions are generic there is probably not much code in the crate, unless they get used, e.g., for the tests.

**Comment by xd009642** [comment]
So there's a chance then that the doctests may not use any runtime code? If so that would explain not finding any crate sources

**Comment by jonasbb** [comment]
No, the doctest run the actual code so they need to instantiate all the generics with concrete types. I just wanted to point out that the code generation will happen in the compilation unit of the test instead of the serde_with crate.

**Comment by xd009642** [comment]
that should be fine, from my experience rust still ties the debug information to the source lines for generics. Also, looking at doc tests they seem to put the debug info into the relevant lines in the doc comments as well (though I'm less sure on this just going off some coverage reports I've seen)

**Comment by xd009642** [comment]
I'll have another look at serde_with as part of #455

**Comment by xd009642** [comment]
So I had a run of it again and got these results from `--run-types Doctests`

```
|| Tested/Total Lines:
|| src/chrono.rs: 0/51
|| src/duplicate_key_impls/error_on_duplicate.rs: 12/20
|| src/duplicate_key_impls/first_value_wins.rs: 9/26
|| src/flatten_maybe.rs: 7/7
|| src/json.rs: 0/3
|| src/lib.rs: 3/6
|| src/rust.rs: 116/161
|| src/with_prefix.rs: 13/128
|| 
39.80% coverage, 160/402 lines covered
```

I'm going to close this as it's a bit old and it looks like this is no longer an issue. If anyone observes this again comment on the overarching doctest issue #455 :smile:
