### ISSUE TITLE
Unexpected SIGILL with tmplgen

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#217]
@Cogitri FYI

This is the end of the debug log:

```
[TRACE tarpaulin] Child exiting
[TRACE tarpaulin] Result queue is [Exited(Pid(31227), 0)]
[TRACE tarpaulin] Exited Pid(31227) parent Pid(31151)
[TRACE tarpaulin] Result queue is [Stopped(Pid(31151), SIGILL)]
[TRACE tarpaulin] No action suggested to continue tracee. Attempting a continue
[ERROR tarpaulin] Failed to get test coverage! Error: Failed to run tests: Error running test - SIGILL raised in 31151
```

So a child exits, then the parent experiences a SIGILL

**Comment by Cogitri** [comment]
Alright, I don't exactly know something about the magic tarpaulin does to do this, but is there something I can help with? :)

**Comment by xd009642** [comment]
Hmm I think it's a case of looking at the disassembly of the test binary, seeing what's at the addresses tarpaulin is instrumenting and then working through and seeing where it's going wrong. It's fiddly and low level and because of ptrace I'm not actually sure if you can guarantee it will work when debugging via GDB either :cry:.

If you want to have a look the update loop logic is pretty much all in `src/statemachine/linux.rs`

**Comment by xd009642** [comment]
This should be fixed with the latest release if you could confirm I'll close this :+1:

**Comment by Cogitri** [comment]
Done, thanks :)
