### ISSUE TITLE
Example of missed coverage

### ISSUE THREAD

**Issue by DevJac** [xd009642/tarpaulin#218]
Here is a short example where tarpaulin misses coverage of a line that should be considered covered:
```rust
use std::ops;

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Vec3(pub f64, pub f64, pub f64);

impl Vec3 {
    pub fn dot(self, rhs: Self) -> f64 {
        (self.0 * rhs.0) + (self.1 * rhs.1) + (self.2 * rhs.2)  // This line will show as uncovered.
    }
}

#[test]
fn test_dot() {
    assert_eq!(Vec3(1.0, 2.0, 3.0).dot(Vec3(1.0, 3.3, 0.0)), 7.6);
}
```
A comment indicates which line is missing coverage.

I understand there are some known cases where coverage is missed, but I thought this might possibly demonstrate a new case.

**Comment by DevJac** [comment]
Because of other recent enhancements and bugfixes, I wondered if this was still a problem. I confirmed this is still happening with tarpaulin 0.9.0 and Rust 1.38.

**Comment by Ploppz** [comment]
I wonder if my issue is also an example of this? Or something else?
It's about what I would call contradictory line coverage information:

![ss](https://i.imgur.com/psfsuGM.png)

What does it mean that `.join(..)` is not covered, when the statement of which it is a part is considered covered?

**Comment by Ploppz** [comment]
nvm it looks more like #270

**Comment by xd009642** [comment]
There's some improvements in coverage in the latest develop that solved some longstanding issues. 

So I'm going to close this issue. But if you try again with that and if it's still an issue report it to my new missing/incorrect coverage issue https://github.com/xd009642/tarpaulin/issues/351 . This helps keep all the different missing coverage problems in one place. And hopefully makes it easier for me to work on
