### ISSUE TITLE
tarpaulin should use a non-zero exit code if the compiler fails

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#219]
I just noticed I have a compiler failure similar to #186 (see for example https://travis-ci.org/djc/quinn/jobs/515066241). However, the Travis job is represented as passed, which has made it much harder for me to notice that code coverage runs were broken -- I only noticed two months after it started. It seems like the cargo tarpaulin command should return a non-zero exit code in this case so that the Travis job would end up failing.

**Comment by xd009642** [comment]
So be because you put it in the `after_success` section of your `.travis.yml`, returning a non-zero error code won't cause the CI run to fail. Move it to be under the `script` tag and you should find the CI run fails!

**Comment by djc** [comment]
That worked, thanks and sorry for the noise!

**Comment by djc** [comment]
(Although you might want to change this in the example in the README as well.)

**Comment by djc** [comment]
I have this in the `script` part now and it still seems to succeed...

**Comment by xd009642** [comment]
I've fixed this again and am publishing a new release 0.8.5 with the fix in at this very moment

**Comment by djc** [comment]
Great, thank you!
