### ISSUE TITLE
Recompiling all dependencies every time is too slow for bigger projects.

### ISSUE THREAD

**Issue by Proksima** [xd009642/tarpaulin#22]
It would be nice to only recompile what is needed instead of always restarting from scratch...

**Comment by xd009642** [comment]
Currently the clean is an act of prudence as dead code, and position independent code need to be generated for coverage to work. I'm working on a large docker based testing method to let me automate testing of tarpaulin on multiple distros and look for disparities in results. Once that's set up if I confirm that not cleaning doesn't have an impact on coverage I'll remove the clean step. After all I don't want to break tarpaulin for other people.

**Comment by xd009642** [comment]
Added a --skip-clean flag to skip the clean stage. Also #29 may be of interest for you to speed up the process of installing tarpaulin on travis.

**Comment by Proksima** [comment]
Thank you for your hard work, this is really appreciated :)
