### ISSUE TITLE
Tarpaulin segfaults on multithreaded raytracer

### ISSUE THREAD

**Issue by DevJac** [xd009642/tarpaulin#220]
I suspect this might be related to #190. If so, feel free to close.

I sometimes get a segfault when running Tarpaulin on my multi-threaded raytracer. Here is the link to the exact commit where this is happening: https://github.com/DevJac/rust-raytracer/tree/0c676608b8ee4990369ba7d9129eaf9ffa79b944 It should be a usable test case, there's some hairy math, but it's just boring Rust with a few crates.

Sometimes tarpaulin works correctly, and sometimes it segfaults, and one time it seemed to hang indefinitely. It is random, I would guess it segfaults about 50% of the time or more. I have done a `git clean -xdf` to ensure I'm starting from a clean slate and I still get the segfault.

`cargo test` works reliably on the same code base.

My unit tests have been the same for quite awhile, and Tarpaulin has successfully run my tests with all previous version of the code. I recently added multi-threading and now I am seeing this issue. It might be related to the multi-threading?

**Comment by xd009642** [comment]
Yeah this is the same issue as #190 (or at least what #190 revealed in addition to it's initial error). I'm hoping to make some progress with this this weekend so thanks for another test case I can use :+1:

**Comment by xd009642** [comment]
Closing as #190 is closed now
