### ISSUE TITLE
html report doesn't show anything

### ISSUE THREAD

**Issue by bbigras** [xd009642/tarpaulin#223]
`commonPath` contained `main.rs`. I was able to fix it by setting it to point to `src` instead.

I'm on the develop branch.

**Comment by xd009642** [comment]
I'm going to need some more details than that. Could you give me a link to the project and where you ran tarpaulin from and the commands used?

**Comment by bbigras** [comment]
Sorry for the short report. It was late and I thought maybe the `commonPath` thing could be enough.

```sh
git clone https://github.com/bbigras/test-project.git
cd test-project
docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:develop-nightly cargo tarpaulin -o Html
```

output
```
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /volume/target/debug/deps/test_project-a645f8a599834781

running 1 test
.
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

|| Tested/Total Lines:
|| src/main.rs: 4/6
|| 
66.67% coverage, 4/6 lines covered
[INFO tarpaulin] Coverage Results:
```

html report is "empty"
![image](https://user-images.githubusercontent.com/24027/57181880-33210680-6e67-11e9-8858-addaee5fbbb5.png)

I think the problem is that `commonPath` is a file while it will get `is_folder: true` 5 lines bellow.
![image](https://user-images.githubusercontent.com/24027/57181911-7e3b1980-6e67-11e9-8ec3-df679f35bb26.png)

![image](https://user-images.githubusercontent.com/24027/57181992-5a2c0800-6e68-11e9-91c7-9355573faa07.png)

If I edit the value to point to `src` instead (and set `length`) and unpause the debugger, it works:
![image](https://user-images.githubusercontent.com/24027/57181951-dffb8380-6e67-11e9-94eb-08440787acb9.png)

![image](https://user-images.githubusercontent.com/24027/57181961-facdf800-6e67-11e9-9540-2ce25a16ad71.png)

**Comment by xd009642** [comment]
@andy128k do you mind helping with this issue? You're better placed to sort this being familiar with react and the html reporting side of things

**Comment by andy128k** [comment]
@xd009642  Done. #224

**Comment by xd009642** [comment]
Cheers @andy128k :+1: @bbigras I've tested this and it now works

**Comment by bbigras** [comment]
Thanks guys!
