### ISSUE TITLE
Lib coverage is missing in codecov.io

### ISSUE THREAD

**Issue by nils-ohlmeier** [xd009642/tarpaulin#226]
The tarpaulin run appears to gather proper coverage numbers:

'[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/travis/build/nils-ohlmeier/rsdparsa/target/debug/deps/webrtc_sdp-6f99e4cb8ed68118
running 116 tests
.................................................................................................... 100/116
................
test result: ok. 116 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/travis/build/nils-ohlmeier/rsdparsa/target/debug/deps/file_parser-5d6b69a2245a5154
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/travis/build/nils-ohlmeier/rsdparsa/target/debug/deps/unit_tests-b2dc59ad04daa1de
running 10 tests
..........
test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/attribute_type.rs: 1460/1662
|| src/bin/file_parser.rs: 0/16
|| src/error.rs: 106/151
|| src/lib.rs: 466/556
|| src/media_type.rs: 293/346
|| src/network.rs: 34/39
|| tests/unit_tests.rs: 245/245
|| 
86.37% coverage, 2604/3015 lines covered'

But then on codecov.io I only see coverage reported for the file_parser executable and the unit_tests https://codecov.io/gh/nils-ohlmeier/rsdparsa/branch/tarpaulin
The unit test coverage in the source file itself appears to be missing. Is this a feature or a bug?

**Comment by xd009642** [comment]
It would be a bug, but when I go on the codecov link I see coverage for the whole project and for each file in files. I've attached a screenshot of what I see

![Screenshot_20190520-073525](https://user-images.githubusercontent.com/3472518/58000941-2e4c8b80-7ad2-11e9-9c8e-6420c742dd89.png)

**Comment by nils-ohlmeier** [comment]
Yes I fixed it last night by moving the example code from src/bin/file_parser.rs to examples/file_parser.rs. That's why there is now proper coverage showing up.

If you are interested I can drop the links to the previous code and the results on codecov.io here. But since I have a workaround now feel free to close the issue.

**Comment by xd009642** [comment]
I would be interested in having a look just to see if it's a bug or not :+1:

**Comment by AnderEnder** [comment]
Looks like it is a bug in xml or on codecov side.

I have several projects and the issue appears only after last release. 
Example:
* last good result with the previous tarpaulin version: https://codecov.io/gh/AnderEnder/s3find-rs/tree/cd3ed5e71604283a238c19ff6260271103c144f9
* next run with only dependency changes with new tarpaulin version: https://codecov.io/gh/AnderEnder/s3find-rs/commit/10394cabd9e11b898a73e7c68bc3f37446679475

The most interesting thing is that only files in src are disappeared. Any `src/bin/*` or next level nested library files are present.

**Comment by nils-ohlmeier** [comment]
So here is the codecov result from where when I still had 'src/*.rs' & 'src/bin/*.rs'
https://codecov.io/gh/nils-ohlmeier/rsdparsa/tree/d7d8f53aa43e917bef25175e5a6094f32bdbe1a0

Using tarpaulin's file exclusion resulted in the coverage for 'src/*.rs' showing up here:
https://codecov.io/gh/nils-ohlmeier/rsdparsa/tree/0519f18c8bb7de77f17ba3d59ba4cab78b15d891

And moving /src/bin to /examples also results in coverage for 'src/*.rs' showing up properly:
https://codecov.io/gh/nils-ohlmeier/rsdparsa/tree/42b2a655824520b99ade009f9dc8ea65cd97d19f

You can find my attempts to get useful numbers in codecov in my tarpaulin branch:
https://github.com/nils-ohlmeier/rsdparsa/commits/tarpaulin

**Comment by nils-ohlmeier** [comment]
[cobertura-reports.tar.gz](https://github.com/xd009642/tarpaulin/files/3200051/cobertura-reports.tar.gz) here is a tarball of the two different cobertura XML files.

**Comment by nils-ohlmeier** [comment]
Thank you @AnderEnder. Super quick turn around time :-)
Is there a way for me to help testing the fix?

**Comment by xd009642** [comment]
The latest build on the develop branch has it in so you can test from there :smile:
