### ISSUE TITLE
Drop RUSTFLAGS requirement

### ISSUE THREAD

**Issue by dtolnay** [xd009642/tarpaulin#228]
I tried compiling cargo-tarpaulin with:

```toml
proc-macro2 = { version = "0.4.27", features = ["span-locations"] }
```

and it seemed to work. Is there anything other than Span::start/end that you rely on from the procmacro2_semver_exempt mode?

**Comment by xd009642** [comment]
Not that I can think of, I'll run it on some larger projects to make sure though.

Thanks for letting me know

**Comment by xd009642** [comment]
It built but there were some test failures. I'll look into them tonight and ask if there's anything i don't find obvious

**Comment by xd009642** [comment]
Yeah I vaguely remember seeing these same issues when I last attempted to remove semver_exempt from the build, some elements in the syntax tree have more specific spans in the semver_exempt version. So it builds and compiles but some of my filtered out false negatives aren't removed from results. 

I'll have to do a proper impact assessment and figure out if that's acceptable and if I can just mark those tests as ignored and let people install it and live with less accurate results if they want to remove the RUSTFLAGS faff..

**Comment by dtolnay** [comment]
Would you be able to track down the origin of the discrepancy? My only guess would be [this stuff](https://github.com/dtolnay/syn/blob/3c40005ac5a0643d48ab11cad94a81ad258e4510/src/spanned.rs#L138) if you are using it. If that's the only thing, it should be pretty easy to implement source ranges based on line/column on your end in a way that does not require joined spans -- I can help out if you get stuck.

**Comment by xd009642** [comment]
Yes it's joined spans! I think this affects all the things like getting the locations of braces or individual enum fields or attributes before a block?

**Comment by dtolnay** [comment]
It shouldn't affect braces -- a matched pair of braces are associated with a single span by the compiler that covers the entire thing.

For enum fields or attributes, you would need to quote them to TokenStream and then traverse each top-level token in the TokenStream to compute the min and max line/column of their individual start and end locations.

**Comment by xd009642** [comment]
RUSTFLAGS requirement is now dropped! Thanks for pointing me towards TokenStream :+1:
