### ISSUE TITLE
Persistent URLs in HTML report

### ISSUE THREAD

**Issue by paulvt** [xd009642/tarpaulin#230]
Currently, while navigating the coverage report it does not retain the path within the project while navigating.  It would be nice if that would be possible so one could refer to a specific directory/file and also support refreshing it.  For refreshing one needs to keep re-navigating to the same location.

For example, I am currently working on a multi-crate project and looking at `some-crate/protocol/payload/event.rs`. Every time I rerun tarpaulin, I have to navigate to that place again.
If the URL would reflect the location, i.e. https://somehost.tld/path/to/tarpaulin-report.html#some-crate/protocolpayload/event.rs, I could both easily refresh it and refer others to it.

I must admit that I am used to this feature from Ruby's simplecov HTML reports. So if the issue is solved with a simple Refresh button next to Back, I guess that is another way to go about it too.

**Comment by xd009642** [comment]
@andy128k I was wondering if you could have a look at this being the one most familiar with the HTML reports :smile:

**Comment by xd009642** [comment]
@paulvt this is now in the develop branch if you're okay using that :+1:. I'll release a new version once I get a feature I'm currently working on in.

**Comment by paulvt** [comment]
Thanks all! I will use the develop-nightly Docker image for now until the new version is out.

A small nitpick, when one uses the browser's back button, the URL is indeed change to the previous location, but not the page itself? This could be a bit confusing for the user.

**Comment by xd009642** [comment]
@andy128k I don't suppose you could look at the back button thing? If so could you branch off of the develop branch and have the PR merge into develop please :+1:

**Comment by xd009642** [comment]
@paulvt this is all in 0.8.2 release now (also as a bonus no more need to install tarpaulin with RUSTFLAGS or run on nightly :smile: )
