### ISSUE TITLE
0.8.2 output exceeds maximum log length on Travis.ci

### ISSUE THREAD

**Issue by crsmithdev** [xd009642/tarpaulin#233]
After upgrading to 0.8.2, I no longer get coverage on Travis.ci.  The jobs now output a huge data structure that kills the job by overloading the log.  Going to try just redirecting all the output and see if I can work around it.

Error message: `The job exceeded the maximum log length, and has been terminated`

Example log output: https://gist.github.com/crsmithdev/c62e4b600556024dce54430133df7697

My .travis.yml: https://github.com/crsmithdev/chip8/blob/8a1421e7050baeaedca568b6c5846c4d006e5295/.travis.yml

Is this a bug or some issue on my end?

**Comment by xd009642** [comment]
This is a bug, something that slipped through the net because I was going off when the tests went from failing to passed! Amending, and yanking 0.8.2/1 right now!

**Comment by xd009642** [comment]
Right give it 30 minutes and it should be all uploaded and ready to go

**Comment by crsmithdev** [comment]
Great, thanks!
