### ISSUE TITLE
Update nightly containers with compiler bug fix

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#239]
https://github.com/rust-lang/rust/issues/58375 was finally fixed last week, and this was crashing rustc for Quinn's coverage jobs. Could you update the nightly container builds to a recent version?

**Comment by xd009642** [comment]
I've just hit the trigger button on all the automated build triggers which I believe runs the docker files and creates the images. Let me know if that doesn't work and I'll see what I can do :+1:

**Comment by djc** [comment]
Awesome, thanks!

**Comment by djc** [comment]
Okay, that problem has been fixed, thanks for the quick response!
