### ISSUE TITLE
Optional dependency should be ignored

### ISSUE THREAD

**Issue by DarkEld3r** [xd009642/tarpaulin#24]
In my situation there is optional (and disabled by default) dependency which can only be compiled with nightly Rust. Tarpaulin gives an error when I try it with stable Rust:
```rust
$ cargo tarpaulin
error[E0554]: #[feature] may not be used on the stable release channel
 --> /home/stkach/code/exonum/3rdparty/flamer/src/lib.rs:2:1
  |
2 | #![feature(plugin_registrar, quote, rustc_private, custom_attribute)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `exonum_flamer`.
No coverage results collected.
```

**Comment by xd009642** [comment]
I believe I've just solved this, as well as made some other small usability things testing on your project pointed me towards. I'll test and then if it's working push a new patch version out afterwards.

**Comment by xd009642** [comment]
So the compilation and running issue is fixed. Tests like reconnect that talk to 127.0.0.1:7201 etc hang on my system. But that may be because I don't fully replicate your test environment. If it's down to an issue in tarpaulin raise another issue and I'll address it :)

**Comment by DarkEld3r** [comment]
@xd009642 This problem is fixed thank you. :+1:
