### ISSUE TITLE
Matching sources in multi-crate repo

### ISSUE THREAD

**Issue by PSeitz** [xd009642/tarpaulin#240]
I have a project where I have multiple test runs from different crates in a single repo.

https://github.com/PSeitz/veloci/blob/master/.travis.yml

The results are uploaded to coveralls, but the source files are not correctly merged, e.g. server/rocket_server.rs is also listed on root. 
The coverage of  server/rocket_server.rs  is also weird, it's 0% but most lines are ignored.
https://coveralls.io/builds/25100652

Is something like this supported currently? If you point me in the right direction I could try to make a PR for this.

**Comment by xd009642** [comment]
I'm away from my pc right now but you could look at the developer wiki and see if it's helpful. Also, the report module handles generating reports, source analysis looks for ignorable lines and the lib.rs handles cargo so it's probably some of them you want or the tracerData struct (name might be slightly wrong)

**Comment by xd009642** [comment]
So looking at your recent coveralls and my own run there is no `rocket_server.rs` in the root of the project anymore and I only released a new version today and with no changes that could account for that...

There are a lot of ignored lines there as well. My only guess is that potentially some of the code is inlined out as that can stop me correctly finding the source lines, or maybe there's something else I haven't anticipated.

Do you have anymore examples of issues in merging?

**Comment by PSeitz** [comment]
I'm using my tarpaulin fork in the coverage tests, where I fixed those issues by calculating all relative paths to env::current_dir. I wanted to open a PR, but have to resolve some merge conflicts first.

There is still an related issue.
In this run I disabled all tests except from the base directory. The tests from the base directory scan the server folder and ignore most of the lines:
https://coveralls.io/builds/25187005/source?filename=server/rocket_server.rs

**Comment by xd009642** [comment]
So I haven't looked at your fork but one thing springs to mind: `env::current_dir`could fail in instances where someones using the `root` argument and an absolute path. Probably better to use the method in the `Config` struct to get the directory relative to the Cargo.toml you're running tarpaulin on.

Maybe check with the latest tarpaulin as well just because I don't have the issue with `rocket_server.rs` being repeated in the root for my coveralls.json

**Comment by PSeitz** [comment]
I changed the logic that if root is set, paths are calculated relative to the root, else to the `env::current_dir`. To use another Cargo without changing the base dir, I added the manifest-path, which is also used in cargo.

The issue still persists with the latest tarpaulin, when there are multiple runs and one of them targets server as root.

Do you know why most of the files are ignored here:
https://coveralls.io/builds/25187005/source?filename=server/rocket_server.rs
When coveralls merges the runs, it still ignores most of the lines.

**Comment by xd009642** [comment]
@PSeitz does your PR #244 solve all your multi-crate issues?

**Comment by PSeitz** [comment]
There is still the issue with the merge:

Coverage in coveralls is wrong for rocket_server.rs. The test run from the root folder ignores most of the lines, which are still ignored when merged:
https://coveralls.io/builds/25207759
When I execute only the tests in the server directory, the coverage looks fine.
https://coveralls.io/builds/25209623

In Codecov, the merge looks fine:
https://codecov.io/gh/PSeitz/veloci/tree/a9f7d6f49f976f2fdc7c205ff1c799d639953d42

**Comment by xd009642** [comment]
So the coverage is always fine in codecov and not coveralls? That's odd... I'll see what I can find

**Comment by PSeitz** [comment]
Yes, the merge in Coveralls seems to keep the ignored lines. I don't see why they are ignored in the first place.

**Comment by PSeitz** [comment]
Now each run adds its own file (eg. 7x src/lib.rs). Still weird, but at least more consistent than before

https://coveralls.io/builds/26518612

**Comment by xd009642** [comment]
@PSeitz is this still an issue? Just because some similar issues have been closed the start of this year so things might work now. Also the tarpaulin config file lets you run different configurations and merge the results which may be useful for you

**Comment by PSeitz** [comment]
Yes, the multi-crate issues seem to be resolved, nice!
