### ISSUE TITLE
Tarpaulin fails when a build script is present

### ISSUE THREAD

**Issue by urschrei** [xd009642/tarpaulin#241]
After switching to cargo-tarpaulin, [it fails when a project runs a custom build command](https://travis-ci.org/urschrei/polyline-ffi/jobs/569346684#L780) (in this case, a `build.rs` to generate a header file). Is this is a known bug / is there a suggested fix?

**Comment by xd009642** [comment]
so I've used tarpaulin personally on one of my projects with a build script and it works fine. I need to look into your build.rs and figure out what it's doing that isn't supported then fix that :+1:

**Comment by urschrei** [comment]
Yeah, it was working using the older gist-based tarpaulin install, the error only cropped up when I switched to cargo-tarpaulin last week. Build script source is here: https://github.com/urschrei/polyline-ffi/blob/master/src/build.rs

Thanks!

**Comment by adam-mcdaniel** [comment]
Im having this problem as well.

[Here's my repo](https://github.com/adam-mcdaniel/rusty-ci)

**Comment by xd009642** [comment]
So I put some debug logging in the build.rs and found this error returned from `generate_with_config`:  `CargoMetadata("/home/xd009642/code/rust/metatarp/polyline-ffi/Cargo.toml", Json(Error("EOF while parsing a value", line: 1, column: 0)))`

Now looking into this to see if I can track down why :+1:

**Comment by xd009642** [comment]
So I've removed cargo as a dependency and now propagate more environment variables to the environment when running tests which has solved a lot of issues in other crates (get more access to nightly features and not locked into cargos stable release cycle).

I tried again on polyline and there's now no issues with the build script just this compiler issue when building the tests which I also experience when running with `cargo test`:

```
error: include macro expected single expression in source
  --> src/../test_fixtures/berlin.rs:84:2
   |
84 | ];
   |  ^
   |
   = note: `#[deny(incomplete_include)]` on by default
```

So I'm going to close this as it appears to be solved, if the other issue in polyline is also a tarpaulin issue feel free to reopen this issue. Though I'll also need some help in running the tests outside of tarpaulin to work on it :smile:

**Comment by urschrei** [comment]
Can confirm this is working perfectly now. Thanks!
