### ISSUE TITLE
Tarpaulin fails when `default-run` is present

### ISSUE THREAD

**Issue by adam-mcdaniel** [xd009642/tarpaulin#242]
When I leave the `default-run` key in my `Cargo.toml`, tarpaulin can't parse my manifest.

[Here's my repo](https://github.com/adam-mcdaniel/rusty-ci)

**Comment by xd009642** [comment]
This is now fixed, just had to bump the cargo version number :+1: it's pushed to the develop branch and I'm just doing a release now so that will be up in about 20 or so minutes
