### ISSUE TITLE
Please provide a changelog

### ISSUE THREAD

**Issue by ArekPiekarz** [xd009642/tarpaulin#243]
Every time Tarpaulin bumps its release I want to know what changed, however each time I have to manually look through the commit list for the last release and go up from there. Would it be possible to summarize changes in a single place? I believe it would also help motivate people to update this project on their systems.

**Comment by xd009642** [comment]
So I've written a changelog for everything done in this year if you have any feedback https://github.com/xd009642/tarpaulin/blob/develop/CHANGELOG.md

**Comment by ArekPiekarz** [comment]
I like that you are using "Keep a Changelog" format. The only thing I noticed to correct is a typo in "[0.8.1] 2019-05-26 [YANKED}", where the last character should be a square bracket. Other than that, good work!

**Comment by xd009642** [comment]
Corrected and closing this issue as a result :smile:
