### ISSUE TITLE
Tarpaulin picks up source files in target/rls in workspace projects

### ISSUE THREAD

**Issue by YaLTeR** [xd009642/tarpaulin#246]
1. Create a new workspace with one library project.
1. Add something that generates source files as a dependency (e.g. `wayland-protocols = { version = "0.23.5", features = ["client"] }`).
1. Open `lib.rs` of that project in an editor with RLS configured and let it initialize and build the project.
1. Run `cargo tarpaulin` and observe that it added all generated files from `target/rls` to the coverage report.

**Comment by xd009642** [comment]
There's an exclude files argument so you can filter out generated code from coverage
