### ISSUE TITLE
Merge Multiple Runs

### ISSUE THREAD

**Issue by JP-Ellis** [xd009642/tarpaulin#248]
Can tarpaulin handle multiple runs (with different options)?

For example, there may be two mutually exclusive features `foo` and `bar`, and the code coverage might need to be run on both.  How would one do this and merge the results?

**Comment by xd009642** [comment]
I believe the readme covers this with extending tarpaulin. There's a project called pycobertura that lets you merge the XML reports but there should be a better way in tarpaulin itself

**Comment by xd009642** [comment]
I was thinking of a toml file describing all the runs

**Comment by JP-Ellis** [comment]
I did have a very quick look at `pycobertura` and there does not appear to be a `pycobertura merge` option, so I'm sure what you mean (unless you meant that I would have to write my own script to merge the reports?).

A toml file describing the runs is a good option for projects with more complicated features, but could be overkill for small projects.  A `--merge-output` option I think would be useful if just a couple or runs are needed.

**Comment by PSeitz** [comment]
Related Issue: https://github.com/xd009642/tarpaulin/issues/240

**Comment by xd009642** [comment]
So this is now solved by the new config file format in develop https://github.com/xd009642/tarpaulin/tree/develop#config-file feel free to try it out and feedback on this issue https://github.com/xd009642/tarpaulin/issues/350 in the meantime I'll close this issue
