### ISSUE TITLE
migration ci from travis to github actions

### ISSUE THREAD

**Issue by AnderEnder** [xd009642/tarpaulin#257]
Github action is a beta service of github(https://github.com/features/actions) and already available for signup. It provides more executors for the projects.

Can this project be migrated to github actions?

I can start this initiative, but it requires to enable actions for the repository.

**Comment by xd009642** [comment]
I'm curious is there anything comparing github actions to travis and what the benefits would be? Also, according to settings actions now seem to be enabled so feel free to submit a PR.

**Comment by AnderEnder** [comment]
Now there is a main benefit as a shorter feedback loop because there are more parallel executors and probably more powerful VMs.

**Comment by AnderEnder** [comment]
@xd009642,

Can this issue be closed or something else is required to be implemented?

**Comment by xd009642** [comment]
Yeah forgot to close it!
