### ISSUE TITLE
Package and/or manifest-path options support

### ISSUE THREAD

**Issue by DarkEld3r** [xd009642/tarpaulin#26]
Most of the Cargo commands support `-p`/`--package` and `--manifest-path` options which is handy for workspaces.

**Comment by xd009642** [comment]
So the root option in tarpaulin is equivalent to the manifest-path option. I admit name consistency may be better, although I do personally like the --root and -r short form for project root. As for package command I agree that is a good idea and now on the list of things to do. :+1:

**Comment by xd009642** [comment]
I added packages so you can specify one or more package specs i.e. --packages=clap:0.3,cargo:1.0. If you fancy trying it out and seeing if it meets your needs that would be helpful :+1:

**Comment by xd009642** [comment]
Unfortunately when testing to ensure I could close this issue I found my latest release with source analysis broke this functionality. I'm adding the bug label and working on a fix, currently have a partial fix on my pc but working on a fix that doesn't sacrifice new features!

**Comment by xd009642** [comment]
Fixed and tested it on exonum itself with the exonum and sandbox packages :smile:

**Comment by DarkEld3r** [comment]
@xd009642 Thank you, I'm going to try it soon! 👍
