### ISSUE TITLE
wrongly 'uncovered' lines

### ISSUE THREAD

**Issue by Licenser** [xd009642/tarpaulin#262]
Hi, we noticed a few inconsistencies with what lines are considered covered and which are not.

Some things we found:

* macros in function bodies are not considered covered even if they get executed: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/stage2.rs#L133
* branch heads are sometimes not considered covered even if their bodies are: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/stage2.rs#L227
* inline  function headers are not always considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/lib.rs#L177
* unsafe blocks are not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/lib.rs#L196
* initalisation to 0 is sometimes not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/lib.rs#L227
* refferences as function parameters (to inlined functions) are not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/avx2/stage1.rs#L413
* precompiler directives in function bodies are not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/avx2/generator.rs#L21
* `break` is not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/avx2/deser.rs#L87
* some let assignments are not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/avx2/deser.rs#L124
* some match statements are not considered covered: https://codecov.io/gh/simd-lite/simdjson-rs/src/master/src/value/borrowed.rs#L87

**Comment by jhpratt** [comment]
Running into the "inline function headers" bit myself. I think this specific case could be solvable by automatically marking the header as covered if any part of the body is.

**Comment by xd009642** [comment]
Closing in favour of https://github.com/xd009642/tarpaulin/issues/351 might be worth testing the latest develop there are a number of improvements in coverage accuracy that could help some of these issues
