### ISSUE TITLE
v0.9 segfaults during tests

### ISSUE THREAD

**Issue by Licenser** [xd009642/tarpaulin#264]
After the 0.9 release tarpaulin started to segfault when running tests:

* (0.9) https://github.com/simd-lite/simdjson-rs/runs/249286547
* (reverted to 8.7) https://github.com/simd-lite/simdjson-rs/commit/fccee1413ebf1cd68c983bfdce59b0d59c458010/checks?check_suite_id=253081140

**Comment by rye** [comment]
Same here: https://github.com/rye/rust-netaddr2/runs/249317332

**Comment by xd009642** [comment]
Ah cripes. You should be able to revert to the old behaviour by adding `-- --test-threads=1` to the end of your command to run tarpaulin

**Comment by Licenser** [comment]
👍 can confirm `-- --test-threads=1` solved the issue :D for us! thanks!

**Comment by xd009642** [comment]
This may be fixed in the 0.9.1 release which is in the process of being built and pushed to crates.io via github actions

**Comment by Licenser** [comment]
Can confirm it's fixed on my end :) happy to close if no one else has objections

**Comment by xd009642** [comment]
Closing any new segfaults etc open a new issue as this one has already covered two causes no need to grow it further :)
