### ISSUE TITLE
gitlab integration

### ISSUE THREAD

**Issue by gdesmott** [xd009642/tarpaulin#266]
Would be nice to be able to integrate tarpaulin's output with [gitlab test coverage system](https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing)

**Comment by xd009642** [comment]
What barriers are there to this? Is it not just a case of defining the necessary regex which I think should be something like `^\d+.\d+% coverage`

**Comment by xd009642** [comment]
I've added a small section to the readme on the develop branch with instructions on using tarpaulin with gitlab pipelines and confirmed they work on a small test project :+1:

**Comment by gdesmott** [comment]
Thanks a lot @xd009642 !

I'd suggest to use `cargo install --force` in the CI config, see https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/commit/d584c3ba2325b5388c299235489b8647b776a4bc for the rational.
