### ISSUE TITLE
Could tarpauling set an environment variable to detect in build.rs?

### ISSUE THREAD

**Issue by stevenroose** [xd009642/tarpaulin#268]
I have a build.rs for my project and it somehow fails when tarpauling tries to execute it as part of the build. Otherwise it doesn't fail. It's not needed for tarpaulin to work, so I'm thinking of having the build.rs just return when it detects a tarpaulin run.

Would it be possible for tarpaulin to just set a simple env variable like TARPAULIN=1 or something? I think it can make sense in more cases than just mine.

**Comment by xd009642** [comment]
Yeah sure, I had seen the build.rs issue with some repos and not others so was hoping to get to the bottom of it and solve it properly but this seems a reasonable compromise

**Comment by xd009642** [comment]
There's now a version with this in the develop branch if you want to already start using it
