### ISSUE TITLE
Random segfault on Azure

### ISSUE THREAD

**Issue by baszalmstra** [xd009642/tarpaulin#272]
We're running into a segfault on Azure that seems to be happening randomly. I've created a PR on our repo with the fix given in #264 which seemed to run fine:
https://dev.azure.com/mun-lang/mun/_build/results?buildId=146&view=results

But once the PR was merged into the repo it segfaulted again:
https://dev.azure.com/mun-lang/mun/_build/results?buildId=148&view=results
https://dev.azure.com/mun-lang/mun/_build/results?buildId=152&view=results

The code between these commits is the same. I also cant figure out how to get any more information. Any help would be greatly appreciated!

**Comment by xd009642** [comment]
Since #190 is now closed can you let me know if this is still an issue?

**Comment by baszalmstra** [comment]
I'll close this since we are now using grcov since it also supports Windows and macOS.
