### ISSUE TITLE
codecoverage of a unique function

### ISSUE THREAD

**Issue by mimoo** [xd009642/tarpaulin#278]
Hello!

I am trying to figure out the code coverage of a unique non-test function, is this possible?

Thanks!

**Comment by xd009642** [comment]
Only via creating a test that just calls that function. If you don't want to run all the tests but just the test that calls the function you can add arguments you'd give to your tests after a `--` and use that to filter the tests you run coverage for.

So if the test was called `unique_fn_coverage` you could use the command `cargo tarpaulin -- unique_fn_coverage`.

**Comment by mimoo** [comment]
I see, one problem I can see is that I don't want things to run with the cfg test flag. Also I now realize that this might not really fit my use-case: I want to test the function coverage of a function that takes a bytearray, and I don't have a bytearray to give it. This is because I want to see how much code is covered by fuzzers.

**Comment by xd009642** [comment]
Ahh right, there is a feature request for coverage of any binary I haven't started work on it because I need to think of the best way to implement it so people can get coverage of other things like benchmarks, examples, fuzz tests etc. I'll have a think about it more in detail and see if I can think of a nice solution (and I'm always open to contributions!)

**Comment by xd009642** [comment]
So I've added coverage for benchmarks and am currently making sure an implementation of coverage for example executables work. This should hopefully make coverage for binaries which are fuzz runs easy to add

**Comment by xd009642** [comment]
So I've been using fuzzers myself recently and saw someone get coverage of how much of their code is covered by fuzzers by adding a single test that just runs on the code on their entire corpus once they'd generated it. Dunno if that's something you fancy trying in the meantime?

**Comment by mimoo** [comment]
hey thanks for getting back to me. Yes after thinking about this for a bit I think this is the best approach, because the corpus you end up generating is supposed to represent every path your fuzzer can reach! Is there anything special I need to do for this to work with Tarpaulin?

**Comment by xd009642** [comment]
You can just write a test that iterates over every file in the corpus and runs it. Then hard code the path or put it in an environment variable

**Comment by mimoo** [comment]
looks like it's working! But I'm getting this error when trying to create a report:

```
[ERROR tarpaulin] Failed to create report directory: No such file or directory (os error 2)
```

I run this:

```
cargo tarpaulin --output-dir /home/vagrant/libra/testsuite/libra-fuzzer/report -o Html
```

**Comment by xd009642** [comment]
Does the folder exist? I'm not sure if I create it if it doesn't exist. Though that's easy enough to add if so

**Comment by mimoo** [comment]
yup the folder exists, I tried with a non-existing folder as well and no luck :c

**Comment by xd009642** [comment]
So I tried to recreate the issue with both folders that existed and folders that didn't. Are you sure the issue doesn't originate in your own tests? The `--debug` output may be helpful or ideally a minimal example to reproduce the issue

**Comment by xd009642** [comment]
Closing this issue as dormant as it's been a few years, feel free to reopen or open a new issue if you still require help
