### ISSUE TITLE
HTML Output broken

### ISSUE THREAD

**Issue by caemor** [xd009642/tarpaulin#282]
Html output seems to be broken on 0.9.1 at least for the repos I tested it on. The Website only shows an empty white page. One example is https://github.com/caemor/openweather where the output is the following: 

[tarpaulin-report.txt](https://github.com/xd009642/tarpaulin/files/3836614/tarpaulin-report.txt)
(Renamed file ending to txt since Github doesn't allow .html file uploads in issues)

Used commands:
```
openweather on master is 📦 v0.1.0 via 🦀 v1.39.0 
❯ cargo tarpaulin --out Html
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running .../openweather/target/debug/deps/openweather-b4cf90dc67c35db0

running 2 tests
..
test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/lib.rs: 38/122
|| src/location.rs: 5/38
|| src/parameters.rs: 7/50
|| 
23.81% coverage, 50/210 lines covered

❯ cargo tarpaulin --version
cargo-tarpaulin version: 0.9.1

```

**Comment by charmander** [comment]
Do you have JavaScript enabled? Are there any script errors in your browser’s console?

**Comment by caemor** [comment]
I am using firefox and JS isn't disabled (and ublock disabled). I also thought that it didn't show any output in Chromium when I first tested it. But for now it's working there :thinking: 

```
1.Warning: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://unpkg.com/react-dom@16.11.0/umd/react-dom.production.min.js. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://fortcdn.com’).

2.Warning <script> source URI is not allowed in this document: “https://unpkg.com/react-dom@16/umd/react-dom.production.min.js”. tarpaulin-report.html:111:1

1. Error: ReferenceError: ReactDOM is not defined tarpaulin-report.html:348:3
    <anonymous> file:///home/caemor/github/openweather/tarpaulin-report.html:348
    <anonymous> file:///home/caemor/github/openweather/tarpaulin-report.html:349
```

**Comment by xd009642** [comment]
It works on firefox for me, apparently the issue can be caused by out of date or untrusted security certificates if you find another website using the ReactDOM production min package and see if that works on your firefox that might be useful? I'll google around and see if I can solve it

**Comment by caemor** [comment]
It's working now :+1: So it really might have just been some certificate issue...
