### ISSUE TITLE
release tarpaulin as binary

### ISSUE THREAD

**Issue by PSeitz** [xd009642/tarpaulin#283]
```cargo install cargo-tarpaulin``` always takes a long time to compile on travis, any plans to provide some binaries?

**Comment by xd009642** [comment]
There are binaries, I think the readme has instructions for downloading the travis install shell script (maybe not before proc-macro was stable precompiled binaries only worked with the same nightly that compiled them). But yeah you can download just the travis install script and run that to download the latest compiled binary (for travis) from github releases or use docker

**Comment by PSeitz** [comment]
Ah I was looking a the wrong place for the github releases. 
The readme only has instructions referencing `cargo install cargo-tarpaulin` though.
