### ISSUE TITLE
Apply the changes in coverage to HTML report

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#284]
As of 0.9.2 tarpaulin stores a serialisation of the result `TraceMap` in `target/tarpaulin` so it can report the change in coverage between runs. It would be nice if this could be added to the HTML reports.

I admit I have zero front-end skill so if anyone fancies tackling this it would be appreciated

**Comment by andy128k** [comment]
Browsers do not allow to load JSON files from filesystem if main HTML file was opened from local filesystem (`file:///`). That's why coverage info is embedded into HTML report. Otherwise a webserver is needed.

**Comment by xd009642** [comment]
Could always embed the previous report into the document as well, or take the code from my console reporting and make any changes in the interface to get the deltas and add them to the file

**Comment by bojan88** [comment]
I can implement this.
Can you please describe it a bit better? How do you want it displayed and where?

**Comment by xd009642** [comment]
For the html reports at the very least on the coverage

**Comment by bojan88** [comment]
@xd009642 what do you think about something like this?
![screenshot](https://user-images.githubusercontent.com/1783133/72764227-2e4ae100-3bb5-11ea-8852-9c971299446a.png)

**Comment by xd009642** [comment]
Yeah that's fine for the file level :+1:
