### ISSUE TITLE
Code coverage should not use benchmarks or examples by default

### ISSUE THREAD

**Issue by philipc** [xd009642/tarpaulin#285]
Benchmarks and examples are not tests, and should not be included in code coverage by default.

**Comment by philipc** [comment]
Also:

- `--run-types Tests` has no effect, the examples are still run
- `--quiet` is being passed as an argument to the examples

**Comment by xd009642** [comment]
I decided earlier on to not exclude those directories by default as I may have to add the ability for users to include them again. Also I wasn't sure if they were reserved names or if a user could repurpose them..

Is `--quiet` being passed to examples an issue? Using the `--verbose` flag will stop it

**Comment by philipc** [comment]
> I decided earlier on to not exclude those directories by default as I may have to add the ability for users to include them again.

What do you mean by 'earlier on'? In my opinion this is a regression in the last release, introduced by 54fff46a752b63ac7ffe36fa44ddad00d50d9e42 and f720229634e39e42d3a0c94e47c69383304e1c99. I'm fine with running any tests in those directories, but you should not be running any benchmarks or examples.

> Is --quiet being passed to examples an issue? Using the --verbose flag will stop it

Yes, examples are free to interpret any arguments passed to them however they want. For example, my one of my examples will try to open it as a file, another will report an error about an unknown argument. Using --verbose seems like a workaround for a bug.

**Comment by xd009642** [comment]
Wait are they actually ran? I thought you just meant they were included in the coverage results.

Also, I sort out the `--quiet` flag once I'm back from work again another slightly misunderstanding and probably a lesson that I shouldn't be trying to respond to things on my morning commute :sweat_smile:

**Comment by philipc** [comment]
Yeah, have a look at https://travis-ci.org/gimli-rs/gimli/jobs/614345787, it ran `/home/travis/build/gimli-rs/gimli/target/debug/examples/simple`. I'm not sure now whether benchmarks are actually run, can't check right now.

**Comment by xd009642** [comment]
Yeah it looks like it's running the examples with the tests but not the benchmarks... I'll fix that tonight

**Comment by xd009642** [comment]
So I realised what it was and am just testing a fix. I'm also going to add a more involved test case to ensure this regression doesn't happen again and if it all works I'll publish 0.9.3 tonight

**Comment by xd009642** [comment]
So just for some background explanation the examples have always shown up in the binaries list when I build just the tests. Not sure why I tried to solve it but it's either something that doesn't seem clear in the cargo source code or isn't part of the public API surface (which lets you do less than cargo test as a command lets you do).

There's now a test for all the types of coverage tarpaulin offers and making sure for that RunType coverage for the other RunTypes remains at zero

**Comment by philipc** [comment]
That works, thanks!
