### ISSUE TITLE
Support lcov.info format

### ISSUE THREAD

**Issue by jwir3** [xd009642/tarpaulin#287]
I know that HTML reports have landed in #182, and the issue related to that mentions lcov. One thing that would be nice is to support lcov-style output files (e.g. lcov.info), so that tools like https://atom.io/packages/lcov-info would work out of the box.

**Comment by xd009642** [comment]
Yeah that sounds like a reasonable feature to add, and probably isn't that hard to do a PR for... I'll try to get to it myself but I'm rather busy at the moment so I'll also mentor anyone who happens across this drawn by the help-wanted label :smile:

**Comment by xd009642** [comment]
Some description of the file format https://github.com/mitchhentges/lcov-rs/wiki/File-format

**Comment by bojan88** [comment]
I have most of this implemented, and will be creating a PR soon

**Comment by xd009642** [comment]
This is now in the develop branch thanks to @bojan88 I'll probably drop a new release this week
