### ISSUE TITLE
Request: Support --target-dir

### ISSUE THREAD

**Issue by SOF3** [xd009642/tarpaulin#289]
I use `--target-dir` to reuse cargo intermediates as well as to manage disk space usage better. However, `cargo tarpaulin` always tries to use the default target directory, which breaks my workflow.

**Comment by xd009642** [comment]
Yeah #247 covers this and more, I'll look into this and see if I can figure it out tonight

**Comment by xd009642** [comment]
I've implemented this and tested it locally. Just waiting for the CI to finish and then I'll merge it into develop where you can use it before the next release
