### ISSUE TITLE
Create a binary for travis-ci

### ISSUE THREAD

**Issue by tailhook** [xd009642/tarpaulin#29]
It looks like tarpaulin builds ~ 10 min. So it's unwise to build it every time. I think it's easy to setup `.travis-ci.yml` for this project which uploads `cargo-tarpaulin` built on travis to github releases. So downloading ready to use binary is much much faster.

What do you think? Do you need any help with that?

**Comment by xd009642** [comment]
Sounds like a good idea, I haven't automated github releases before let alone from travis. If you don't mind picking this up that would be appreciated :+1: my current thought is using the latest tagged commit to get the latest stable version and then maybe offering a "latest and greatest" download which would be the most  recent commit to master. Any thoughts or comments on the idea?

**Comment by tailhook** [comment]
Travis CI deploy plugin allows only uploading binaries to a tagged release. And I think this is also a github issue. While I could make a PR, you need put an encrypted github key for the upload. [Docs](https://docs.travis-ci.com/user/deployment/releases/). Let me know if I can help further.

**Comment by xd009642** [comment]
Okay I'll let you know, cheers.

**Comment by xd009642** [comment]
Sorted :+1:

**Comment by robinst** [comment]
(For anyone landing here:) If you prefer installation via `cargo install` on Travis, doing the installation in an `install` script makes it possible to use the cache and avoid installation in subsequent builds. Something like this:

```yml
...
cache: cargo
install:
  - cargo tarpaulin --version || cargo install cargo-tarpaulin
```

@xd009642 if you'd like to include this in the README, I can raise a PR for it if you want.

**Comment by xd009642** [comment]
@robinst yeah if you don't mind. If you could also add a small bit of text explaining the two options as well as whether it will install the latest version of tarpaulin if a newer version is published than the version in the cache?

**Comment by robinst** [comment]
> if a newer version is published than the version in the cache?

Yeah, that's the downside of the `cargo install` approach. To upgrade, you need to clear the cache manually. I think the currently described way is fine, no need to add another way.
