### ISSUE TITLE
Tarpaulin fails certain tests that pass on cargo test

### ISSUE THREAD

**Issue by sgvolt** [xd009642/tarpaulin#300]
I have a somewhat iffy test case that succeeds when run with `cargo test`, but fails on invocation of `cargo tarpaulin`.

Boundary conditions: I am running `rustc 1.37.0 (eae3437df 2019-08-13)` and `cargo-tarpaulin version: 0.9.3` on `Linux volt-stgrie 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`.

The (pretty much minimally reproducing) test case is 

    #[cfg(test)]
    mod tests {
        #[test]
        fn signal_reg() {
            let fg = std::sync::Arc::new(std::sync::atomic::AtomicBool::default());
            let si = signal_hook::flag::register(signal_hook::SIGQUIT, fg.clone());
            assert!(si.is_ok());
            // test if atomic is unset before signal
            assert!(!fg.load(std::sync::atomic::Ordering::Relaxed));
            unsafe { libc::raise(signal_hook::SIGQUIT) };
            // test if atomic was set after signal
            assert!(fg.load(std::sync::atomic::Ordering::Relaxed));
        }
    }

the according project thus uses

    [dev-dependencies]
    signal-hook = "0.1.12"
    libc = "0.2.66"

(the only other relevant `cargo.toml` entry is probably `edition = "2018"`)

As stated already, `cargo test` outputs

>    Compiling tarp-sig-test v0.1.0 (/home/stefan/projects/tarp-sig-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running target/debug/deps/tarp_sig_test-1dba07752f9cbea9
>    
>    running 1 test
>    test tests::signal_reg ... ok
>    
>    test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
>    
>    Doc-tests tarp-sig-test
>    
>    running 0 tests
>    
>    test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

while `cargo tarpaulin -v` yields

>    [INFO tarpaulin] Running Tarpaulin
>    [INFO tarpaulin] Building project
>        Finished dev [unoptimized + debuginfo] target(s) in 0.04s
>    [DEBUG tarpaulin] Processing Target(lib)
>    [INFO tarpaulin] Launching test
>    [INFO tarpaulin] running /home/stefan/projects/tarp-sig-test/target/debug/deps/tarp_sig_test-4713170db2ac1871
>    
>    running 1 test
>    test tests::signal_reg ... FAILED
>    
>    failures:
>    
>    ---- tests::signal_reg stdout ----
>    thread 'tests::signal_reg' panicked at 'assertion failed: fg.load(std::sync::atomic::Ordering::Relaxed)', src/lib.rs:14:9
>    stack backtrace:
>       0: backtrace::backtrace::libunwind::trace
>                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
>       1: backtrace::backtrace::trace_unsynchronized
>                 at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
>       2: std::sys_common::backtrace::_print
>                 at src/libstd/sys_common/backtrace.rs:47
>       3: std::sys_common::backtrace::print
>                 at src/libstd/sys_common/backtrace.rs:36
>       4: std::panicking::default_hook::{{closure}}
>                 at src/libstd/panicking.rs:200
>       5: std::panicking::default_hook
>                 at src/libstd/panicking.rs:211
>       6: std::panicking::rust_panic_with_hook
>                 at src/libstd/panicking.rs:477
>       7: std::panicking::begin_panic
>                 at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
>       8: tarp_sig_test::tests::signal_reg
>                 at src/lib.rs:14
>       9: tarp_sig_test::tests::signal_reg::{{closure}}
>                 at src/lib.rs:4
>      10: core::ops::function::FnOnce::call_once
>                 at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/ops/function.rs:231
>      11: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
>                 at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
>      12: __rust_maybe_catch_panic
>                 at src/libpanic_unwind/lib.rs:82
>      13: std::panicking::try
>                 at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:275
>      14: std::panic::catch_unwind
>                 at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panic.rs:394
>      15: test::run_test::run_test_inner::{{closure}}
>                 at src/libtest/lib.rs:1466
>    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
>    
>    
>    failures:
>        tests::signal_reg
>    
>    test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
>    
>    [INFO tarpaulin] Coverage Results:
>    || Uncovered Lines:
>    || Tested/Total Lines:
>    || src/lib.rs: 7/7 +0%
>    || 
>    100.00% coverage, 7/7 lines covered, +0% change in coverage
>    Error: "Test failed during run"

I'm not terribly familiar with the inner workings of Tarpaulin, but I would speculate that the breakpoint insertions (or whatever else tarpaulin actually does to the code in order to measure covered lines) don't work well with Unix signal handling code or maybe screw up the atomic ordering.

**Comment by xd009642** [comment]
So breakpoints emit unix signals and as such tarpaulin captures signals itself so you're signals are almost definitely getting taken by tarpaulin. There's a forward-signals option I believe that helps users with this use case but I think it's only been tested with user signals. It might forward any unrecognised signals but I'm not sure of that at all, it's been a while since I've touched that part of the code

**Comment by sgvolt** [comment]
Oh, I must have overlooked that flag. Indeed, using `cargo tarpaulin -f` all tests succeed as expected for my use case. Is there a strong reason for not forwarding signals that are not used by tarpaulin by default, though?

**Comment by xd009642** [comment]
Well because of the breakpoints tarpaulin shouldn't forward everything and unexpected signals may be the result of an error internally (though that mainly counts for things like sigill, sigsegv etc). I'd have to figure out if it could impact other users projects first before making it a default.

**Comment by sgvolt** [comment]
That makes sense. Even if the behaviour remains as-is it would be neat to at least have a list of definitely unavailable signals in the description of the `-f/--forward` flag. And maybe a mention in the documentation of how tarpaulin behaves with Unix signals by default, so that it does not need to be inverse-inferred from the forward flag description.

**Comment by xd009642** [comment]
So I've just came back to this and added some text to the readme, it will show up on next release:

```
### Note on tests using signals

If your tests or application make use of unix signals they may not work with
tarpaulin. This is because tarpaulin relies on the sigtrap signal to catch when
the instrumentation points are hit. The `--forward` option results in 
forwarding the signals from process stops not caused by SIGSTOP, SIGSEGV or 
SIGILL to the test binary.
```

If that's clear enough let me know and I'll close the issue :+1:

**Comment by sgvolt** [comment]
Looks good! Thanks for clarifying this :)
