### ISSUE TITLE
Use latest Rust in the Docker image

### ISSUE THREAD

**Issue by EFanZh** [xd009642/tarpaulin#308]
Rust 1.40 has been released lately, and I have used some of its features. But it seems the latest Tarpaulin Docker image still uses old Rust version. Could you update the Docker image to use the latest Rust toolchain?

**Comment by xd009642** [comment]
So I do use the latest rust it just takes a new commit to be pushed to develop or master for a new image to be built. I've manually triggered a rebuild of the latest images though so they should move to 1.40.0 once docker hub finishes building (caching allowing).
