### ISSUE TITLE
Segfault during test, in Docker (musl)

### ISSUE THREAD

**Issue by Ploppz** [xd009642/tarpaulin#314]
Running tarpaulin in a docker container:
`Error: "Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests"`

It's my own docker image:
```
FROM ekidd/rust-musl-builder:latest

USER root

RUN apt-get update && \
    apt-get install -y python3 python3-pip
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

USER rust

RUN pip3 install --upgrade --user awscli
ENV PATH="/home/rust/.local/bin:${PATH}"

COPY --chown=rust credentials /home/rust/.aws/credentials

RUN cargo install cargo-tarpaulin

RUN mkdir -p /home/rust/.cargo/git /home/rust/.cargo/registry /home/rust/src/target
```
and container is run with `docker run --security-opt seccomp=unconfined -it -v "$(pwd):/home/rust/src" my-rust-musl`

**Comment by Ploppz** [comment]
I managed to reproduce it in an open-source crate:
https://github.com/Ploppz/s3-upload/tree/tarpaulin

Run `./reproduce-error.sh`, which will build docker images and run docker-compose. docker-compose is needed just because that particular library requires `minio` running while testing. It did not reproduce the error in every run I made locally. For some reason, just running the `docker-compose up` command alone (after building the images of course)  reproduced it every time.

The `rust-musl-tarpaulin` image found in that branch builds on [rust-musl-builder](https://hub.docker.com/r/ekidd/rust-musl-builder), which uses the musl-gcc compiler to make a completely static build.
Could the use of musl-gcc be the reason for the segfault?

Hope this helps to catch the bug @xd009642. Let me know if you can't reproduce it.

**Comment by xd009642** [comment]
Musl could be the issue, I'll start working on this tonight

**Comment by xd009642** [comment]
So I've been doing some work to simplify tarpaulins dependencies and removed cargo from the project. I tried using your `ekidd/rust-musl-builder:latest` and install tarpaulin in it and some rust projects and they worked so if you could test again and let me know if the latest version now works on musl for you that would be great :smile:

**Comment by xd009642** [comment]
I'm just going to close this as inactive, if the issue persists feel free to reopen this issue
