### ISSUE TITLE
Generate code coverage data per test

### ISSUE THREAD

**Issue by ligurio** [xd009642/tarpaulin#325]
Hello!

Is it possible to generate code coverage per test with tarpaulin?

**Comment by xd009642** [comment]
`cargo tarpaulin -- test_name` would only run that test. It would be up to you to handle saving different reports etc.

**Comment by xd009642** [comment]
Did this solve the issue? If so just close it ☺️

**Comment by ligurio** [comment]
> Did this solve the issue? If so just close it ☺️

Yeah, thanks for answer :)
