### ISSUE TITLE
Add Support for Multi-Feature Crates

### ISSUE THREAD

**Issue by Alexhuszagh** [xd009642/tarpaulin#329]
I maintain a crate that has a feature "correct", which implements a slow, but correct algorithm. When "correct" is not present, it uses a fast, but lossy algorithm that is generally quite close. As a result, the two features have a lot of conditionally-compiled code, with ~2,000 lines solely for the lossy algorithm, and ~4,000 lines solely for the correct algorithm. What this means is code coverage is quite low for any singular test, even though my unittests cover both cases: with the presence or absence of the feature.

It would be nice therefore to have 1 of 2 tools to simplify this: either, allow the user to provide a list of features for each build, and tarpaulin runs coverage analysis on all of them, merging the result into a single report, or allow us to run an analysis merging with a previous report.

A sample use would be as follows:

```bash
cargo tarpaulin --feature-list=" a b a,b"
```
In this case, the features would be split on whitespace, producing the following: ["", "a", "b", "a,b"]. Each of these would be tested and then the combined coverage would be reported.

**Comment by xd009642** [comment]
I've got another potential solution to this using a toml file to store all the coverage settings for each run. Just because a variety of people want to merge reports for different reasons. I'll try to start on it this week

**Comment by pksunkara** [comment]
I have been trying to set up tarpaulin on https://github.com/clap-rs/clap but it looks it's not running all the tests I want. I can't even figure out what's happening because I am on a mac (running it in docker is not working) and there's no documentation online on the options at all. My best guess is this issue.

**Comment by xd009642** [comment]
@pksunkara So the documentation on the options is meant to be fully contained within the help text, you can check that in `main.rs` and let me know if there is anything unclear and I'll attempt to improve it. If you want to open a new issue I can support you in getting tarpaulin running as desired for clap

**Comment by xd009642** [comment]
@Alexhuszagh so if you have a look in the latest develop you'll see there's now a config file section https://github.com/xd009642/tarpaulin/tree/develop#config-file which adds support for this feature. So feel free to try it out before I do my next release the extra set of eyes on the readme and ergonomics of it can always help. But I think this should solve your use case nicely :smile:

**Comment by xd009642** [comment]
Just cause I'm posting this in other issues I'll close this one and any feedback can go here https://github.com/xd009642/tarpaulin/issues/350

**Comment by Alexhuszagh** [comment]
Thank you, this is perfect. Above and beyond what I had initially hoped for.
