### ISSUE TITLE
Exclude code in #[test] functions

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#33]
Or maybe it is being excluded and code refactored from test functions under `#[cfg(test)]` aren't being excluded.

**Comment by xd009642** [comment]
Currently code from tests is included in coverage. I know there are differences in opinion with this but I think it's the most sensible default option as tests may contain logic. But I do want to eventually exclude them, though this is linked to my planned improvements to implement #16 and #17, and I'm not planning on working on any serious enhancements until the current bugs are all closed.

So in short it's on the list it's just a bit lower down than some other things!

**Comment by xd009642** [comment]
Just letting you know this is now implemented in e540a20d3341024d998141b83bdb86c59f3925a4 and enabled via the --ignore-tests flag. It'll be in the next release which should hopefully be out before the end of the week :+1:

**Comment by mathstuf** [comment]
Thanks! Looking forward to it :) .

**Comment by mathstuf** [comment]
Testing this, code in a non-inline module which is `#[cfg(test)]` is still included. Not sure about inline modules yet.

**Comment by xd009642** [comment]
Really!? I tested this situation on my own machine and it excluded it. Maybe I introduced something that broke it.

Testing it now. I don't suppose you have a link to the project you tried it on I can use to check it with?

**Comment by xd009642** [comment]
So running on tarpaulin itself (meta I know). With the --ignore-tests option enabled none of the lines in the `#[cfg(test)]` module are included in the coverage results. Could you show me an example of this going wrong?

**Comment by mathstuf** [comment]
I noticed it with the git-workarea crate. `test.rs` should be 0/0, but I saw 0/7 or 7/7 (I forget which).

**Comment by mathstuf** [comment]
My numbers were off, but `src/test.rs` is used as `#[cfg(test)] mod test;` line.

```
test result: ok. 22 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Coverage Results
src/error.rs: 0/5
src/git.rs: 65/90
src/prepare.rs: 221/296
src/test.rs: 48/66

73.09% coverage, 334/457 lines covered
Tarpaulin finished
```

**Comment by xd009642** [comment]
Ah I know what the issue is. It parses each file separately... So it parses test.rs without looking at the wider context provided by main.rs. Issue reopened!

**Comment by xd009642** [comment]
Fixed so you'll see this in the next release (whenever that may be)! Tested on rust-git-workarea can can confirm it now works as expected :smile:

**Comment by mathstuf** [comment]
Thanks!
