### ISSUE TITLE
Travis install script warning

### ISSUE THREAD

**Issue by michaelmior** [xd009642/tarpaulin#335]
I see that the Travis install script produces a warning that it's not recommended. However, it's still listed in the README as a faster option. So it seems to be both recommended and not recommended. Clarifying this would be helpful.

**Comment by xd009642** [comment]
I'll remove that warning, it was previously recommended against as with proc macro not stabilised previously you could only run tarpaulin with the nightly version it was compiled with

**Comment by xd009642** [comment]
I've amended the warning to say that it's not recommended for if you use nightly features and to use docker instead. Hopefully that should clear up any confusion

**Comment by michaelmior** [comment]
Thanks!
