### ISSUE TITLE
tarpaulin in clap

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#336]
@pksunkara I tried tarpaulin on slack and got these results (no tests ignored)

```
|| Tested/Total Lines:
|| clap-test.rs: 39/40
|| clap_derive/examples/skip.rs: 0/2
|| clap_derive/src/derives/attrs.rs: 0/287
|| clap_derive/src/derives/parse.rs: 0/90
|| clap_derive/src/derives/spanned.rs: 0/30
|| clap_derive/src/derives/ty.rs: 0/13
|| clap_derive/tests/options.rs: 0/2
|| clap_derive/tests/skip.rs: 0/2
|| clap_derive/tests/special_types.rs: 0/2
|| clap_derive/tests/ui/skip_flatten.rs: 0/1
|| clap_derive/tests/ui/skip_subcommand.rs: 0/1
|| src/build/app/mod.rs: 299/563
|| src/build/app/settings.rs: 109/111
|| src/build/arg/mod.rs: 433/629
|| src/build/arg/settings.rs: 60/61
|| src/build/arg_group.rs: 74/117
|| src/build/usage_parser.rs: 953/1018
|| src/lib.rs: 0/2
|| src/macros.rs: 33/38
|| src/mkeymap.rs: 95/144
|| src/output/fmt.rs: 35/52
|| src/output/help.rs: 440/638
|| src/output/usage.rs: 195/259
|| src/parse/arg_matcher.rs: 57/73
|| src/parse/errors.rs: 95/189
|| src/parse/features/suggestions.rs: 29/29
|| src/parse/matches/arg_matches.rs: 84/97
|| src/parse/matches/matched_arg.rs: 7/7
|| src/parse/parser.rs: 604/886
|| src/parse/validator.rs: 258/407
|| src/util/fnv.rs: 12/12
|| src/util/graph.rs: 10/20
|| src/util/map.rs: 0/10
|| src/util/osstringext.rs: 35/40
|| src/util/strext.rs: 0/5
|| tests/app_settings.rs: 555/561
|| tests/arg_aliases.rs: 92/92
|| tests/borrowed.rs: 9/9
|| tests/conflicts.rs: 67/67
|| tests/default_vals.rs: 285/285
|| tests/delimiters.rs: 71/71
|| tests/derive_order.rs: 90/90
|| tests/env.rs: 132/136
|| tests/flags.rs: 70/75
|| tests/global_args.rs: 8/8
|| tests/groups.rs: 105/105
|| tests/help.rs: 343/343
|| tests/hidden_args.rs: 40/40
|| tests/indices.rs: 88/88
|| tests/macros.rs: 61/61
|| tests/multiple_occurrences.rs: 75/75
|| tests/multiple_values.rs: 515/515
|| tests/opts.rs: 267/272
|| tests/positionals.rs: 140/147
|| tests/posix_compatible.rs: 208/208
|| tests/possible_values.rs: 86/89
|| tests/propagate_globals.rs: 68/68
|| tests/require.rs: 323/323
|| tests/subcommands.rs: 95/95
|| tests/template_help.rs: 28/28
|| tests/tests.rs: 129/147
|| tests/unique_args.rs: 18/18
|| tests/utf8.rs: 180/186
|| tests/version-numbers.rs: 4/4
|| tests/version.rs: 30/30
|| 
80.47% coverage, 8138/10113 lines covered
```

**Comment by pksunkara** [comment]
This was the initial commit. https://github.com/clap-rs/clap/pull/1648/commits/80a42016874b793af06cf18babecc316dda447ab.
https://travis-ci.org/clap-rs/clap/jobs/644553817 is the pr job.
https://travis-ci.org/clap-rs/clap/jobs/644553773 is the push job.

I got the same result as you in both the jobs.

I have 2 main concerns here:

* Looks like clap_derive tests are not working. I thought `--all` was default from what I read, but I will try `--workspace`. Or maybe it's because they are macros.
* I got `[WARN tarpaulin] Failed to collect git info: failed to get branch name: reference 'HEAD' is neither a local nor a remote branch.; class=Invalid (3)` on both the jobs in travis.

I have also other minor concerns:

* What's happening with doc-tests? I assume the integration and unit tests are the only ones being tested.
* What's happening with examples?
* https://github.com/xd009642/tarpaulin/issues/105 is something I would love as a maintainer of clap which makes it easy for people making CLIs

**Comment by pksunkara** [comment]
https://travis-ci.org/clap-rs/clap/jobs/644668654 is the new job where I ran with `--workspace --features "yaml unstable"`. It looks like the `clap_derive` test were now run.

But we have some tests running using https://crates.io/crates/trybuild which are failing. Most of the macros crates are using these tests now.

**Comment by xd009642** [comment]
So for options that also exist in cargo test there should be parity.  so `--all-features` is an option and `--workspace` tests all packages in the workspace. Also just like `cargo test` integration and unit tests are done by default. 

I used to filter out the examples folder by default, but there's now a run type for examples which can be used to see how much of your code is being covered by your projects examples so if you want to exclude them from results use `--exclude-files examples/*` or `*/examples/*` if there are examples in packages in the workspace.

For coveralls, it shouldn't be an issue as there's the travis job ID for coveralls, populating as much of the git information available for the coveralls request json is useful for other CI services and people with private servers.

**Comment by xd009642** [comment]
And I'll look into the tests that fail in tarpaulin and see what's up with that :smile:

**Comment by pksunkara** [comment]
> I used to filter out the examples folder by default, but there's now a run type for examples which can be used to see how much of your code is being covered by your projects examples so if you want to exclude them from results use `--exclude-files examples/*` or `*/examples/*` if there are examples in packages in the workspace.

Sorry, I don't get it. Are you saying `examples` are being run by default?

And thanks for checking into trybuild.

**Comment by xd009642** [comment]
they're not run by default but the source files are included in the report

**Comment by pksunkara** [comment]
Closing this in favor of #326
