### ISSUE TITLE
Incremental coverage

### ISSUE THREAD

**Issue by Luro02** [xd009642/tarpaulin#358]
Running `cargo tarpaulin` is quite slow for bigger projects. On my computer I have to wait about 2-3mins for the coverage (including doctests), which can be quite annoying if only some minor things were changed and one wants to see the coverage changes before applying it to the rest of the project.

The rust compiler uses something called incremental compilation, where the compiler only recompiles files that have changed since the last compilation.

`cargo tarpaulin` could do something similar by keeping a list of all hashed src/test/example/bench files and then it would only run tests for files that changed since the last coverage run.

I think this could really improve the performance, especially if only a few files/lines were changed.

**Comment by xd009642** [comment]
Well it's a bit harder than that as you need to also think about what modules are pulled in by each test module. Also, it would slow down CI runs where the information from the last run won't be available to you. I think I'd have to see some evidence on how this could speed up CI runs before thinking of implementing as that's the vast majority of tarpaulin's use case
