### ISSUE TITLE
How to use the pre-built binaries with travis?

### ISSUE THREAD

**Issue by najamelan** [xd009642/tarpaulin#359]
I was hoping to use cargo tarpaulin on travis, in the standard linux configuration which is travis-ci-opal-xenial-1553530491-f909ac5. The readme says:

> Alternative, there is the travis-install shell script will install the latest tagged release built on travis to your travis instance and significantly speeds up the travis builds. You can install via that script using bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh).

It never finds `libssl.so.1.1`. I tried installing the packages `libssl-dev` and `openssl`, but it won't find the dynamic lib...

**Comment by xd009642** [comment]
Could you try with `dist: trusty` and `libssl-dev`? I remember having some issues with the other ubuntu versions available on travis

**Comment by najamelan** [comment]
So I ran some more tests: 
- trusty: The issue is [the same](https://travis-ci.org/najamelan/async_executors/builds/656947832#L746). [Config](https://travis-ci.org/najamelan/async_executors/jobs/656947833/config)
- bionic: It works! by installing libssl-dev

I will file a PR to update the readme.

**Comment by xd009642** [comment]
So the minimum recommended travis setup has `sudo: required` I wouldn't expect it to fix anything but I also wouldn't expect coverage to work without it because you can't disable ASLR

**Comment by najamelan** [comment]
Ok, I'll double check with `sudo: required` just in case.

**Comment by najamelan** [comment]
trusty: also fails with sudo, but is version: libssl-dev amd64 1.0.1f-1ubuntu2.27, so it's just a not 1.1 as tarpaulin has been compiled against I think.
xenial: fails, libssl version: 1.0.2g-1ubuntu4.15

bionic has libssl-dev amd64 1.1.1-1ubuntu2.1~18.04.5. Bionic does not need `sudo: required`

An added nuissance is that by putting it as an inline script in the travis yaml:
```yaml
      after_success: |
        bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
        cargo tarpaulin --features "spawn_handle async_std tokio_tp tokio_ct localpool threadpool" --exclude-files src/bindgen.rs --out Xml
        bash <(curl -s https://codecov.io/bash)
```
This will report the built successful even if the codecov script concludes with "no coverage data found". Probably needs some `set -e` for fast failure.

**Comment by xd009642** [comment]
@najamelan does the PR merged solve this issue? Or are there more documentation changes that would help?

**Comment by najamelan** [comment]
If I were you, I would create CI configurations that actually run on travis, which would prove that they work and then point to them in the readme, but this already is definitely great improvement. Thanks for merging.
