### ISSUE TITLE
Error on doctest

### ISSUE THREAD

**Issue by buttercrab** [xd009642/tarpaulin#360]
I am developing a [project](https://github.com/buttercrab/hyeo-ung-lang).
When I tried doctest, an [error](https://travis-ci.com/buttercrab/hyeo-ung-lang/jobs/292715337) came out:
`error[1m: the option `Z` is only accepted on the nightly compiler`

**Comment by xd009642** [comment]
That's because to keep the doctest executables around tarpaulin uses a nightly feature persist-doctests. This means doctest coverage is currently a nightly only feature. 

Tracking issue in the rust compiler: https://github.com/rust-lang/rust/issues/56925

**Comment by buttercrab** [comment]
Oh, I solved it. Thanks!
