### ISSUE TITLE
tarpaulin panic when building project

### ISSUE THREAD

**Issue by buttercrab** [xd009642/tarpaulin#365]
The project itself builds with no problem and passes all tests,
but tarpaulin panics when building project.

> `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/util/canonical_url.rs:42:13`

[Travis CI](https://travis-ci.com/buttercrab/hyeo-ung-lang/jobs/295188421#L1011)

**Comment by jmagnuson** [comment]
I think this is a duplicate of #319. Try using tarpaulin `0.9.3` and see if the issue persists.

**Comment by xd009642** [comment]
@buttercrab I'm working on a moderately big change that will hopefully solve all build related issues. Just ironing out the last few bugs :+1:

**Comment by holmesmr** [comment]
As an aside, Cargo 0.43.0 was tagged today, which does include the upstream fix for this issue.

**Comment by buttercrab** [comment]
@jmagnuson Sorry I'm late. I've tried `0.9.3` and I found parse error. 
> `Error: "Failed to compile tests! Error: failed to parse lock file at: /home/travis/build/buttercrab/hyeo-ung-lang/Cargo.lock"`
[Travis CI](https://travis-ci.com/github/buttercrab/hyeo-ung-lang/jobs/297628370#L1069)

**Comment by buttercrab** [comment]
I found that during test, it prints logs to stdout. Maybe printing to stdout caused the problem.

**Comment by buttercrab** [comment]
@holmesmr How can I use that version? It's still in [0.42.0](https://github.com/xd009642/tarpaulin/blob/master/Cargo.toml#L22)

**Comment by buttercrab** [comment]
Great! It works!
