### ISSUE TITLE
ssh tools not found

### ISSUE THREAD

**Issue by hellojukay** [xd009642/tarpaulin#371]
```ｓｈｅll
/bin/bash: line 87: ssh-agent: command not found
$ ssh-add <(echo "$PRIVATE_KEY")
/bin/bash: line 89: ssh-add: command not found
```
should not delete ssh tools

**Comment by xd009642** [comment]
I'm sorry but I don't understand this issue and how it relates to tarpaulin? Can you elaborate

**Comment by hellojukay** [comment]
tarpaulin image in ci pipeline  . private git auth need ssh tools.

**Comment by xd009642** [comment]
What image? The docker image?

**Comment by hellojukay** [comment]
@xd009642 yes,  the latest tarpaulin image

**Comment by xd009642** [comment]
okay the develop images are now back on the rust image, though generally it's bad practice to move ssh keys into docker images I think a better solution is to vendor the dependencies in the local directory so when you run tarpaulin and mount the volume you can run with the `--offline` flag to avoid needing to download the dependencies again

**Comment by hellojukay** [comment]
> hough generally it's bad practice to move ssh keys into docker images I think a better solution is to vendor the dependencies in the local directory 

yes, but ssh tools should in container.  private key was injected when pipeline is running, not save in  image docker image.

**Comment by xd009642** [comment]
Yes but a better approach is to share the host ssh-agent with the docker image to avoid mistakes. For docker-compose:

```
    volumes:
        - $SSH_AUTH_SOCK:/ssh-agent # Forward local machine SSH key to docker
    environment:
        SSH_AUTH_SOCK: /ssh-agent
```

Either way I've added it back in on the develop branch for ease of use, I don't think doubling the size of the docker image affects that many people
