### ISSUE TITLE
Count lines that are comment

### ISSUE THREAD

**Issue by buttercrab** [xd009642/tarpaulin#374]
As you can see in [this report](https://codecov.io/gh/buttercrab/hyeo-ung-lang/src/f83e43ab3130fce12a3e7eb49e242228c476428b/src/parse.rs#L8), from line 8 to 16, it is checked as green even though it is a comment. (I am using in nightly version)

I think it shouldn't counted in any way. Is this a bug or meant to be?

**Comment by xd009642** [comment]
It's a bug and I think it might be related to the doc comments - I think I need more sophisticated handling for finding instrumentation points in those cases.

**Comment by xd009642** [comment]
I might have a solution I'm just testing it out now. If it works I'll merge it into develop later today or tomorrow

**Comment by xd009642** [comment]
Yeah looks like it all works, I've pushed it on develop if you want to try it out before my next release. Ran it on your project and checked all the doc comments and didn't see any comments marked as coverable lines

**Comment by xd009642** [comment]
I'm pushing out a release now! If the issue is still there let me know otherwise I'll close this issue in a few days if I don't hear anything. Though feel free to reopen it or raise a new one if I close it and the issue persists :+1:

**Comment by buttercrab** [comment]
Great!
