### ISSUE TITLE
Option to disable hit counts for line coverage

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#38]
For long tests and people who don't care about how many times a line is hit disabling the hit count could yield significant performance improvements. This would involve disabling a breakpoint after it's hit and counted.

A fairly easy change I'm picturing this as a command line option called something like `--no-count`.

**Comment by xd009642** [comment]
For reference this ran on zxcvbn-rs a project with <60% test coverage and not a large number of lines hit >1 got these results using time on my machine.

```
cargo tarpaulin -v --skip-clean
real	0m55.135s
user	0m54.829s
sys	0m0.176s

cargo tarpaulin -v --skip-clean --no-count
real	0m54.559s
user	0m54.269s
sys	0m0.158s
```

Hit percentage is consistent between the two and gains should be much larger for larger projects.

**Comment by hawkw** [comment]
This would be excellent, thank you!

**Comment by xd009642** [comment]
It's in and works in master branch so you can install from git directly. I probably won't publish another release until my I have another feature in progress ready to merge which should remove some unnecessary instrumentation points which might add another slight improvement :+1:
