### ISSUE TITLE
Html diff fails if a source file disappears

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#382]
If a source file disappears between two Html report generations, the attempt to find the now-deleted files fails and causes the new report to not be created.

**Comment by mathstuf** [comment]
Working on a fix.

**Comment by mathstuf** [comment]
Fixed by #384 (why did autoclose fail?)

**Comment by xd009642** [comment]
Autoclose only triggers on merge to master (not sure if I can change that in settings)

**Comment by mathstuf** [comment]
Ah. I think you need to set the default branch to `develop` to fix that.
