### ISSUE TITLE
Coverage of unreachable lines changes with ;

### ISSUE THREAD

**Issue by malbarbo** [xd009642/tarpaulin#39]
```rust
pub fn f() {
    panic!()
}

#[test]
#[should_panic]
fn t() {
    f();
    unreachable!() // adding make this line covered
}
```

The `unreachable` line is marked as not covered if `;` is omitted and marked as covered it `;` is added.

**Comment by xd009642** [comment]
Interesting, it seems removing the semi-colon changes how the AST represents the expression. I'll have a look at this some time this week :+1:

**Comment by xd009642** [comment]
Fixed and you'll see it in the next release (unless you're feeling adventurous and want to try it out early :wink: )
