### ISSUE TITLE
Tests that try to load files no longer pass with new tarpaulin container

### ISSUE THREAD

**Issue by bfjelds** [xd009642/tarpaulin#392]
I have some tests that load files using code like this:

```
let file = "../path/file.txt"
let file_path = fs::canonicalize(PathBuf::from(file))
     .expect(&format!("unable to find test file: {}", file))
     .to_str()
     .expect("unable to convert PathBuf to &str")
     .to_string();
let contents = fs::read_to_string(file_path);
```

The tests pass using `cargo test` and previously passed using `cargo tarpaulin` ... but after updating to a new tarpaulin container, the tests now fail saying that the files do not exist.

**Comment by bfjelds** [comment]
It seems as though **std::env::current_dir()** differs between `cargo test` and `cargo tarpaulin` .

My project has several Cargo.toml files, with one at the repo root defining the workspace members (where the other Cargo.toml files are).

When I start the tarpaulin container, /volume is set to the path containing my workspace Cargo.toml (-v "${PWD}:/volume").

* for `cargo test`, **std::env::current_dir()** == <path-to-each-test's-cargo-toml-folder>
* for `cargo tarpaulin`, **std::env::current_dir()** == /volume

**Comment by bfjelds** [comment]
Here's a simple project that demonstrates the issue: https://github.com/bfjelds/tarpaulin-test

**Comment by xd009642** [comment]
Ah that's awesome thanks, I've managed to track down the issue and am part way through a fix. I should hopefully have something to try out by the end of tomorrow and aiming for a release on Friday with a patch in

**Comment by xd009642** [comment]
If you check develop there's a fix there that worked on your test project :+1:

**Comment by bfjelds** [comment]
thanks!!! both for initially creating this awesome tool and for being so responsive!!!  i will try out the new bits as soon as i can.

**Comment by bfjelds** [comment]
my tests passed with this:

xd009642/tarpaulin:develop
DIGEST:sha256:83f7f3997254fc7824e605f023d161352bcd002cf23f0fdd291658e4bdb731ae

thanks for fixing this so quickly!!

**Comment by pksunkara** [comment]
Yup, the develop branch fixed this issue. Could you please make a quick release?

**Comment by xd009642** [comment]
I can make a release tonight when I'm on my laptop
