### ISSUE TITLE
Don't collect coverage for source in hidden folders or dependencies

### ISSUE THREAD

**Issue by janriemer** [xd009642/tarpaulin#397]
Hello there @xd009642,
## Problem
When trying to set up tarpaulin in gitlab-ci, I've encountered the issue that **tarpaulin includes the source lines of dependencies into the final coverage report** and so my coverage was obviously pretty low (see link to logs below). :laughing:
The setup is as follows:
1. The project uses a dependency from _a remote git repository via ssh_
2. In order to cache the tarpaulin bin between runs, the env var **CARGO_HOME is set to ./.cargo** (so .cargo lives in the crate's root folder and can be cached by Gitlab runner)
2.1 The dependency from the remote git repo seems to be checked out into .cargo/git/... when building the crate (so far so good :smiley_cat:)
3. Now tarpaulin runs the tests and collects coverage from both the crate :warning: **and the git dependency**

So I am wondering, why it also collects coverage from the git dependency. It would mean that tarpaulin also looks into **hidden folders** for source files to collect coverage from.
I would expect tarpaulin not to look into hidden folders for source files not to mention _crate dependencies_, but I am probably missing something here.

What do you think? Can you clarify the behaviour here?

## Workaround
I could fix this issue by excluding .cargo when running tarpaulin, so:
```sh
cargo tarpaulin -v --exclude-files .cargo
```

## Logs
Here is the log of the ci pipeline with the "broken" coverage report...:
https://gitlab.com/janriemer/ci-test/-/jobs/510075263
...and the corresponding gitlab-ci.yml:
https://gitlab.com/janriemer/ci-test/-/blob/ba373962e6af211a75228c7483837399e9b7e5c6/.gitlab-ci.yml

Here is the log of the ci pipeline with the "fixed" coverage report...:
https://gitlab.com/janriemer/ci-test/-/jobs/510675924
...and the patch/diff in the gitlab-ci.yml:
https://gitlab.com/janriemer/ci-test/-/commit/b68f2553bac22e2d0aab4f8c6828b7d62335bcdd

----------------------------------
Last, but not least I want to say thank you for this really cool tool! :kissing_heart:  I really appreciate your effort! All in all, it was very easy to set up. :nerd_face:

**Comment by xd009642** [comment]
Firstly thanks for the detailed bug report! And for coverage tarpaulin filters out excluded files, files in the target folder and files not in the project root. I honestly didn't expect a `.cargo` to be in the project root as caches in other CI services like travis typically know where to look to form the cache so you just leave CARGO_HOME as default. 

I'll work on a fix and let you know when it's pushed to the develop branch as it would be helpful to double check it fixes your issue before the next release :+1:

**Comment by xd009642** [comment]
Actually there's now a feature branch `ignore_dot_cargo` that might work, if you want to try that out and let me know, otherwise I'll continue work tomorrow (because there's some tidy up to do)

**Comment by xd009642** [comment]
I tested locally and saw it fixed the issue so you can now find this in the develop branch, please let me know if it works for you :smile:

**Comment by janriemer** [comment]
Wow, thank you for this very quick response and fix! :rocket: 

I've tested it in a local docker container and it works like a charm! :sparkles: 

You can close this issue. Thanks again! :kissing_heart:

**Comment by xd009642** [comment]
Cool I'm also doing a new release tonight so this will be available via cargo install before 00:00 GMT :+1:
