### ISSUE TITLE
This should propagate the environment flags set in the launching shell

### ISSUE THREAD

**Issue by svenstaro** [xd009642/tarpaulin#4]
So I have this web application which needs a bunch of environment variables even for testing. I think this tool should propagate those because currently it doesn't and so I can't test my app with it.

**Comment by xd009642** [comment]
Hi, I agree this is a desired behaviour. I've mocked up a project where tarpaulin fails due to this issue to test with and I'll let you know when I believe this is resolved.

**Comment by svenstaro** [comment]
Cool, looking forward to that. Thanks.

**Comment by xd009642** [comment]
I'm currently publishing 0.3.2, once it's up you can test it and let me know if it works for you. It works on my setup correctly so it should be good to go. Let me know how it works

**Comment by svenstaro** [comment]
Seems fine now, thanks.
