### ISSUE TITLE
Add lines of unused generic functions

### ISSUE THREAD

**Issue by malbarbo** [xd009642/tarpaulin#40]
Consider a library that provides generic functions but does not test them. The functions will not be considered and the coverage result will be misleading. For example

```rust
pub fn sum<I: Iterator<Item = u32>>(iter: I) -> u32 {
    let mut s = 0;
    for x in iter {
        s += x;
    }
    s
}

#[test]
fn some_test() {
}
```

reports 100% coverage, but should be 0%!

It seems that it is difficult to generate debugging information for code that are not generated! (See https://github.com/rust-lang/rust/issues/39293) I think that tarpaulin can solve this by adding lines using the parsed code.

Besides branch coverage, this is the biggest issue I have with rust coverage.

@xd009642 I would like to thank you for working in this great tool!

**Comment by xd009642** [comment]
Hadn't considered this, adding this to my todo list :+1:. And you're welcome I enjoy working on it :smile: 

RE branch coverage that's my next big feature. Once I close a few of the issues currently open it will be what my time is spent doing, I'm just working on a fairly flexible design to allow me to extend it to things like MCDC coverage!

**Comment by xd009642** [comment]
Unused generics are now in coverage! You can see this when my next release comes out or if you're eager install tarpaulin from the commit I closed this issue in.

**Comment by malbarbo** [comment]
I found two more cases that are not considered: 

```rust
use std::cmp::Ordering;
use std::fmt::Debug;

pub trait Trait: Debug {
    fn print(&self) {
        println!("{:?}", self);
    }
}

pub struct X<T>(T);

impl<T> X<T> {
    fn cmp(&self, other: &T) -> Ordering
        where T: Ord
    {
        self.0.cmp(other)
    }
}
```

Conceptually `Trait::print` and `X::cmp` are generic functions because they need to be monomorphized.

Another point is that where clauses are marked as uncovered, like in

```rust
#[derive(Debug)]
pub struct Y;

impl Y {
    fn f<T>(&self, x: &T)
        where T: Debug,
              Self: Debug,
    {
        println!("{:?} {:?}", self, x);
    }
}
```

There is a problem with unused inlined functions that I reported in https://github.com/rust-lang/rust/issues/45174

**Comment by xd009642** [comment]
Awesome, these should be easy enough to do (well the traits one might be a bit fiddly). Also, for the `#[inline]` stuff I'll add an attribute rule to sort that out as well

**Comment by xd009642** [comment]
Unused inline functions are now included in coverage! Where clauses and traits still figuring out just to make sure I don't accidentally discount lines that can be covered.

**Comment by xd009642** [comment]
All done, anything else just let me know :smile:
