### ISSUE TITLE
create_command doesn't follow rustup toolchain specification

### ISSUE THREAD

**Issue by AngelOnFira** [xd009642/tarpaulin#404]
https://github.com/xd009642/tarpaulin/blob/02e744e715d2bc2cd327261b03e162ddfb34aa56/src/cargo.rs#L142

The create_command function adds +nightly or +beta to the cargo command. However, if a project is using a toolchain from a locked date through the `rust-toolchain` file, then this command will try and use the wrong toolchain.

For example, on our project, we build a Docker image for CI that installs a specific version of nightly. When we run Tarpaulin we get:

`error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed`

Although `rustup toolchain list` would show that we do have a nightly installed:

`nightly-2020-04-17-x86_64-unknown-linux-gnu`

The full toolchain spec can be found here: https://github.com/rust-lang/rustup#toolchain-specification

**Comment by xd009642** [comment]
Closing this as it's solved by #405
