### ISSUE TITLE
Consider using cargo_metadata instead of cargo crate

### ISSUE THREAD

**Issue by malbarbo** [xd009642/tarpaulin#41]
It take too long to compile cargo. An alternative is to use [cargo_metadata](https://crates.io/crates/cargo_metadata), which offers an api over the `cargo metadata` command.

**Comment by xd009642** [comment]
I use cargo to get more than just metadata, I also use it for building, some interactions with the system linker and also telling me what the test executable names are. Also, I plan on having a flag to enable test coverage for doc tests as some users want it, and cargo has an interface to that functionality (that I need to explore in more detail).

Based on that I don't think this is going to be an issue I'll address but I'm happy to hear if you have any suggestions on getting around all those parts of my cargo usage! I will check cargo and see if I can disable features of the library I don't use to cut down the build times though!

**Comment by xd009642** [comment]
Closing this unless there are any further comments
