### ISSUE TITLE
The code coverage is inaccurate for function return future

### ISSUE THREAD

**Issue by w93163red** [xd009642/tarpaulin#412]
Hi,

Currently,  I am running ~70 tests (cargo test features="xxx" --test-threads=1). But I found that the line coverage does not match the running log. Some lines have been executed but not been marked. Then I just run one test, the line coverage seems correct. 

Under this circumstance,  should I run the test one by one to get the best result or there's other way to bypass it?

![image](https://user-images.githubusercontent.com/7308728/80867979-83db6300-8c65-11ea-9bf7-5893cb13dde0.png)

![image](https://user-images.githubusercontent.com/7308728/80867962-61494a00-8c65-11ea-9eb8-d694af5056f0.png)

**Comment by xd009642** [comment]
I'd personally report the misses in #351 and wait on an update to improve them or tweak the config. It depends on the level of inaccuracy and how much you can tolerate though.

**Comment by w93163red** [comment]
> I'd personally report the misses in #351 and wait on an update to improve them or tweak the config. It depends on the level of inaccuracy and how much you can tolerate though.

My current workaround is to have a script to run each test separately. It is still not accurate, but much accurate than before.

**Comment by xd009642** [comment]
Closing this issue as the llvm coverage backend is now released `--engine llvm` with increased accuracy due to compile time instrumentation instead of runtime
