### ISSUE TITLE
[minor] Outdated Travis configuration

### ISSUE THREAD

**Issue by dbdr** [xd009642/tarpaulin#413]
Tarpalin's example configuration for Travis contains:
```
sudo: required # required for some configurations
```
However, according to [Travis documentation](https://config.travis-ci.com/ref/sudo) the sudo key is deprecated and has no effect.
The [config explorer](https://config.travis-ci.com/explore) also says:
```
[warn] on root: deprecated key: "sudo" (The key `sudo` has no effect anymore.)
```
I think that line should simply be removed from your example.

PS: I initially tried following travis configurations that used kcov under the hood. kcov failed mysteriously with cryptic linking errors. I am much happier to use a rust tool instead, which worked out of the box. Keep up the good work!

**Comment by xd009642** [comment]
Just fixed this on the develop branch :+1:
