### ISSUE TITLE
Export RUSTFLAGS when running tests

### ISSUE THREAD

**Issue by jyn514** [xd009642/tarpaulin#416]
This is not quite a bug and not quite a feature request ... One of my integration tests involves running the binary in a separate process so that if it segfaults I'm able to catch the error instead of the whole test runner crashing immediately. To make this work, I run `cargo build` and then run the resulting binary. Normally this works fine, since running `cargo test` involves building all the dependencies anyway, so at worst building the binary takes a few seconds. However, if I run `cargo-tarpaulin` before running cargo test, then the integration test rebuilds every single dependency (since [tarpaulin sets RUSTFLAGS](https://github.com/xd009642/tarpaulin/blob/02e744e715d2bc2cd327261b03e162ddfb34aa56/src/cargo.rs#L221) and my binary doesn't). As a result, the test times out; see https://gitlab.com/jyn514/rcc/-/jobs/535816510#L158 for an example of this.

If tarpaulin would export RUSTFLAGS, then I could use the cached dependencies instead of having to rebuild the whole thing from scratch.

**Comment by xd009642** [comment]
Hmm interesting I'll have to have a think about the best way to tackle this. Overwriting the rustflags as a change could mess up things for users who run tarpaulin on their local systems... You can check `src/cargo.rs` for how I set the rust flags. If you're building without `--release` the rustflags will be `-C relocation-model=dynamic-no-pic -C link-dead-code -C debuginfo=2`

**Comment by jyn514** [comment]
> Overwriting the rustflags as a change could mess up things for users who run tarpaulin on their local systems

I'd be fine making this opt-in, I understand this is a bit of an edge case. Exporting the flags manually sounds like a good workaround in the meantime, I'll see if that helps. Another thing I could try is telling tarpaulin to ignore those integration tests, not sure if there's already a way to do that.

**Comment by xd009642** [comment]
Any arguments after a `--` go to the test binaries so you can use that to specify what tests to run i.e. `cargo tarpaulin -- my_module`. As those arguments go to the test binary if there's anything to ignore certain tests for them that will work

**Comment by jyn514** [comment]
`--skip` looks like what I want, thank you!

```
$ cargo test -- -h | grep skip
        --skip FILTER   Skip tests whose names contain FILTER (this flag can
                        be used multiple times)
```

**Comment by jyn514** [comment]
Unfortunately `--skip` seems to only apply to unit tests, so that doesn't help. I tried setting RUSTFLAGS myself but it still rebuilt everything: https://gitlab.com/jyn514/rcc/-/jobs/540034388#L165, https://gitlab.com/jyn514/rcc/-/commit/973623a82927a9be11b70c4a1bf2c95f4e031524

**Comment by xd009642** [comment]
So in tarpaulin on develop I've added two args `--print-rust-flags` and `--print-rustdoc-flags`. These will print all possible values for RUSTFLAGS and RUSTDOCFLAGS that you can get given your tarpaulin configuration for the project and CLI args in use (different args can change some flags). 

There is also new macros I added about a month ago so you can do `#[cfg(not(tarpaulin_include))]` on something and it won't be in the binaries tarpaulin builds. Which might also be a good option for you. Check this part of the README for more details https://github.com/xd009642/tarpaulin#ignoring-code-in-files 

If there's anything else you'd like to see to resolve this issue let me know otherwise I'll probably close it after a week or two of nothing (but feel free to reopen if I close it)

**Comment by jyn514** [comment]
I actually stopped using tarpaulin because it was slowing down CI so much ... I'll see if I can try to add it back but this is a busy week for me so feel free to close if you don't hear back.

**Comment by xd009642** [comment]
Fair enough slow CI is definitely a pain. I think using `#[cfg(not(tarpaulin_include))]` on large tests to avoid building them with tarpaulin's flags could potentially help a lot depending on your code. 

Also, bit of future work but once I prototype the idea I describe here https://github.com/xd009642/tarpaulin/issues/516#issuecomment-665938418 if that works tarpaulin should be able to transition to using mostly the same build output as `cargo test`. So you might want to watch that issue.
