### ISSUE TITLE
Annotated report like kcov

### ISSUE THREAD

**Issue by bbigras** [xd009642/tarpaulin#42]
I see on the readme that tarpaulin supports kcov style report? Does that mean stuff like XML or the html one with the annotated code?

**Comment by xd009642** [comment]
It means the xml style report, I should possibly change that to make it more specific. Is the HTML report a feature that would be of interest?

**Comment by bbigras** [comment]
> Is the HTML report a feature that would be of interest?

Not for me. I'll wait for "annotated coverage reports" to be implemented.

**Comment by xd009642** [comment]
Okay, I'm going to close this issue then as everything seems good :+1: (Unless it isn't then let me know and I can reopen it)
