### ISSUE TITLE
JUnit report XML output?

### ISSUE THREAD

**Issue by paulvt** [xd009642/tarpaulin#421]
Some of the larger CI systems such as GitLab and Jenkins support the JUnit report XML format.
Is there an easy way to generate that or convert it from the standard XML output like is done for Cobertura?

For more on the format, see also: https://stackoverflow.com/a/4925847

This feature would nicely supplement already supported CI systems such as Travis/GitHub, Circle CI etc.

**Comment by xd009642** [comment]
So that format doesn't seem to store any coverage information at all? You possibly want to look towards another tool to do this. A quick search on crates.io turned up this https://github.com/CWood1/cargo-junit

**Comment by paulvt** [comment]
Well, indeed. I think I got misled by the GitLab CI docs. It does support Cobertura and just matching a plain regex against the cargo-tarpaulin output, so I'll go with that. Thanks.
