### ISSUE TITLE
No way to run coverage for tests in an example

### ISSUE THREAD

**Issue by CAD97** [xd009642/tarpaulin#424]
Using cargo-tarpaulin 0.12.3, `--run-types Examples` [seems to be](https://github.com/CAD97/sorbus/runs/661849166?check_suite_focus=true) running the binaries produced by `cargo build --examples` (and in my case, failing to collect coverage for them some unknown reason). Instead, I want to run the test executable for the examples, produced by `cargo test --examples`.

Or more specifically, I want all tests run by `cargo test --all-targets` to run, and the examples' tests do not seem to be included in `--run-types Tests`.

**Comment by xd009642** [comment]
I'll have a look some point this week hopefully and see if I can figure it out, hopefully it's just a case of calling cargo wrong in src/cargo.rs

**Comment by CAD97** [comment]
Yep!

https://github.com/xd009642/tarpaulin/blob/504acb12e0e4a0dd5c7a9de096c81d8c88b2842f/src/cargo.rs#L143-L170

This is doing `cargo build --examples` for `--run-type Examples`. If the intent is to run the tests in the examples, the executed command should be `cargo test --no-run --examples`.

To be clear, I'm not certain if the behavior of `--run-type Examples` is _wrong_, persay. Assuming you _can_ get coverage from an arbitrary entry point (and not just the rusttest harness), it can be useful to run examples with coverage for those examples which are oneshot runs.

----

Side note: I think, based on that code, that tarpaulin isn't running inline unit tests. IIUC, `cargo test --tests` just does the external tests (those in the `tests` folder and/or specified as tests in `Cargo.toml`, and `--lib` or `--bins` need to be used to get the unit tests out of the lib or bins, respectively. (Again, IIUC, the default of `cargo test` is approximately `cargo test [--lib] [--bin default] --tests --doc` (with `--lib` and `--bin` as appropriate for present lib/bin targets), and using an explicit picker removes those defaults.)

**Comment by xd009642** [comment]
I've done a fix for this and tested it on sorbus, it's on the develop branch if you want to use it before the next release. But if not I hope to solve some of the doc test coverage issues this week and then do a new release this weekend or next week :+1:
