### ISSUE TITLE
Handle multiple instances of generic functions

### ISSUE THREAD

**Issue by philipc** [xd009642/tarpaulin#43]
Currently, if multiple addresses are found for the same line number, then only the first address is used.

The problem is that these addresses may belong to different instances of the same generic function, and if the test cases only call one of these instances then the coverage reports that the function wasn't called at all.

Here's an example run where this occurred: https://coveralls.io/builds/13559392
Note that the coverage says `Lines::new` was [called](https://coveralls.io/builds/13559392/source?filename=src%2Flib.rs#L592), but none of the [lines within it](https://coveralls.io/builds/13559392/source?filename=src%2Flib.rs#L871) have hits.

I think what you need to do is deduplicate within a line number row sequence when parsing the DWARF, but if multiple sequences have an address for the line then install an breakpoint for each one.

**Comment by xd009642** [comment]
So I did consider this while working on #40. So I added the deduplication because there were multiple instructions for each line especially with things like matches, conditionals etc and it was leading to incorrect hit counts. I've kind of built my understanding of the dwarf address to line stuff based on the output of `objdump -WL` (the decoded lines) and parts of the standard and gimli docs so I might have missed something.

So looking at my simple_project test project Where the file unused.rs contains only:

```
pub fn hello() {  // Line 4
    println!("Hello world");
    println!("I'm never tested);
}
```

The decoded lines I get are:
```
tests/data/simple_project/src/unused.rs:
unused.rs                                      4            0x404a00
unused.rs                                      5            0x404a18
unused.rs                                      0            0x404a2b
unused.rs                                      5            0x404a2f
unused.rs                                      0            0x404a34
unused.rs                                      6            0x404a44
unused.rs                                      0            0x404a57
unused.rs                                      6            0x404a5b
unused.rs                                      7            0x404a60
```

Hence my deduplication step.

I'm going to look into this more closely regarding instances with generics to see if this problem has a nice clean solution, but I can see you've worked on gimli so you probably have a much better idea than me. So with that in mind if you have any tips or pointers that would be great :smile:

**Comment by philipc** [comment]
Currently rust uses a separate line number sequence for every function. I'm not sure if this is ever likely to change (I think it's dependent on LLVM). If we can rely on that though, then doing the deduplication within each sequence will be easy and it will handle simple_project, while still allowing multiple instances of generic functions. Otherwise, you'll need to get the range info for each function in order to figure out which lines belong to the same function instance. You can get this out of either the symbol table, or `.debug_info`.

Personally though, I don't really care about hit counts being accurate. I want coverage to be accurate though, and currently it isn't. So another option if you don't care about hit counts is you can simply add a breakpoint for every line. This may also allow you to get coverage information when a line contains a branch, eg if a line is an `if/else` all on one line, then may be 3 line entries: condition, true branch, and false branch, and avoiding deduplication lets you get coverage info for each of those separately. There may be some challenges in reporting that info in a useful manner though.

**Comment by xd009642** [comment]
Thanks for the tips, I'm sure that's more than enough to go on :+1:. 

Regarding hit count, I don't want to remove features that work for a number of projects, especially given that hit-rate is used as a metric in codecov and coveralls. Obviously, working coverage is the most important outcome so I will be addressing this as the next issue I tackle, but I'll be trying out the solutions which don't sacrifice existing features.

**Comment by xd009642** [comment]
Fixed and tested on a project I created to recreate the issue. Thanks for the issue :smile:

**Comment by philipc** [comment]
Thanks for the quick fix, those results are looking much better now.
