### ISSUE TITLE
--ignore-panics should ignore extra parameters to assert macros

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#448]
```rust
assert!(
    somecond,
    "explanation: {}",
    somevar,
);
```

`tarpaulin` reports the `somevar` line as uncovered under `--ignore-panics`, but if this line is reached, we've panicked. Similar for the other `assert_XX!` macros.

**Comment by xd009642** [comment]
that's probably down to how the code the macro creates differs with the flag, I can look at adding the macros to my logical line based analysis. It'll just need some thought about areas where it may impact accuracy negatively :thinking:

**Comment by xd009642** [comment]
Finally got round to this, and there's something now in develop to do it! I should cut a new release this weekend so you'll see it the crates.io install then :tada:
