### ISSUE TITLE
Features flag is broken

### ISSUE THREAD

**Issue by pksunkara** [xd009642/tarpaulin#453]
https://travis-ci.org/github/clap-rs/clap/jobs/690930150#L362

You are not allowing any features to be set at all which I assume is a mistake. Please fix and do a patch release soon.

**Comment by xd009642** [comment]
Working on it now, and I'll add a test so this doesn't happen again

**Comment by xd009642** [comment]
@pksunkara I've just pushed a commit to develop if you want to try it out. I've tried it on clap with the arguments and it worked for me.

Once the CI passes I'll go through the release process

**Comment by xd009642** [comment]
Release commit pushed out so it'll be on crates.io once the CI is finished :+1:
