### ISSUE TITLE
--features required?

### ISSUE THREAD

**Issue by baszalmstra** [xd009642/tarpaulin#454]
Since v0.13.1 I get this error on CI:

```
/usr/share/rust/.cargo/bin/cargo tarpaulin --out Xml --verbose --all-features --workspace
error: The following required arguments were not provided:
    --features <FEATURES>...

USAGE:
    cargo tarpaulin --all-features --features <FEATURES>... --out <FMT>... --verbose --workspace
```

Specifying `--all-features` doesn't work either. My project has no specific features, how should I call `cargo tarpaulin`?

**Comment by xd009642** [comment]
Oh damn, sorry about that I must have messed up the clap usage string in what I thought was a simple patch. I'll do another patch and release a new version imminently

**Comment by baszalmstra** [comment]
Haha, no worries, been there done that. :)

**Comment by danieleades** [comment]
ha was just going to flag this.

have you considered using structopt instead of clap (directly)?

**Comment by xd009642** [comment]
I've considered it but it feels like it would be a big refactor of code that's been fairly stable until recently and I've got other issues in tarpaulin to work on

**Comment by xd009642** [comment]
Right it should be on crates.io in the next 5 minutes or so, thanks for letting me know :+1:

**Comment by baszalmstra** [comment]
Thank you for such a fast fix! I can confirm that it works. 👍
