### ISSUE TITLE
Make sure files with no coverable code are in Html report (and optionally coverage.json)

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#459]
I have a 2018 edition crate with:

```
src/module_file.rs
src/module_file/submodule.rs
```

In the Html output, I only see a `module_file` directory for this (`module_file.rs` is not rendered).

**Comment by xd009642** [comment]
Do you have a project that you can share? Also what's inside the `src/module_file.rs`? If there's no lines that can be covered it probably won't be rendered in the report

**Comment by mathstuf** [comment]
The source branch here: https://gitlab.kitware.com/utils/rust-gitlab/-/merge_requests/224

The report is uploaded as an artifact (it had run out of disk space; rerunning them now so it shows up).

**Comment by mathstuf** [comment]
And the module files are just a bunch of re-exports, so maybe that is the case.

**Comment by xd009642** [comment]
yeah that'll be the case if there's no code to cover there's nothing in the report. 

The question is then: should there be something then added to the HTML reports so you see every rs file regardless of if it has any code to cover in it? I personally don't have an opinion on the matter, I think both methods make sense.

**Comment by mathstuf** [comment]
I think seeing 0/0 for files without coverable content makes sense. It allows them to participate in "coverage over time" graphs if they do end up with code at some point (or code disappears from a file).

**Comment by xd009642** [comment]
Makes sense, I'm not sure when I'll have time to work on this but off the top of my head I think an answer may be to take `src/test_loader.rs` and when the tracemap is constructed also walk the project source directories to get any files not in the tracemap and just add them in with an empty vector of traces.

That should add them into the coverage.json that's saved in the target folder and might make the source appear in the HTML report. The coverage.json is used for the delta coverage in the terminal printout so could be a starting point to implement other methods of tracking coverage over time.

Mainly just a note for future me (or anyone who looks at this and fancies contributing).

I'll also change the title to be clearer to the feature and had some tags to this issue

**Comment by xd009642** [comment]
I've implemented this and it's in develop :tada:
