### ISSUE TITLE
Tarpaulin exits with 0 if there were errors compiling tests

### ISSUE THREAD

**Issue by hawkw** [xd009642/tarpaulin#46]
Tarpaulin currently appears to exit with a 0 if compiling the test executables failed.

For `h2`, we are currently building the library with `cargo build` and then letting Tarpaulin build and run the tests, rather than running Tarpaulin for coverage only after running the tests from cargo. Because Tarpaulin will exit successfully if building the test executables failed, this means that builds on Travis are being marked as "successful" when, in fact, the tests were never run (see carllerche/h2#143 for details).

Here's an [example](https://travis-ci.org/carllerche/h2/jobs/285119212#L531-L551) of a Travis build where the tests did not compile but the build was marked as successful.

**Comment by xd009642** [comment]
Thanks for the issue. I've just fixed this and am in the process of releasing 0.5.2 with this fix in!
