### ISSUE TITLE
Hidden error message when using --exclude without --workspace

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#460]
When running tarpaulin 0.13.2 in a workspace with `--exclude` but without the `--workspace` flag, no error is reported but no coverage is collected:

```
[INFO tarpaulin] Creating config
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
Error: "Failed to report coverage! Error: No coverage results collected."
```

Adding the `--debug` flag reveals the actual error:

```
error: --exclude can only be used together with --workspace
```
Probably this error should be shown even without the `--debug`` flag.

**Comment by xd009642** [comment]
Just sorted this and it's in develop. I'll also go through the stages of releasing a new version later today.
