### ISSUE TITLE
String litterals are counted as "not covered"

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#47]
I have a project with lots of code like this:

```rust!
writeln!(
    out,
    r#"Some text
    spanning several lines
    because it's quite long"#,
)?;
```

In these case, there are several lines of code that are only occupied by string litterals (either regular `"..."` or raw `r#"..."#`), and these lines are always counted as "not covered", even if the enclosing `writeln!(..)` is properly counted as covered.

**Comment by xd009642** [comment]
Thanks for the issue, I know what needs to be done so hopefully expect something this week. :+1:

**Comment by xd009642** [comment]
So I don't suppose you could share a small working example. I've created a small test project with the snippet you pasted above as well as some other attempts and I can't recreate the issue. Also, are you running the latest version of tarpaulin?

**Comment by xd009642** [comment]
I've wrote some code which may sort the issue, but until I can create or get a test project which recreates the issue I can't properly test it (although you could try it out if you feel eager :wink:). Or some help in building wayland-rs might help me solve the issue, but I'd prefer a smaller test project.

**Comment by vberger** [comment]
I'm observing it on wayland-scanner, see here https://coveralls.io/builds/13636716/source?filename=wayland-scanner%2Fsrc%2Fcode_gen.rs

This crate is independent from the rest of wayland-rs, so you can extract it. As well as the scanner test in wayland-rs test directory.

Otherwise, I may find some time tomorrow to try and make a simpler example.

**Comment by xd009642** [comment]
Awesome I can see it on my system. That should be enough for me to get cracking :+1:

**Comment by xd009642** [comment]
Right I've finally got this cracked. I forked wayland-rs for testing and you can see results here if you don't mind reading the raw logs https://travis-ci.org/xd009642/wayland-rs/jobs/288797043 (although advanced warning I will delete my fork in a couple of days).

Suffice to say checking it against the code_gen file I'm happy I've covered this, although there may be some unconsidered edge cases. If you find any just let me know :+1: I'll probably release a new version tomorrow or Wednesday with this change in :smile:
