### ISSUE TITLE
Windows Compilation Problem

### ISSUE THREAD

**Issue by hgabe** [xd009642/tarpaulin#471]
`error[E0432]: unresolved import `nix::unistd`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:11:10
   |
11 | use nix::unistd::*;
   |          ^^^^^^ could not find `unistd` in `nix`

error[E0432]: unresolved import `nix::unistd`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\breakpoint.rs:3:10
  |
3 | use nix::unistd::Pid;
  |          ^^^^^^ could not find `unistd` in `nix`

error[E0432]: unresolved imports `nix::Error`, `nix::Result`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\breakpoint.rs:4:11
  |
4 | use nix::{Error, Result};
  |           ^^^^^  ^^^^^^ no `Result` in the root
  |           |
  |           no `Error` in the root

error[E0432]: unresolved import `nix::errno`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:1:10
  |
1 | use nix::errno::Errno;
  |          ^^^^^ could not find `errno` in `nix`

error[E0433]: failed to resolve: could not find `sys` in `nix`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:3:10
  |
3 | use nix::sys::ptrace::*;
  |          ^^^ could not find `sys` in `nix`

error[E0433]: failed to resolve: could not find `sys` in `nix`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:4:10
  |
4 | use nix::sys::signal::Signal;
  |          ^^^ could not find `sys` in `nix`

error[E0432]: unresolved import `nix::libc`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:2:10
  |
2 | use nix::libc::{c_long, c_void};
  |          ^^^^ could not find `libc` in `nix`

error[E0432]: unresolved import `nix::unistd`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:5:10
  |
5 | use nix::unistd::Pid;
  |          ^^^^^^ could not find `unistd` in `nix`

error[E0432]: unresolved imports `nix::Error`, `nix::Result`
 --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:6:11
  |
6 | use nix::{Error, Result};
  |           ^^^^^  ^^^^^^ no `Result` in the root
  |           |
  |           no `Error` in the root

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:13:28
   |
13 |     let options: Options = Options::PTRACE_O_TRACESYSGOOD
   |                            ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:14:11
   |
14 |         | Options::PTRACE_O_TRACEEXEC
   |           ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:15:11
   |
15 |         | Options::PTRACE_O_TRACEEXIT
   |           ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:16:11
   |
16 |         | Options::PTRACE_O_TRACECLONE
   |           ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:17:11
   |
17 |         | Options::PTRACE_O_TRACEFORK
   |           ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Options`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:18:11
   |
18 |         | Options::PTRACE_O_TRACEVFORK;
   |           ^^^^^^^ use of undeclared type or module `Options`

error[E0433]: failed to resolve: use of undeclared type or module `Request`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:48:13
   |
48 |             Request::PTRACE_PEEKUSER as RequestType,
   |             ^^^^^^^ use of undeclared type or module `Request`

error[E0433]: failed to resolve: could not find `pid_t` in `libc`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:49:19
   |
49 |             libc::pid_t::from(pid),
   |                   ^^^^^ could not find `pid_t` in `libc`

error[E0433]: failed to resolve: use of undeclared type or module `Request`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:64:13
   |
64 |             Request::PTRACE_POKEUSER,
   |             ^^^^^^^ use of undeclared type or module `Request`

error[E0433]: failed to resolve: use of undeclared type or module `ForkResult`
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:139:12
    |
139 |         Ok(ForkResult::Parent { child }) => {
    |            ^^^^^^^^^^ use of undeclared type or module `ForkResult`

error[E0433]: failed to resolve: use of undeclared type or module `ForkResult`
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:145:12
    |
145 |         Ok(ForkResult::Child) => {
    |            ^^^^^^^^^^ use of undeclared type or module `ForkResult`

error[E0412]: cannot find type `ProcessInfo` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\breakpoint.rs:77:37
   |
27 | impl Breakpoint {
   |     - help: you might be missing a type parameter: `<ProcessInfo>`
...
77 |     ) -> Result<(bool, TracerAction<ProcessInfo>)> {
   |                                     ^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Error` in crate `nix`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\errors\mod.rs:26:19
   |
26 |     NixError(nix::Error),
   |                   ^^^^^ not found in `nix`
   |
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use cargo_metadata::Error;
   |
1  | use clap::Error;
   |
1  | use core::fmt::Error;
   |
1  | use crate::report::cobertura::Error;
   |
     and 24 other candidates

error[E0412]: cannot find type `Error` in crate `nix`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\errors\mod.rs:67:16
   |
67 | impl From<nix::Error> for RunError {
   |                ^^^^^ not found in `nix`
   |
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use cargo_metadata::Error;
   |
1  | use clap::Error;
   |
1  | use core::fmt::Error;
   |
1  | use crate::report::cobertura::Error;
   |
     and 24 other candidates

error[E0412]: cannot find type `Error` in crate `nix`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\errors\mod.rs:68:21
   |
68 |     fn from(e: nix::Error) -> Self {
   |                     ^^^^^ not found in `nix`
   |
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use cargo_metadata::Error;
   |
1  | use clap::Error;
   |
1  | use core::fmt::Error;
   |
1  | use crate::report::cobertura::Error;
   |
     and 24 other candidates

error[E0425]: cannot find function `open_symbols_file` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\test_loader.rs:392:16
    |
392 |     let file = open_symbols_file(test)?;
    |                ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Options` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:13:18
    |
13  |       let options: Options = Options::PTRACE_O_TRACESYSGOOD
    |                    ^^^^^^^ help: an enum with a similar name exists: `Option`

error[E0425]: cannot find function `setoptions` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:19:5
   |
19 |     setoptions(pid, options)
   |     ^^^^^^^^^^ help: a local variable with a similar name exists: `options`

error[E0425]: cannot find function `detach` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:23:5
   |
23 |     detach(pid, None)
   |     ^^^^^^ not found in this scope

error[E0412]: cannot find type `Signal` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:26:44
   |
26 | pub fn continue_exec(pid: Pid, sig: Option<Signal>) -> Result<()> {
   |                     -                      ^^^^^^ not found in this scope
   |                     |
   |                     help: you might be missing a type parameter: `<Signal>`

error[E0425]: cannot find function `cont` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:27:5
   |
27 |     cont(pid, sig)
   |     ^^^^ not found in this scope

error[E0425]: cannot find function `step` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:32:5
   |
32 |     step(pid, None)
   |     ^^^^ not found in this scope

error[E0425]: cannot find function `read` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:36:5
   |
36 |     read(pid, address as AddressType)
   |     ^^^^ not found in this scope
   |
help: possible candidates are found in other modules, you can import them into scope
   |
1  | use core::ptr::read;
   |
1  | use libc::read;
   |
1  | use std::fs::read;
   |
1  | use std::ptr::read;
   |

error[E0412]: cannot find type `AddressType` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:36:26
   |
36 |     read(pid, address as AddressType)
   |                          ^^^^^^^^^^^ not found in this scope

error[E0423]: expected function, found macro `write`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:40:5
   |
40 |     write(pid, address as AddressType, data as *mut c_void)
   |     ^^^^^
   |
help: use `!` to invoke the macro
   |
40 |     write!(pid, address as AddressType, data as *mut c_void)
   |          ^
help: possible better candidates are found in other modules, you can import them into scope
   |
1  | use core::fmt::write;
   |
1  | use core::ptr::write;
   |
1  | use libc::write;
   |
1  | use serde::export::fmt::write;
   |
     and 4 other candidates

error[E0412]: cannot find type `AddressType` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:40:27
   |
40 |     write(pid, address as AddressType, data as *mut c_void)
   |                           ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `ptrace` in crate `libc`
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:47:15
   |
47 |         libc::ptrace(
   |               ^^^^^^ not found in `libc`

error[E0412]: cannot find type `RequestType` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:48:41
   |
48 |             Request::PTRACE_PEEKUSER as RequestType,
   |                                         ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `ptrace` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:63:9
   |
63 |         ptrace(
   |         ^^^^^^ not found in this scope

error[E0425]: cannot find function `traceme` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:73:5
   |
73 |     traceme()
   |     ^^^^^^^ not found in this scope

error[E0425]: cannot find function `getevent` in this scope
  --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\ptrace_control.rs:77:5
   |
77 |     getevent(pid)
   |     ^^^^^^^^ not found in this scope

error[E0425]: cannot find function `limit_affinity` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:135:21
    |
135 |     if let Err(e) = limit_affinity() {
    |                     ^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `fork` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:138:11
    |
138 |     match fork() {
    |           ^^^^ not found in this scope

error[E0412]: cannot find type `Pid` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:161:11
    |
161 |     test: Pid,
    |           ^^^ not found in this scope

error[E0425]: cannot find function `create_state_machine` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:169:37
    |
169 |         let (mut state, mut data) = create_state_machine(test, &mut traces, config);
    |                                     ^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `execute` in this scope
   --> C:\Users\hgsba\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-tarpaulin-0.13.3\src\lib.rs:227:5
    |
227 |     execute(exec_path, &argv, envars.as_slice())
    |     ^^^^^^^ not found in this scope

error: aborting due to 45 previous errors

Some errors have detailed explanations: E0412, E0423, E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `cargo-tarpaulin`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-tarpaulin v0.13.3`, intermediate artifacts can be found at `C:\Users\hgsba\AppData\Local\Temp\cargo-installiOkFwJ`

Caused by:
  build failed`

**Comment by yerke** [comment]
From README: `Tarpaulin only supports x86_64 processors running Linux.`

**Comment by xd009642** [comment]
Yeah currently tarpaulin only works on Linux. There is a tracking issue for windows support but I haven't started any work on it #131. Otherwise I think it should work on windows subsystem for linux.
