### ISSUE TITLE
--no-run runs tests and reports coverage

### ISSUE THREAD

**Issue by leeola** [xd009642/tarpaulin#473]
Perhaps I am confused, but `--no-run` appears to not work correctly. 

My expectation is that, like `cargo test --no-run`, it will compile but not execute any user code. However in practice it appears to both run tests and print a coverage summary.

Example:

```
cargo new --lib foo
cd foo
docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin sh -c "cargo tarpaulin --no-run"
```

**Comment by xd009642** [comment]
Yeah that's an issue I'll sort it now it should be relatively easy :+1:

**Comment by xd009642** [comment]
Yeah that's now sorted in the develop branch so it'll be in the next release (whenever that ends up being)
