### ISSUE TITLE
No output at all...

### ISSUE THREAD

**Issue by ckaran** [xd009642/tarpaulin#481]
I'm trying to see if I'm doing something wrong.  I'm using [bolero](https://crates.io/crates/bolero) to fuzz test all my code.  However, when I run `cargo tarpaulin -t 1000 -b --ignore-tests -l --workspace -o Html`, I don't get any HTML output.  Is tarpaulin putting the results somewhere I can't find?  Or is there a real problem between fuzzing and tarpaulin?

**Comment by xd009642** [comment]
Well if it's runnable via `cargo test` it should work. Do you have a repo I can reproduce it with?

**Comment by ckaran** [comment]
Not yet... and the results just got weirder.  When I selected a single test to run, it worked.  No idea why yet, I'm working on tracking it down.

That said, this may actually be an issue with bolero; I logged one earlier at https://github.com/camshaft/bolero/issues/18.  I'll keep poking to see what is going on.

**Comment by ckaran** [comment]
OK, I've skipped two tests that have known failures... and tarpaulin produced good output.  This is definitely a bolero issue of some kind.  I'm going to close out this bug.  Thanks for the fast response!
