### ISSUE TITLE
Running a single test type? ie --lib, --test, etc

### ISSUE THREAD

**Issue by leeola** [xd009642/tarpaulin#482]
I'm attempting to get coverage for what would normally be `cargo test --lib`. Most notably I'm doing this to avoid some integration tests, and not having success with the flag `--exclude-files "*integration*"`.

Am I missing a way to just run lib tests?

_(edit: I realized I am pre-assuming what the `Tests` runtype does, so I'm trying that now. To see if it excludes `/tests`)_
_(edit2: nope, seems the `Tests` runtype still executes `/tests`, as expected.)_

**Comment by xd009642** [comment]
There's not yet an analogue for `--lib` it is on my todo list as part of #247

**Comment by xd009642** [comment]
I've currently got a feature branch for this and it seems to be working pretty good. I'll look at adding some tests and tidying it up as I'm also adding things like named tests at the same time i.e. `--bench <NAME>`

**Comment by xd009642** [comment]
This is now in the develop branch, so you can try it out there otherwise it'll be around next release :+1:
