### ISSUE TITLE
Coverage gaps on `match` and some function argument lines.

### ISSUE THREAD

**Issue by scouten** [xd009642/tarpaulin#496]
I am seeing some lines of code marked as executable, but not reached, when it is logically impossible for those lines to have been missed.

This [codecov.io report](https://codecov.io/gh/rust-git/rsgit/pull/56/diff?src=pr&el=tree#diff-c3JjL29iamVjdC9tb2QucnM=) demonstrates some examples of that with a `match` expression and a function with arguments spilling across multiple lines.

**Comment by xd009642** [comment]
Closing this issue as the llvm coverage backend is now released --engine llvm with increased accuracy due to compile time instrumentation instead of runtime
