### ISSUE TITLE
cargo tarpaulin cannot successfully compile while cargo test can

### ISSUE THREAD

**Issue by w93163red** [xd009642/tarpaulin#497]
I am compiling my project and use tarpaulin to get the coverage. However when I run `cargo tarpaulin --lib --features "xxx"` I encountered this problem:
![image](https://user-images.githubusercontent.com/7308728/87615476-db279600-c6e0-11ea-9f00-b4a7cc46c5a7.png)
The crate repo: https://github.com/time-rs/time

But when I ran cargo test --lib --features "xxx", I did not encounter this. Is there any way I can fix that?

**Comment by w93163red** [comment]
When I downloaded the time crate, and just ran `cargo tarpaulin`:

![图片](https://user-images.githubusercontent.com/7308728/87681081-3b075680-c74c-11ea-812b-0a5f638069fd.png)

**Comment by xd009642** [comment]
So the solution is either to move down to tarpaulin 0.13.x, got to a github link for the time version or wait for the next time release. They've fixed it in tree but from what I understand it won't be released until 0.3 is ready https://github.com/time-rs/time/issues/267
