### ISSUE TITLE
No way to run ignored tests

### ISSUE THREAD

**Issue by yodaldevoid** [xd009642/tarpaulin#5]
I can find no way to currently run tarpaulin so that tests that are marked to be normally ignored are run. Either by default or behind some flag tests that are normally ignored should be run when checking code coverage.

**Comment by xd009642** [comment]
There currently is no way. However, I'll start adding the relevant code now. I know what needs to be done so hope to have something released before the end of the weekend!

**Comment by xd009642** [comment]
Implemented and tested, I've added a flag to run any ignored tests. Thanks for the issue :+1:

**Comment by yodaldevoid** [comment]
Well, that was certainly fast! Thank you very much!
