### ISSUE TITLE
Ignore whole file in src/bin

### ISSUE THREAD

**Issue by nilgoyette** [xd009642/tarpaulin#515]
I tried adding `#![cfg(not(tarpaulin_include))]` on top of some files to tell tarpaulin to ignore the whole file. I also tested without the `!`. In both cases, the command is ignored and tarpaulin does its job.

I'm aware that we can ignore a module, but how can I tell tarpaulin to ignore a file in src/bin without adding a `#![cfg(not(tarpaulin_include))]` in top of all my functions?

Tested on private enterprise project on a Linux Mint 20.0 vm, Rust 1.45.0

**Comment by xd009642** [comment]
You can use the `--exclude-files` argument i.e. `--exclude-files src/main.rs`. I'll try and have a look at getting the module level attributes to work as well.
