### ISSUE TITLE
Segfault when used with actix-web tests

### ISSUE THREAD

**Issue by OskarPersson** [xd009642/tarpaulin#519]
I'm getting a segfault error when running tarpaulin with actix-web tests. I've created a docker image but I can for some reason only reproduce the error when running the docker image on Gitlab CI. I've created a minimal example [here](https://gitlab.com/oskarpersson/actix-tarpaulin) ([failing job](https://gitlab.com/oskarpersson/actix-tarpaulin/-/jobs/666773181))

The test works as expected when using only `cargo test` instead of `cargo tarpaulin`.

**Comment by xd009642** [comment]
Quick request could you add the `--debug` flag to the gitlab CI example you've done. Just hoping it might give me enough info without needing to make my own gitlab repo to replicate it

**Comment by OskarPersson** [comment]
Done https://gitlab.com/oskarpersson/actix-tarpaulin/-/jobs/683370058

**Comment by glademiller** [comment]
I don't have any more details to add other than to say I believe I am experiencing the same issue since the last update to the latest tag on docker hub.

**Comment by OskarPersson** [comment]
This seems to now be fixed with the latest tarpaulin, actix-web (4.0.0 rc3) and rust: https://gitlab.com/oskarpersson/actix-tarpaulin/-/commit/f65a0ea386472c7dc696ea818a48337d40d5ed44
