### ISSUE TITLE
Option to embed/use local JavaScript resources instead of from unpkg.com

### ISSUE THREAD

**Issue by legoktm** [xd009642/tarpaulin#534]
Hi,

We're starting to use tarpaulin at Wikimedia to generate HTML code coverage reports for our Rust projects, and it's pretty great. However, we have a pretty restrictive CSP that only allows local/self-hosted resources for both privacy and security reasons (e.g. [a broken report](https://doc.wikimedia.org/cover/labs-tools-shorturls/)). Would it be possible to bundle any necessary resources with tarpaulin so they don't need to be loaded from a remote site? This would also be nice for offline usage.

See for example how a [PHPUnit report](https://doc.wikimedia.org/cover-extensions/Linter/) bundles bootstrap.

Also, we're stuck on 0.13.x because of the time issue (#505), I don't know if it'd would be possible to also backport a fix to that series of releases, I'd understand if not.

https://phabricator.wikimedia.org/T260786 is our downstream task for this.

**Comment by xd009642** [comment]
Thanks for the kind words :smile: and I don't seen an issue with bundling things like that. I'll add it, backport the fix and let you know when it's release :+1:

**Comment by hashar** [comment]
The Content Security Policy messages in Firefox console:
```
Content Security Policy: The page’s settings blocked the loading of a resource at:
https://unpkg.com/react@16/umd/react.production.min.js (“script-src”).
https://unpkg.com/react-dom@16/umd/react-dom.production.min.js (“script-src”).
```

:]

**Comment by xd009642** [comment]
This is now in two branches. One off the current develop, another branching off of the last 0.13.x release called `0.13.5_BACKPORT` if you install tarpaulin from there and confirm there are no other issues I can either push out a release if you'd rather, or if you don't mind you can install it via the git url and I don't have to think about how to represent this in my changelog :grin: .

**Comment by legoktm** [comment]
I tested the `0.13.5_BACKPORT` branch and it works perfectly, thanks :) I updated our CI to install the version from git, which should be fine for us going forward and now https://doc.wikimedia.org/cover/labs-tools-newusers/ looks great.

**Comment by xd009642** [comment]
Awesome, I also noticed a false-negative issue which I've created an issue for here since it should be quick https://github.com/xd009642/tarpaulin/issues/546 . I'll sort out the changelog and merge the fix against the latest version and close this issue when it's done. Then once time gets it's 0.3 release out tarpaulin will be ready for you :smile:
