### ISSUE TITLE
Tarpaulin doesn't rule out testing code when calculating coverage

### ISSUE THREAD

**Issue by RaynaYe** [xd009642/tarpaulin#544]
![image](https://user-images.githubusercontent.com/9419175/91035265-e7383900-e638-11ea-9c87-5974519b2b0c.png)
As is shown in the picture, when calculating coverage results，Tarpaulin regards testing code same as project code.
However, in many other coverage tools， testing code should not be taken into consideration，measurement is only target at real project code. This calculating way can cause the problem that the coverage we get may be higher than the real value.
How do you guys think about this problem?

**Comment by xd009642** [comment]
There is an `--ignore-tests` flag for ignoring lines in modules or functions annotated by `#[cfg(test)]` or `#[test]`.

**Comment by RaynaYe** [comment]
> There is an `--ignore-tests` flag for ignoring lines in modules or functions annotated by `#[cfg(test)]` or `#[test]`. It'll probably be made a default in future releases but that's a tbd

got it! thank you!
