### ISSUE TITLE
HTML reports

### ISSUE THREAD

**Issue by a-dma** [xd009642/tarpaulin#55]
It would be nice to have the possibility to generate local HTML coverage reports [like lcov does](http://ltp.sourceforge.net/coverage/lcov/output/index.html) without having to rely on external tools like travis or coverall. Mostly, having a percentage indicators and a function breakdown while being able to browse the code would be a very valuable addition. imo.

**Comment by xd009642** [comment]
So that is the main approach I was thinking of for the road-map item of "annotated coverage reports". I realise that's really open ended and non-specific but I was leaving my options open. I haven't really worked on it yet because no one's expressed an interest in the feature. Until now!

I'll start investigating and try to get something in for my 0.6.x release. I'm not gonna make any promises yet just cause it's early days. But if I have any updates I'll let you know here.

**Comment by a-dma** [comment]
Great, thanks a lot.
As always time is scarce, but I'm happy to lend a hand when possible

**Comment by xd009642** [comment]
Thanks for the offer. Firstly, I'll need to choose a crate to let me generate the html. I'm having a look at some options but if you have any specific recommendations I'd be open to suggestions :+1:

**Comment by a-dma** [comment]
There's a ton of template crates (there's a ton of everything Rust right now...). Have a look at https://github.com/rust-unofficial/awesome-rust#template-engine. I think something simple with as few dependencies as possible would be nice here, I think `horrorshow-rs` looks interesting.

Otherwise I would probably use `serde` and implement a custom deserializer into HTML.
Just my two cents of course!

**Comment by mathstuf** [comment]
What about generating markdown and letting that get rendered using a markdown crate?

**Comment by xd009642** [comment]
So there's currently significant process on this that hasn't yet been pushed to github yet. There are more interactive elements like a project browser to let people browse their results. No one get too excited yet but wait and see what's in store :wink:

**Comment by mathstuf** [comment]
OK, sounds good :) .

**Comment by guidiego** [comment]
Hey @xd009642 Im totally interested in this project, could I help in this one?

**Comment by xd009642** [comment]
Hmm I'm not sure how easy this one is to jump into, it's being done as part of a near complete rewriting of the report module. Also the HTML reports are actually designed, it's now just a case of doing the rewrite and filling in the template.

If you're open to other issues, #54 #113 and #63 might be good ones to work on. (Though #113 depends how comfortable you are reading the cargo source code).

I was also going to look into what windows support would take - though that is a big addition

**Comment by guidiego** [comment]
@xd009642 Yeah! I didn't think that will be easy. Correct me if I am wrong, `tarpaulin` didn't create any kind of coverage files.

In my vision, we need to improve the CLI output and format a `.lcov` file! Has many HTML reporters that accept lcov + code string and create the reporter automatically <3

About another issues: I'm taking a look at the list into #63, and unsure if I understand #113! But I will try open PR's in the next days!

**Comment by vi** [comment]
Just using `kcov somedir/ target/debug/test-6e8607e47b97cdb7` gives nice HTML reports.

Can `tarpaulin` just automatically call `kcov` if it is available and put the HTML into some `target/coverage/`?

**Comment by xd009642** [comment]
I kinda don't see the need for tarpaulin to call into another code coverage tool as part of it's run. Supporting standard outfor formats like the lcov file and cobertura is much more productive I feel. For example you can get html reports currently by processing an outputted cobertura.xml with pycobertura (which is detailed in the readme).

Tarpaulin will be rolling it's own HTML reports with additional information that isn't relevant to other HTML reports which also enables future reports like condition coverage, MCDC etc which I haven't seen in other open source tools. 

When the reporting module is in a state others can work on it, I think generating a `.lcov` file would definitely be a good addition 👍

**Comment by xd009642** [comment]
Closed thanks to #182 if anyone wants to try it out look to the develop branch (or my next crates.io release)
