### ISSUE TITLE
Coverage for workspaces

### ISSUE THREAD

**Issue by dragostis** [xd009642/tarpaulin#56]
Would it make sense for tarpaulin to generate coverage for workspaces by running `cargo test --all`? This would help a lot with integration tests that cover more than one crate.

**Comment by xd009642** [comment]
Yeah that makes sense. I do over a packages option so people can specify the list of packages in the workspace to do the same thing. I'll add this in some form or another, just need to decide if it should be a default behaviour or manually specified :+1:

**Comment by xd009642** [comment]
Closing this issue as it was fixed along with the work for #57!
