### ISSUE TITLE
Different binary run path causes file not found issues

### ISSUE THREAD

**Issue by dragostis** [xd009642/tarpaulin#57]
Running `cargo test --all` in [pest](https://github.com/pest-parser/pest) works okay, but `cargo tarpaulin -v -p pest pest_derive pest_grammars` fails with file not found [here](https://github.com/pest-parser/pest/blob/master/pest_grammars/tests/json.rs#L165), most probably due to the test binaries being run from a different path than Cargo.

**Comment by xd009642** [comment]
So I've in the past used the file! macro to get absolute paths to data I access during tests. I didn't realise cargo test changed the working directory so it wasn't an issue, I'll update tarpaulin to exhibit the same behaviour

**Comment by dragostis** [comment]
Awesome! 😄 Thank a lot.

**Comment by xd009642** [comment]
Right I've sorted this issue on my end. Just testing and afterwards I'll merge in and probably release a new tarpaulin version! To save reading the commit message I'll summarise my changes below

* Implemented `--all` as the default behaviour 
* Added exclude option to exclude packages
* Now change working directory to manifest root for each package in line with what `cargo test` does

**Comment by dragostis** [comment]
@xd009642 Awesome, professional work! Thank you so much. 👍

**Comment by xd009642** [comment]
No problem :blush: anything else just let me know

**Comment by dragostis** [comment]
The file issue still seems to [be there](https://travis-ci.org/pest-parser/pest/builds/289178522).

**Comment by xd009642** [comment]
Darnit, having a look into that now!

**Comment by xd009642** [comment]
Right I've isolated the cause. It's gonna need a bit of fiddling, so I might do a bit of a refactor to make things gel a bit nicer. If I don't have a fix by tonight I should have one tomorrow

**Comment by dragostis** [comment]
@xd009642 There's no rush. Thank you so much for taking the time. 😃

**Comment by xd009642** [comment]
So I was being overly cautious! It's fixed and to make sure I tested it on pest - no test failures.

Releasing 0.5.4! Just give travis time to upload the new github release and you should see it work :smile:
