### ISSUE TITLE
tarpaulin fails with dozens of "Failed to instrument EIO: I/O error"

### ISSUE THREAD

**Issue by yodaldevoid** [xd009642/tarpaulin#6]
I have recently tried running tarpaulin on one of my projects, namely [dts_viewer](https://github.com/yodaldevoid/dts_viewer), but every time I run it I am told my tests cover none of my code and dozens of lines of "Failed to instrument EIO: I/O error" are printed. Any clue as to what might be happening here?

**Comment by yodaldevoid** [comment]
Here is a copy of the output from running cargo tarpaulin -v
[pastebin](https://pastebin.com/UJwLnGX8)

**Comment by xd009642** [comment]
Looking at dts_viewer the project setup is definitely a bit unique. So the folder you run cargo tarpaulin on it runs it on that project, so it runs the projects tests getting coverage for the projects source. I wasn't sure how the dependent directory would be treated but running it on my system it seems to work (my output is at the bottom (non-verbose).

So just to help figure this out, what OS are you running and if it's linux what distro? I'm assuming it is linux as that's a nix error message. Is it 32 or 64 bit and what architecture? Tarpaulin is currently designed for x86_64 linux but has only been tested on Ubuntu and Fedora so running on other systems may cause things to not work.

> [xd009642@localhost dts_viewer]$ cargo tarpaulin
> Launching test
> 
> running 0 tests
> 
> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
> 
> Launching test
> 
> running 31 tests
> ...............................
> test result: ok. 31 passed; 0 failed; 0 ignored; 0 measured
> 
> Launching test
> Both DTS_DIR and CARGO_MANIFEST_DIR unset!
> Coverage Results
> device_tree_source/src/include.rs: 31/277
> src/main.rs: 0/148
> device_tree_source/tests/iter_dts_files.rs: 8/78
> device_tree_source/src/parser.rs: 305/493
> src/change_tracker.rs: 0/107
> device_tree_source/src/lib.rs: 30/40
> device_tree_source/src/tree.rs: 0/271
> 
> 26.45% coverage, 374/1414 lines covered

**Comment by yodaldevoid** [comment]
> Looking at dts_viewer the project setup is definitely a bit unique.
You say unique, I say organic. 😛 In truth, there is a method behind my madness, but that is not really relevant.

My current system is a Ubuntu 17.04 x64 minimal server install that I have built up so as to not have a bunch of cruft. Is there possibly some library or program that I could be missing?

On a side note, it is good to see that tarpaulin deals with the large amounts of macro code very cleanly.

**Comment by xd009642** [comment]
I wasn't questioning the setup, it's just interesting to see what things I hadn't anticipated :) . I'll have a look and get back to you, this might be something downstream in a dependency and a bit trickier than the other issue.

I'm glad it copes with macro code well, I didn't write anything specific to macros so this is really just showing how useful the DWARF tables are for source information :+1:

**Comment by xd009642** [comment]
Could you send me the output from "uname -a" please? Could help me figure out if there are any incompatibilities

**Comment by yodaldevoid** [comment]
`Linux auroria 4.12.0-041200rc2-generic #201705212331 SMP Mon May 22 03:32:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by xd009642** [comment]
Thanks, my initial gut instinct is that this might be caused by one of the new security updates on the 4.12 kernel. Still investigating but this one may take a while. Until I sort it, I'd recommend using a service like travis if you want to run tarpaulin on it.

**Comment by yodaldevoid** [comment]
May I ask what version of the kernel you are using?

**Comment by xd009642** [comment]
4.11.8, however today I should update to fedora 26 which will be 4.12. If I can't recreate the issue on fedora 26 I'll try to get qemu working again (I had some difficulties last time and gave up since my move to 4.12 was on the horizon)

**Comment by yodaldevoid** [comment]
I downgraded my kernel version by just booting up on an old 4.10 kernel I had laying around and the errors still occur. Unless I've gone about this wrong it doesn't look like the kernel version has any bearing on all this.

**Comment by yodaldevoid** [comment]
Using some good old-fashioned printf debugging I have determined that the call thowing all the errors is the `read_address()` at [line 34 in breakpoint.rs](https://github.com/xd009642/tarpaulin/blob/master/src/breakpoint.rs#L34). Do what you will with that information.

**Comment by xd009642** [comment]
Hmm now that is more interesting... However, the error does occur exactly where I expect.

So just to fill you in a little on what's happening, tarpaulin uses a breakpoint based method of instrumenting the code (like bcov, gcov, kcov). So it uses the debugging tables to get the addresses in the ELF file which correspond to lines of code to interject software breakpoints. Modern operating systems usually have security measures like address randomisation so that people can't tell where the instructions are with an executable, latch onto an already running process and inject malicious code.

So the EIO error will be because the address in the DWARF table isn't where the instruction actually is. I expected this to be caused by one of the new security measures in 4.12, but it might be that ubuntu minimal server has some extra security features given it's designed for server use... Either way I'll go back to trying to get qemu to work and consult the ubuntu docs on this.

If you know any security features running on the server that aren't on a typical ubuntu workstation install that could be helpful.

**Comment by xd009642** [comment]
It could potentially be because of seccomp filters on the server. I'm reading up on them now and trying somethings out. I may have to ask you to try out a test build with some more information if qemu keeps fighting me :)

**Comment by xd009642** [comment]
I've got qemu working, installed rust, tarpaulin and your repo to a minimal-ubuntu-server instance. Hopefully, I'll have a better update tomorrow for you!

**Comment by xd009642** [comment]
Well it's been a bit more than a day, but I believe I've narrowed down the problem (but not yet the solution). Despite the compile flag "-C relocation-model=dynamic-no-pic", the resulting test binaries still seem to have position independent code (which stops me mapping from dwarf tables to instructions).

I'm still looking into this, it might be it needs some extra options because of different defaults for compile options or maybe I have to take a more sophisticated approach to map from the addresses in the DWARF tables to the actual instructions i want to trace.

Just thought you might appreciate an update :)

**Comment by yodaldevoid** [comment]
Thank you for the update. I reproduced what you described. I know gcc on Ubuntu has defaulted to emitting PIC for about a year now, but I don't see how that could be connected. You mentioned that you tested Tarpaulin on Ubuntu. Do you remember what version that was on?

**Comment by xd009642** [comment]
Ubuntu 14.04 (on travis). And with Ubuntu 17.04 I set the compile flag for dynamic-no-pic so it shouldn't be an issue, unless some linker flags can come into play. 

Currently I'm going to continue under the assumption that all Ubuntu 17.04 releases (server and workstation) are effected and continue investigating.

**Comment by yodaldevoid** [comment]
So I've tested on a few VMs I had laying around. I tested on Ubuntu Desktop 15.04, 16.10, and 17.04. 15.04 was the only one that worked out of all of these. This makes sense if the Ubuntu patch to gcc is at fault as I know rust uses `ld` from gcc for linking. I suggest looking at the [Ubuntu Security page](https://wiki.ubuntu.com/Security/Features) for more information on when the patch was applied.

From this I'm wondering if PIE needs to be disabled as a linker flag as well.

**Comment by yodaldevoid** [comment]
Welp, adding "C link-args=-no-pie" to RUSTFLAGS seems to have fixed the issue when running tarpaulin, but I still see a different address in the objdump from what gdb reports. At any rate, this seems like an issue with rustc. I would expect passing "-C relocation-model=dynamic-no-pic" to disable all PIC at both build time and link time, but maybe that is just me.

**Comment by xd009642** [comment]
Interesting, I'll add a change into tarpaulin test and push out an update (as well as looking into the linker stuff). I do agree with you that this seems to be a rustc issue and it seems others agree as well from a quick google https://github.com/rust-lang/rust/issues/35061 

Thanks for your assistance in finding a solution :+1: I hope you find tarpaulin useful and let me know if you spot anything else
