### ISSUE TITLE
"0.00% coverage" reported when rustflags contains `-C debuginfo=0`

### ISSUE THREAD

**Issue by Turbo87** [xd009642/tarpaulin#601]
In https://github.com/rust-lang/crates.io/pull/2951 I've added https://github.com/actions-rs/tarpaulin to the CI pipeline of crates.io, but unfortunately it currently reports "0.00% coverage" and I'm out of ideas of what I might be doing wrong 😞 

The project definitely does have tests so the coverage should be at least above zero. Any help would be greatly appreciated! 🙏

**Comment by xd009642** [comment]
Interesting, I'll try running locally and see if I can figure it out

**Comment by Turbo87** [comment]
> I'll try running locally and see if I can figure it out

that would be great, thanks! :)


> if there are any tips for running locally would be appreciated

riiight, I totally forgot about the necessary test setup... 😅 

I hope https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#working-on-the-backend and https://github.com/rust-lang/crates.io/blob/master/docs/CONTRIBUTING.md#running-the-backend-tests should give you all the necessary information. If not, let me know if something is missing. :)

**Comment by xd009642** [comment]
I haven't gotten to this yet (been busy), but I'm releasing a fairly significant update to tarpaulin tonight or tomorrow so if you want to try it there's always the chance it may now work due to one of the new features or linker changes.

**Comment by xd009642** [comment]
@Turbo87 So I managed to get the tests running locally and with cargo-tarpaulin 0.16.0 and rustc 1.49.0 I get coverage results (82.01% coverage, 6837/8337 lines covered). I've hosted my own version just to check with actions what happens in CI as CI doesn't run on forks but if the issue persists on CI but not locally it's probably not going to be straightforward to track this down

**Comment by Turbo87** [comment]
that's good news. I wasn't even able to get it running locally, but maybe I did something wrong. did you just run it with the defaults?

**Comment by xd009642** [comment]
yeah I just followed the readme instructions, had to fiddle around with postgres just because diesel didn't seem happy doing the migration without a password but once the diesel migration worked and cargo test ran through cargo tarpaulin worked fine

**Comment by xd009642** [comment]
Oh I might have something, in the workflow it does: `RUSTFLAGS: "-C debuginfo=0 -D warnings"` now tarpaulin relies on debuginfo to map instructions to the source code. I've just removed the debuginfo removal and pushed it so I'll see if it reports coverage.

If it does I'll change this into an issue to prevent people from overriding debuginfo in a way that stops tarpaulin from working :smile:

**Comment by xd009642** [comment]
@Turbo87 That sorted it! Removing `-C debuginfo=0` gives you coverage results :tada:

**Comment by Turbo87** [comment]
awesome! I looked at `git blame` but I still can't tell why we have this enabled in the first place 😅 

thanks a lot for your help!!
