### ISSUE TITLE
false negatives with `|` in match

### ISSUE THREAD

**Issue by Licenser** [xd009642/tarpaulin#607]
Having match arms with `|` (or) variants only marks the first and last of the or variant covered:

```rust
match number {
 1
 | 3
 | 5
 | 7
 | 9
 | 11
 13 => "odd",
 _ => "even"
}
```

See: https://codecov.io/gh/tremor-rs/tremor-runtime/pull/547/src/tremor-script/src/lexer.rs?before=tremor-script/src/lexer.rs#L459

**Comment by xd009642** [comment]
Sorry for the late reply, I've just done a fix for this it should be on develop tonight and I plan on making a release later tonight as well or if not later this week. Just depends on how things go :grin:

**Comment by xd009642** [comment]
Right this has been released, feel free to reopen if somethings not quite right :smile:
