### ISSUE TITLE
SIGILL while running tarpaulin against tokio-imap

### ISSUE THREAD

**Issue by djc** [xd009642/tarpaulin#619]
See here:

https://github.com/djc/tokio-imap/runs/1394544645?check_suite_focus=true

This is the first time I've seen this -- could this be a regression somehow?

**Comment by xd009642** [comment]
Looks like one of the two issues in #618 if you do `RUSTFLAGS='-C relocation-model=dynamic-no-pic'` it should fix it in the meantime. I've got a fix for one part of #618 and know what causes the SIGILL/SIGSEGV, just working out the best fix

**Comment by djc** [comment]
Awesome, thanks.
