### ISSUE TITLE
Tarpaulin fails when binaries have required features

### ISSUE THREAD

**Issue by jonhoo** [xd009642/tarpaulin#62]
In many libraries, binaries are included to allow additional testing or benchmarking of the library. However, since these binaries introduce extra dependencies, those dependencies are often hidden under a feature, and the feature is [set as required](https://github.com/rust-lang/cargo/issues/1982#issuecomment-319661478) for the binary using [`required-featues`](http://doc.crates.io/manifest.html#the-required-features-field-optional). This is, for example, the case in [`faktory-rs`](https://github.com/jonhoo/faktory-rs/tree/e78e7627858d60dd613b46f61ae6baf31ea0145a).

Unfortunately, these required dependencies seem to confuse tarpaulin:
```console
$ cd faktory-rs
$ git checkout e78e7627858d60dd613b46f61ae6baf31ea0145a
$ cargo tarpaulin
Error during run
$ cargo tarpaulin -v
Running Tarpaulin
Cleaning project
Error: failed to compile: target `loadtest` requires the features: `binaries`
Consider enabling them by passing e.g. `--features="binaries"`
Error during run
```

The first error is pretty unhelpful, but with `-v` it's clear that tarpaulin is trying to compile the binary without including the required feature flag, which obviously doesn't work. There also doesn't seem to be a command-line flag I can use to have it *not* compile the binary. I *could* make it always use the feature (which I did as a workaround in jonhoo/faktory-rs@37b9d8904a4c6f203e88bcb1103ebaf625ec4871), but that's still not ideal.

**Comment by xd009642** [comment]
I'll have a look into this and will let you know if I have any questions or when I make some progress :+1:

**Comment by jonhoo** [comment]
For that particular crate, tarpaulin also seems to cause some tests to time out. It seems to be related to the fact that these tests sleep for a while: https://travis-ci.org/jonhoo/faktory-rs/jobs/301014855#L811

**Comment by xd009642** [comment]
That might be due to tarpaulin stealing the signals as it relies on ptrace. If the signal isn't one I expect the `--forward` option may solve the issue

**Comment by jonhoo** [comment]
@xd009642 hmm, no, `--forward` didn't seem to help :/

**Comment by xd009642** [comment]
Sorted the initial issue you reported and once the CI passes I'll release a patch so you can make use of it. Regarding the sleep issue if you want to open a new issue just cause it might be trickier so I'd prefer it in it's own issue :smile:

**Comment by xd009642** [comment]
Also noticed in your .travis.yml you set link dead code in RUSTFLAGS in your travis environment, if you're doing that for code coverage reasons there's no need tarpaulin sorts that out. But if you're doing it for other parts of your CI runs ignore me

**Comment by jonhoo** [comment]
I'll try 0.5.5 once you push it out (CI passed btw), and then open an issue for the sleep issue.

**Comment by jonhoo** [comment]
Hmm, 0.5.5 seems to solve the problem for me somehow:
https://travis-ci.org/jonhoo/faktory-rs/jobs/302178003#L776

My guess is that tarpaulin was trying to execute the binary, which then hangs because no server it could run against was available. Or something...

**Comment by xd009642** [comment]
Well that explains why I couldn't recreate it. I'm going to put it down to me subtly misusing a cargo API previously or some nuance of rustc-test which is normally hidden. Glad it works :+1:
