### ISSUE TITLE
Tarpaulin ignores non-zero exit code from a custom build script

### ISSUE THREAD

**Issue by Ch00k** [xd009642/tarpaulin#627]
I have a project where I have a custom build script, and when the build script exits with a non-zero, tarpaulin exits with a 0. [This](https://github.com/Ch00k/orthanc-cli/pull/11/checks?check_run_id=1441380815) pipeline (the `run_tests` step) illustrates the problem. [`build.rs`](https://github.com/Ch00k/orthanc-cli/blob/1a0a0b4824b5ab58a06af14ead00b7b74b9feea8/build.rs) fails because it cannot write into a directory, that does not exist.

I hope this much information is enough, but please let me know if I need to provide any more, or to create a minimal example that would illustrate the issue.

**Comment by Ch00k** [comment]
For the sake of completeness, `cargo test --bins` exits with code `101`.

**Comment by Ch00k** [comment]
I just discovered another condition where tarpaulin would exit with a 0 when cargo exists with a non-zero: https://github.com/Ch00k/orthanc-rs/pull/81/checks?check_run_id=1848790220

**Comment by Ch00k** [comment]
Ignore this. I just realized that the fix for this issue has not been released yet, and I am using the latest 0.16.0.

**Comment by xd009642** [comment]
If you use the latest develop hopefully it works. But if not, I wanted to be extra sure after the 0.17 regressions happened that the next release is 100% good so extra bug reports are always appreciated. 

Hopefully, I'll have the next release out this month but I've got a lot of other things on so it might take a bit longer
