### ISSUE TITLE
Tarpaulin Docker Image Fails to Parse New rusttoolchain Syntax

### ISSUE THREAD

**Issue by RobbieMcKinstry** [xd009642/tarpaulin#636]
Hi!

With the recent release of [rustup v1.23.0](https://blog.rust-lang.org/2020/11/27/Rustup-1.23.0.html), the Tarpaulin Docker image no longer works with the new, TOML-base format of the `rust-toolchain` file.

# To reproduce:

1. Pick a project that work with Tarpaulin.
2. Write TOML into `rust-toolchain` file, as per the rustup release linked above.

_e.g._:
```
$ cat rust-toolchain
[toolchain]
channel = "1.48"
components = ["rustfmt", "clippy"]
```

3. Run the Tarpaulin docker image in this directory:

```bash
docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
```

4. Observe the error:

```
Status: Downloaded newer image for xd009642/tarpaulin:latest
error: invalid channel name '[toolchain]' in '/volume/rust-toolchain'
error: caused by: invalid toolchain name: '[toolchain]'
```

I haven't tested if this bug exists outside of the Docker container as well, because I run OSX.

Thank you for your work on this project! :-)

**Comment by xd009642** [comment]
I'll try to have a look at this tomorrow, it's probably just the docker images need rebuilding as they use the rust latest image so are very dependent on when updates get pushed out

**Comment by RobbieMcKinstry** [comment]
Thank you!

**Comment by xd009642** [comment]
Sorry about the silence on this, I forgot to comment that the docker images have been refreshed with a newer Rust base image. Just testing it locally and with docker on the minimal example and both work fine :+1:

**Comment by RobbieMcKinstry** [comment]
Thank you! :)
