### ISSUE TITLE
Running `cargo tarpaulin` on clean project doesn't output anything while it's building

### ISSUE THREAD

**Issue by robinst** [xd009642/tarpaulin#67]
1. Have a project without a `target` folder, so it hasn't been built yet
2. Run `cargo tarpaulin` (version 0.5.5)

Expected: I get some output telling me what's going on
Actual: I don't get anything for a long time, until it finishes building the project

This is the output:

```
$ cargo tarpaulin
Launching test
...
```

But it took a minute or two before it printed "Launching test". I assume it was building the project, but at first I thought there was something wrong so I killed it and tried again.

(Noticed while looking at #65)

**Comment by xd009642** [comment]
I agree, I usually only judge it by my laptop fans. Just added a fix in (it's not hard tbh) so you'll see this in my next release. Or earlier if you choose to install the latest from master
