### ISSUE TITLE
0.17.0 "release" status

### ISSUE THREAD

**Issue by rayslava** [xd009642/tarpaulin#672]
Is there any reason 0.17.0 is not marked as release on GitHub?
Currently I use https://github.com/actions-rs/tarpaulin with GitHub Actions and it only supports tarpaulin versions marked as "Release", so the latest version supported is 0.16.0 and apparently there's issue which prevents it from working on my code. I checked 0.17.0 locally and it works on the same code perfectly, so I'm looking forward to enable it in CI as well.

**Comment by xd009642** [comment]
So 0.17.0 had some issues that effected a few users very consistently and were caught after release so it was yanked from crates.io and removed from github releases. The develop branch fixes most of those issues (issues with executable following and musl builds), but there's still an issue that hasn't been fixed #663. 

Once that's fixed I'll release a new version but I'm also very busy with my day job right now so things haven't moved as quickly as I'd like :disappointed:

**Comment by rayslava** [comment]
Oh, I see. Just git tag 0.17.0 which is here already, made me think that this could be kind of "forgot to press the button" issue.
Thank you.
