### ISSUE TITLE
Tarpaulin not working if absolute file path contains a dot

### ISSUE THREAD

**Issue by kaenganxt** [xd009642/tarpaulin#682]
**Describe the bug**
Running tarpaulin in my development environment worked fine, but running it on our CI platform (Jenkins) did not produce any results. Looking at the code, this is caused by the [is_hidden](https://github.com/xd009642/tarpaulin/blob/develop/src/path_utils.rs#L19) function filtering out folders starting with a dot in the absolute file path. Since Jenkins places its default workspace in `~/.jenkins/`, all files were ignored.

**To Reproduce**
Place a Cargo project inside a folder starting with a dot and run tarpaulin.

**Expected behavior**
Parent folders starting with a dot should not influence if a file is considered or not. The is_hidden function should only consider dots inside the project folder.

**Comment by xd009642** [comment]
Thanks for the issue, I've just added a fix and test for this. It might be a while until my next release (need to solve some other issues) so in the meantime you can install the latest version on the develop branch.
