### ISSUE TITLE
Report not generated when tarpaulin fails because of `--fail-under`

### ISSUE THREAD

**Issue by acrrd** [xd009642/tarpaulin#691]
**Describe the bug**
When I run `cargo tarpaulin -o html --fail-under 100` the program fails and the report is not generated, If I reduce the threshold to a value that allow the tarpaulin to succeeds the report is generated.

**To Reproduce**
Run the program with the option to generate the report and `--fail-under` with a percentage that will make `tarpaulin` to fail.

**Expected behavior**
I expect to have a report also if the coverage is under the desired percentage.

**Comment by xd009642** [comment]
So I've just pushed a branch to fix this, if the CI passes them I'll merge into develop and you'll be able to use it in the next release or by installing from the branch.

**Comment by acrrd** [comment]
Thanks!
