### ISSUE TITLE
0.18-alpha1 fails in CI with actions-rs/tarpaulin

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#705]
Several of my projects are using [actions-rs/tarpaulin](https://github.com/actions-rs/tarpaulin) which in its default configuration pulls the latest release.

Since 0.18-alpha1 was released, all my CI coverage jobs started failing with a failure to compile the tests, and an error message like this:

```
Mar 01 14:40:14.455 ERROR cargo_tarpaulin: Failed to compile tests! Error: signals: linking with `cc` failed: exit code: 1
```

This for example this run : https://github.com/Smithay/calloop/runs/2004759169

Weirdly enough, it does not fail when I install & run tarpaulin locally on my computer.

So, my immediate fix has been to restrict actions-rs/tarpaulin to using version 0.16, but I guess this is something that would be worth investigating.

**Comment by xd009642** [comment]
Interesting, the only rustflag I've removed is the dynamic-relocation-mode between the two versions. I'll have a look and see if I can figure it out

**Comment by xd009642** [comment]
Well this is fun it compiled and ran perfectly on my local machine :disappointed:

**Comment by vberger** [comment]
Yes, same issue, it only happens on the CI, not on my local machine.

But it occurred both for calloop and wayland-rs, which are not directly related (neither depend on the other).

**Comment by xd009642** [comment]
Okay, if I remove the target directory, cargo test, then cargo tarpaulin it causes it to happen.. I'm going to raise an issue on cargo because I have a feeling this is more a rust/cargo issue than a me issue though I'm causing it by my usage :thinking:

**Comment by xd009642** [comment]
https://github.com/rust-lang/cargo/issues/9220 okay I've raised this issue.

One potential solution is to get rid of `cargo test` and just run tarpaulin. Tarpaulin will return the same exit code as cargo test (provided it doesn't fail itself then it returns non-zero). Depends if you're happy with having to check if it's tests or coverage that fail via logs

**Comment by vberger** [comment]
Oh, interesting. Furthermore, if we do the reverse (`cargo clean`, then `cargo tarpaulin`, then `cargo test`), then `cargo test` fails with a more detailed error. For example on calloop I get `undefined reference to `core::ptr::drop_in_place'`.

**Comment by vberger** [comment]
> One potential solution is to get rid of cargo test and just run tarpaulin.

Indeed yes. Though attempting that on `calloop` I observe that one of the tests fails when run with tarpaulin, but not in `cargo test`...

**Comment by xd009642** [comment]
oh really they all passed for me? Or do you ignore that test when tarpaulin is ran

**Comment by vberger** [comment]
The `loop_logic::tests::insert_bad_source` test always fails when running tarpaulin on calloop on my local computer.

Its contents basically boil down to feeding a bogus file descriptor (`42`) to `epoll` and checking that it returns an error (but with some abstraction logic around that). Would running the tests in tarpaulin cause the process to have several FDs open by chance?

**Comment by xd009642** [comment]
Hmm I don't know of any reason tarpaulin would leave several FDs open, and it passed on my machine in tarpaulin... It's probably going to be something tricky at the OS/system level :grimacing:

**Comment by vberger** [comment]
But does it open FDs at all, even without leaking them? Depending on how many tests are ran concurrently, this might be enough to trigger this failure on some computer and not others.

**Comment by xd009642** [comment]
I end up opening all the source files once, and each binary gets opened to read the dwarf info before launching the test in question. Aside from that and writing any report output I don't think there is anything else. Unless you're doing doc test coverage then opening files containing doctests to check for should_panic attributes

**Comment by xd009642** [comment]
Well this has lead me to realising that my `--force-clean` option is a no-op. Something I clearly didn't full port when I transitioned from using cargo as a binary instead of as a library. So may not be intentional but this issue has lead me to a different one no ones spotted yet

**Comment by xd009642** [comment]
Okay this should hopefully go away in the text cargo release! https://github.com/rust-lang/cargo/issues/9220

**Comment by xd009642** [comment]
I've released an alpha2 that turns on cleaning by default, there's also a rustc PR merged that will fix incremental compilation when link-dead-code is enabled and will reach stable in 1.53.0 - so a few releases after that I'll look at changing the default back to reduce run times again
