### ISSUE TITLE
Update dependencies for Debian

### ISSUE THREAD

**Issue by apeduru** [xd009642/tarpaulin#74]
I am running Debian 9.2 and I was missing a couple of packages in order to install `cargo-tarpaulin`. I'd like to update the README to include `apt-get update && apt-get install libssl-dev pkg-config cmake zlib1g-dev` as part of the requirements for installation.

**Comment by xd009642** [comment]
That would be great. Anything that makes it easier for users to get up and running is fine with me :+1:

**Comment by apeduru** [comment]
Do I need r/w permissions for this repo? I can't seem to push a branch.

**Comment by xd009642** [comment]
Closed following merge of #75
