### ISSUE TITLE
support for macbook m1

### ISSUE THREAD

**Issue by GopherJ** [xd009642/tarpaulin#741]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/33961674/115645238-9822df00-a352-11eb-9d25-6e0484baada4.png">

**Comment by GopherJ** [comment]
currently when I run cargo install cargo-tarpaulin on macbook pro m1, it fails to compile

**Comment by xd009642** [comment]
So currently tarpaulin only works on x64 linux. The 0.18.0 alpha releases (alpha1 and alpha2) shoul compile but they'll just print out a message saying there's no tracing engine supported for the system
