### ISSUE TITLE
a significant increas in false negatives with 0.18.0-alpha3

### ISSUE THREAD

**Issue by Licenser** [xd009642/tarpaulin#757]
Updating from 0.16 to 0.18.0-alpha 3 introduces a significant number of new false negatives https://coveralls.io/builds/39571774 is a full set of newly uncovered code but I'll try to call out the biggest ones

* `loop` and `break` are not covered
* the match head (i.e. `match ... {`)
* Some multi-line match statements ( https://coveralls.io/builds/39571774/source?filename=tremor-script%2Fsrc%2Fast%2Fanalyzer.rs#L74 for example )
* multi-line match patterns ( https://coveralls.io/builds/39571774/source?filename=tremor-value%2Fsrc%2Fserde%2Fvalue%2Fse.rs#L378 )
* some const expression in touple construction ( https://coveralls.io/builds/39571774/source?filename=src%2Furl.rs#L87 )

**Comment by xd009642** [comment]
Now on 0.24.0 and have `--engine llvm` so I'm going to close this as it's hopefully outdated - a lot of people have reported llvm coverage improving results accuracy a bunch as well :pray:
