### ISSUE TITLE
Dockerfile fails ot produce XML output

### ISSUE THREAD

**Issue by bjchambers** [xd009642/tarpaulin#768]
**Describe the bug**

Trying to use docker to run tarpaulin and produce XML fails.

**To Reproduce**

```
docker run --security-opt seccomp=unconfined -v "${PWD}:/volume:rw" \
  xd009642/tarpaulin:develop-nightly \
  cargo build && cargo tarpaulin --out Xml
```

Produces the error: `Error: "Failed to report coverage! Error: Failed to create run report"`.

No additional information is logged about why it failed. It had even produced coverage information already.

If I specify `--output-dir=/volume` the error changes to `Error: "Failed to create or locate custom output directory: Some(\"/volume\")"`

**Expected behavior**

The output file added to my local directory.

**Comment by mars64** [comment]
I believe this issue is around docker command chaining, the following seems to work for me: 

```
docker run --security-opt seccomp=unconfined -v "${PWD}:/volume:rw" \                                                                                                                                                                                                                                                                                
  xd009642/tarpaulin:develop-nightly \
  /bin/bash -c "cargo build && cargo tarpaulin --out Xml"
```

**Comment by bjchambers** [comment]
Whoops! Indeed it is. Thanks!
