### ISSUE TITLE
fails on travis with ASLR disable failed: EPERM

### ISSUE THREAD

**Issue by kdy1** [xd009642/tarpaulin#77]
```
0.42s$ bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
cargo-tarpaulin
after_success.2
178.59s$ cargo tarpaulin --out Xml &&
    bash <(curl -s https://codecov.io/bash)
    
Building project
Launching test
ASLR disable failed: EPERM: Operation not permitted
thread 'main' panicked at 'Failed to trace: Sys(EPERM)', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Unexpected grab
Error while collecting coverage. EPERM: Operation not permitted
Coverage Results
#
# Omitted 
#
0.00% coverage, 0/302 lines covered
Tarpaulin finished
```

Travis log: https://travis-ci.org/swc-project/swc/builds/328637807#L2967

I use nightly

**Comment by kdy1** [comment]
Closing because it seems like a issue of travis. 

https://github.com/travis-ci/travis-ci/issues/9061

**Comment by philipc** [comment]
Possible workaround is running with `sudo: required` so it's not using containers. I think tarpaulin could avoid needing to disable ASLR with some effort (something like https://github.com/gimli-rs/findshlibs might help).

**Comment by kdy1** [comment]
Oh.. that worked. Thank you.

**Comment by xd009642** [comment]
@philipc thanks for the help, I'll make an issue for looking into using findshlibs to improve tarpaulin. Any input you might have would be appreciated :smile:  

I've also added sudo:required to the example travis.yml in the README so new users don't hit this problem as well.

**Comment by rfdonnelly** [comment]
@xd009642, I setup cargo-tarpaulin using the README on crates.io and ran into this issue since the crates.io README doesn't yet have this change.  Please consider bumping the version to update the crates.io README.

BTW, I discovered cargo-tarpaulin from your recent reddit post.  I was looking for a coverage solution and was turned off by the complex setup of kcov.  Cargo-tarpaulin is so much slicker!

**Comment by xd009642** [comment]
Thanks for the compliment :smile: I did consider releasing a patch so crates.io is up-to-date but latest stable is out Feb 4th iirc and I'm hoping to actually have some more features to merge in. And that way I don't have to do another release to get rid of the warning about stable Rust!

**Comment by Marwes** [comment]
Seeing this issue on travis as well https://travis-ci.org/Marwes/combine/jobs/356101326#L946 I believe a fix for this hasn't been released(?)

**Comment by rfdonnelly** [comment]
@Marwes you need sudo on Travis.  Update your `.travis.yml` per https://github.com/xd009642/tarpaulin/commit/1b8bf6c5623cdee291ae7f6589105e8784fe4712

**Comment by Marwes** [comment]
@rfdonnelly Yeah I saw that but https://github.com/xd009642/tarpaulin/issues/77#issuecomment-357495278 and https://github.com/xd009642/tarpaulin/issues/77#issuecomment-359521890 seems to indicate that there is a solution that does not require sudo. (Going to add `sudo: required` but it would better if that wasn't necessary)

**Comment by rfdonnelly** [comment]
@Marwes My understanding is that there is no solution for Travis that does not require sudo.

* https://github.com/xd009642/tarpaulin/issues/77#issuecomment-357495278 mentions a possible solution that does not seem to have been explored further.
* https://github.com/xd009642/tarpaulin/issues/77#issuecomment-359521890 does not refer to no-sudo solution.

**Comment by xd009642** [comment]
Agree with @rfdonnelly sudo is required sorry about that

**Comment by sharksforarms** [comment]
This is unfortunate, trying to use tarpaulin in my Jenkins environment, cargo does not play nice with sudo

**Comment by new-commer** [comment]
I encountered the same error.
I have tried using sudo. like `sudo -E cargo tarpaulin ` , it do not work 
Is there anyone can tell me how to resolve it ?

**Comment by philipc** [comment]
@new-commer You shouldn't be using sudo to run tarpaulin. The workaround is to put `sudo: required` in your `.travis.yml`. The effect of the workaround is to disable use of containers in travis. If you're not using travis, then you'll need to find some other way to disable containers.

**Comment by new-commer** [comment]
@philipc  Thanks for reply 
`The workaround is to put sudo: required in your .travis.yml`
Do you mean modify `.cargo/registry/src/github.com-*/cargo-tarpaulin-*/.travis.yml` ?
I saw it already have `sudo: required`  setting. Or there is another `.travis.yml` ? 
And sorry, I don't know much about travis , what is `travis` , i just run tarpaulin in gitlab ci.

**Comment by philipc** [comment]
travis is like gitlab ci, so the problem is the same, but the fix will be different. The problem is that containers (such as docker) normally have ASLR enabled, but tarpaulin can't work with ASLR. You'll need to figure out either how to run tarpaulin without docker, or how to configure docker to allow tarpaulin to disable ASLR (maybe there's a seccomp setting for this, I'm not familiar with it though).

**Comment by mgeisler** [comment]
Just a note that CircleCI fails the same way: https://circleci.com/gh/mgeisler/textwrap/58. It has worked very well for me until recently.

I've raised the issue in their discussion forum: https://discuss.circleci.com/t/cargo-tarpaulin-fails/30215. Perhaps they'll be able to fix this on their side, which would give us an easy way to run Tarpaulin again.

**Comment by rdaniels6813** [comment]
Workaround on CircleCI is to use `machine: true` and call the docker command directly with the `--security-opt seccomp=unconfined` flag.

An example of this can be found here: https://github.com/bittrd/rust-hello-world/blob/f8840e431009843d7bee652265230cc3fa0f3002/.circleci/config.yml#L38

**Comment by xd009642** [comment]
@rdaniels6813 oh thanks for that I'll add a note to the README :+1:

**Comment by mgeisler** [comment]
I ended up using the following CircleCI configuration for [textwrap][1]:
```
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Pull xd009642/tarpaulin
          command: docker pull xd009642/tarpaulin
      - run:
          name: Generate coverage report
          command: >-
            docker run --security-opt seccomp=unconfined
            -v $PWD:/volume xd009642/tarpaulin
            cargo tarpaulin --out Xml --all-features
      - run:
          name: Upload to codecov.io
          command: bash <(curl -s https://codecov.io/bash) -Z -f cobertura.xml
```

This way only the `cargo tarpaulin` step is run in the Docker container and the whole pipeline takes about 2-3 minutes on my textwrap project.

[1]: https://github.com/mgeisler/textwrap/blob/master/.circleci/config.yml
