### ISSUE TITLE
Does tarpaulin work with rustdoc::all?

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#773]
https://github.com/jonhoo/griddle/pull/19

**Comment by pedromfedricci** [comment]
Hey! I just pulled the latest tag: xd009642/tarpaulin:latest, and the rustc in it is 1.51.0.
rustdoc::all was introduced in 1.52.0 -> [#82798](https://github.com/rust-lang/rust/pull/82798),
so i guess that's why it will fail to compile if the docker image is used?
ty for checking it!

**Comment by xd009642** [comment]
Ah brilliant I was just about to pull the image and see what the rust version was! I'll trigger a rebuild so it will update the compiler version 👍
