### ISSUE TITLE
Builds are always from-scratch

### ISSUE THREAD

**Issue by mathstuf** [xd009642/tarpaulin#777]
**Describe the bug**
I have updated to `master` as of this morning and every build now starts with a clean build. I do have `RUSTC_WRAPPER` set to `sccache`, but unsetting it doesn't change the behavior.

**To Reproduce**
`cargo tarpaulin -- $testname` to iterate on a single test. After the update to 06a5d38ddf5f3380860fcfb63479491515a3fc60, every run now starts from scratch.

**Expected behavior**
Eliding already completed work should be fine.

**Comment by xd009642** [comment]
There is `--skip-clean` unfortunately, there was a bug in rustc that changing `-C link-dead-code` and building a project without changing the code resulted in a compilation failure making cleaning a necessity. But if you put tarpaulin build artefacts in a different target directory (or only run tarpaulin) on the project you can safely use `--skip-clean`

**Comment by mathstuf** [comment]
Ah, OK. So I guess the wrong directory was then just a red herring allowing me to avoid that corner case. I do have `export CARGO_TARPAULIN_TARGET_DIR="target/tarpaulin"` set up, so I'll also hook up `--skip-clean`.
