### ISSUE TITLE
Look into removing need to disable ASLR

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#78]
Look into  https://github.com/gimli-rs/findshlibs as an approach to remove the need to disable ASLR. This should lead to improvements in binary parsing, ensure that `sudo: required` isn't required for travis to work consistently and mitigates the risk of some linux distros restricting calls to `personality` for security reasons (I vaguely recall seen some distros aimed at servers do this).

**Comment by philipc** [comment]
I don't think findshlibs will help here since it only works for the current process. Sorry for the misinformation.
