### ISSUE TITLE
The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101

### ISSUE THREAD

**Issue by GopherJ** [xd009642/tarpaulin#783]

**Comment by GopherJ** [comment]
https://github.com/parallel-finance/parallel/runs/2937715563?check_suite_focus=true

**Comment by xd009642** [comment]
So looks like semver requires rustc 1.53 now, I raised an issue to see if they'll change the lines that cause it and if they do I'll push a new release. Otherwise I'll look into alternatives or patches https://github.com/dtolnay/semver/issues/249

**Comment by xd009642** [comment]
you could also resort to the docker image or downloading the prebuilt version off github releases via `bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)` in the meantime

**Comment by xd009642** [comment]
https://github.com/dtolnay/semver/issues/249 If you are pinning an old nightly I'd just recommend upgrading or pinning tarpaulin to 0.16.0.
