### ISSUE TITLE
Displays coverage results for dependency, not for crate itself

### ISSUE THREAD

**Issue by lexxvir** [xd009642/tarpaulin#8]
Hi,

I've tried version 0.3.6 with my [crate](https://github.com/lexxvir/tlv-parser) and got following result:

```
± cargo tarpaulin              
Launching test

running 4 tests
test tlv::tests::find_val_test ... ok
test tlv::tests::from_vec_test ... ok
test tlv::tests::tag_len_test ... ok
test tlv::tests::to_vec_test ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Launching test

running 1 test
test quickcheck_from_vec ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Coverage Results
target/debug/build/backtrace-17fa5380aeaf9437/out/capture.rs: 17/80

21.25% coverage, 17/80 lines covered
```

As you can see tarpaulin reports about [backtrace](https://crates.io/crates/backtrace) crate not about tlv-parser crate.
[backtrace](https://crates.io/crates/backtrace) is dependency of [error-chain](https://crates.io/crates/error-chain) that is dependency of tlv-parser.

**Comment by xd009642** [comment]
Hi lexxvir, this is related to #10, I've cloned your crate and will use it as one of my test projects to make sure I've fixed this and let you know when I've sorted it

**Comment by xd009642** [comment]
0.3.7 is out, do you mind trying it for me? Something is up with my rustup and it's not switching to nightly so I haven't been able to properly test your project

**Comment by lexxvir** [comment]
I have tested 0.3.8. It seems all woks well now:
```
Coverage Results
tests/lib.rs: 11/13
src/tlv.rs: 153/254
src/errors.rs: 0/2
target/debug/build/backtrace-17fa5380aeaf9437/out/capture.rs: 17/80
```

Little strange that file from backtrace crate placed into results..

But anyway, thank you for fix!

**Comment by xd009642** [comment]
I think it's because the source is in a child directory of the project manifest. I'll add a filter to ignore any source in the target filter and that should resolve that last little issue.

**Comment by xd009642** [comment]
So this is weird, I got nightly rerunning with the aim of seeing why the backtrace crate source ends up in the results and this is my tarpaulin output.

```
cargo tarpaulin
Launching test

running 4 tests
test tlv::tests::find_val_test ... ok
test tlv::tests::from_vec_test ... ok
test tlv::tests::tag_len_test ... ok
test tlv::tests::to_vec_test ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Launching test

running 1 test
test quickcheck_from_vec ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Coverage Results
src/tlv.rs: 155/254
src/errors.rs: 0/2
tests/lib.rs: 11/13

61.71% coverage, 166/269 lines covered
```

Is there anything atypical in your setup that I wouldn't have on my system from simply cloning the repo? I'm just going to reopen this issue for now because I'm not happy it's fully fixed yet.

**Comment by lexxvir** [comment]
I've done some investigation and more probably the cause was a version of backtrace crate.
Initially my working copy contains Cargo.lock with backtrace 0.3.0.
I ran cargo update and backtrace version changed to 0.3.2. After that cargo tarpaulin prints results similar to yours:
```
± cargo tarpaulin
Launching test

running 4 tests
test tlv::tests::find_val_test ... ok
test tlv::tests::from_vec_test ... ok
test tlv::tests::tag_len_test ... ok
test tlv::tests::to_vec_test ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Launching test

running 1 test
test quickcheck_from_vec ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

Coverage Results
src/tlv.rs: 156/254
src/errors.rs: 0/2
tests/lib.rs: 11/13

62.08% coverage, 167/269 lines covered
```

Remain difference in covered lines in src/tlv.rs:
* your version 155 lines
* mine working copy version 156 lines
* mine clean git checkout 152 lines

**Comment by xd009642** [comment]
Cool, good to know the lock file affects the project in that way. As for the differences, tarpaulin doesn't always catch closing braces from looking at different projects on different systems that's typically the difference. It's a minor issue and on my list.

**Comment by lexxvir** [comment]
Ok, so I think it may be closed now.
