### ISSUE TITLE
Integration testing: Interactive programms

### ISSUE THREAD

**Issue by bewee** [xd009642/tarpaulin#827]
**Describe the bug**

Spawning a process for an interactive main programm during integration testing and then communicating with it (e.g. via stdin/stdout) leads to falsely uncovered lines.

Same happens when similarly testing routes of a web server program (my original problem). However, there I even experience tarpaulin crashing ("Failed to get test coverage! Error: ESRCH: No such process"). Although I can imagine this having a similar cause, I should maybe open a separate issue?

**To Reproduce**

src/main.rs
```rust
fn main() {
    loop {
        let mut buffer = String::new();
        io::stdin().read_line(&mut buffer).unwrap();
        print!("Received {}", buffer);
    }
}
```

tests/tests.rs
```rust
#[test]
fn test() {
    let mut child = Command::new("./target/debug/main")
        .stdout(Stdio::piped())
        .stdin(Stdio::piped())
        .spawn()
        .unwrap();
    let mut stdin = child.stdin.take().unwrap();
    let mut stdout = child.stdout.take().unwrap();
    let t = thread::spawn(move || {
        let mut reader = BufReader::new(&mut stdout);
        let mut buff = String::new();
        reader.read_line(&mut buff).unwrap();
        assert_eq!(buff, "Received asdf\n");
    });
    let mut writer = BufWriter::new(&mut stdin);
    writer.write_all(b"asdf\n").unwrap();
    writer.flush().unwrap();
    t.join().unwrap();
    child.kill().unwrap();
}
```

Running `cargo tarpaulin --follow-exec`

Output: 
```
INFO cargo_tarpaulin::report: Coverage Results:
|| Tested/Total Lines:
|| src/main.rs: 0/4 +0.00%
|| tests/tests.rs: 15/15 +0.00%
|| 
78.95% coverage, 15/19 lines covered, +0% change in coverage
```

Distro: Ubuntu 20.04
Rustc version: 1.57.0-nightly (b69fe5726 2021-09-10)

**Expected behavior**

100% coverage

**Comment by bewee** [comment]
Ok, turns out that the `child.kill()` caused all those problems. Similar to https://github.com/xd009642/tarpaulin/issues/252#issuecomment-730319104, I added an exit route to my project (hidden behind a feature flag) which I now use instead. I don't like this hack very much, but for now it works.

**Comment by xd009642** [comment]
Ah glad you found it, I figured seeing the initial email in my inbox it would be the kill. I have some idea on how to solve this, generally by catching the kill signal from the test forwarding and marking that the binary is expected to exit not-of-its-own-volition. I'll update you when I've had a chance to work on this and if I make any progress

**Comment by xd009642** [comment]
I did fix some kill based thing in 2022 iirc hopefully this is now solved :crossed_fingers: if not feel free to reopen
