### ISSUE TITLE
Compiler error with nightly running on travis-ci

### ISSUE THREAD

**Issue by xmclark** [xd009642/tarpaulin#83]
I am having an issue when running tarpaulin on travis-ci using rust nightly 1.25.

I have a rust project with a travis ci file that looks like this:
```
sudo: required
language: rust
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - nightly
before_script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install cargo-update || echo "cargo-update already installed"
  - cargo install-update -a # update outdated cached binaries
os:
  - linux
  - osx
script:
  - |
      cargo clean &&
      cargo build &&
      cargo test
after_success:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
      cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
    fi
```

When it gets to the after_success script, it barfs with:
```
cargo-tarpaulin
Building project
error: internal compiler error: librustc/ty/subst.rs:424: Region parameter out of range when substituting in region 'a (root type=Some(unsafe fn(*mut <Self as foreign_types::ForeignTypeRef>::CType) -> &'a mut Self {<Self as foreign_types::ForeignTypeRef>::from_ptr_mut::<'a>})) (index=1)
thread 'rustc' panicked at 'Box<Any>', librustc_errors/lib.rs:476:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.25.0-nightly (21882aad7 2018-01-28) running on x86_64-unknown-linux-gnu
```

**Comment by xmclark** [comment]
I switched to stable rust and I get no compilation errors. I saw your reference to [keygraph-rs](https://github.com/xd009642/keygraph-rs) and noticed it was working correctly on stable. 

This is good news and much preferred, but I was surprised since the readme says at the very top to use nightly rust. Maybe that should get updated. Regardless, I think this issue could be closed.

**Comment by xd009642** [comment]
It's now nightly or beta, it will compile however code that's not used may not be linked in stable meaning coverage results will be wrong. 

I'll look into this properly when I get home from work later :+1:

**Comment by xd009642** [comment]
So one thing I noticed that's in my recommended travis.yml is the absence of `dist: trusty` the issue doesn't exist on my machine so I'm forking your project to have a play and see what I can uncover. Given rustc panicked it's probably worth getting the backtrace and raising an issue in rust-lang/rust since the compiler shouldn't panic. (Though I can do that if I uncover anything)

**Comment by xd009642** [comment]
Right it worked on nightly with `dist: trusty` on my fork. I'm removing that line though to see if I can recreate the rustc crash just cause the compiler team will probably be interested in that!
