### ISSUE TITLE
Update warning text for compiler issues

### ISSUE THREAD

**Issue by hcpl** [xd009642/tarpaulin#85]
We can with certainty limit the range of versions with regressions in `README.md` to at least stable 1.23.0 and nightlies from `nightly-2017-11-09` to `nightly-2018-01-04` inclusive.

Current situation:
- on stable, only `1.23.0` is affected;
- on beta, this is probably fixed by backporting from nightly:
  <details>
  <summary>Output from beta</summary>

  ```
  $ rustc +beta --version
  rustc 1.24.0-beta.11 (03f456d3c 2018-02-03)
  $ cargo +beta tarpaulin
  Building project
  Launching test
  running /tmp/rust/footest/target/debug/deps/footest-f73228ca8200cacb

  running 1 test
  .
  test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

  Coverage Results
  src/lib.rs: 4/6

  66.67% coverage, 4/6 lines covered
  Tarpaulin finished
  ```
  </details>

  This means we may expect this issue fixed in `1.24.0`, yay.
- on nightly, regression was introduced on `nightly-2017-11-09` and seemingly fixed on `nightly-2018-01-05`:
  <details>
  <summary>Output from nightly-2017-11-08</summary>

  ```
  $ cargo +nightly-2017-11-08 tarpaulin
  Building project
  Launching test
  running /tmp/rust/footest/target/debug/deps/footest-aa824eed01067652

  running 1 test
  .
  test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

  Coverage Results
  src/lib.rs: 4/6

  66.67% coverage, 4/6 lines covered
  Tarpaulin finished
  ```
  </details>
  <details>
  <summary>Output from nightly-2017-11-09</summary>

  ```
  $ cargo +nightly-2017-11-09 tarpaulin
  Building project
  Launching test
  running /tmp/rust/footest/target/debug/deps/footest-57ce85339063166d

  running 1 test
  .
  test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

  Coverage Results
  src/lib.rs: 4/4

  100.00% coverage, 4/4 lines covered
  Tarpaulin finished
  ```
  </details>
  <details>
  <summary>Output from nightly-2018-01-04</summary>

  ```
  $ cargo +nightly-2018-01-04 tarpaulin
  Building project
  Launching test
  running /tmp/rust/footest/target/debug/deps/footest-19f7079bab746531

  running 1 test
  .
  test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

  Coverage Results
  src/lib.rs: 4/4

  100.00% coverage, 4/4 lines covered
  Tarpaulin finished
  ```
  </details>
  <details>
  <summary>Output from nightly-2017-01-05</summary>

  ```
  $ cargo +nightly-2018-01-05 tarpaulin
  Building project
  Launching test
  running /tmp/rust/footest/target/debug/deps/footest-fbdfce5dea4b0160

  running 1 test
  .
  test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

  Coverage Results
  src/lib.rs: 4/6

  66.67% coverage, 4/6 lines covered
  Tarpaulin finished
  ```
  </details>

For outputs above, I used a small project with a `src/lib.rs` only:
```rust
pub fn foo(a: usize) -> Option<usize> {
    a.checked_add(100)
}

pub fn bar(b: u8) -> u8 {
     b.checked_add(128).unwrap_or(128)
}


#[cfg(test)]
mod tests {
    #[test]
    fn test_foo_0() {
        assert_eq!(::foo(0), Some(100));
    }
}
```

I'm not sure if the fix made between `nightly-2018-01-04` and `nightly-2018-01-05` really solves every affected case though, since the code I used can be too simplistic.

**Comment by hcpl** [comment]
Also, this issue clarifies https://github.com/xd009642/tarpaulin/issues/70.

**Comment by xd009642** [comment]
Updated the text with the version of nightly it was fixed it :+1:

**Comment by hcpl** [comment]
Thanks!
