### ISSUE TITLE
Ability to use --all-features mirroring 'cargo build --all-features'

### ISSUE THREAD

**Issue by daboross** [xd009642/tarpaulin#86]
This would just be a small syntax enhancement.

`cargo build --features "x y z"` has an analog which enables all features the project defines, `cargo build --all-features`. It would be nice if `cargo tarpaulin --all-features` did this as well, enabling all features.

**Comment by xd009642** [comment]
Agreed and adding, I'll let you know when it's done

**Comment by xd009642** [comment]
Right this is done and in develop, it'll be available in the next release or you can use it earlier if you use cargo install and specify this repository and the develop branch! Thanks for the issue :+1:

**Comment by daboross** [comment]
Thank you for the quick response! It's a pleasure using the library.

**Comment by xd009642** [comment]
No problem as issues go this was really simple!
