### ISSUE TITLE
Generating coverage xml of a library that has examples produces line-rate=NaN

### ISSUE THREAD

**Issue by flaminggoat** [xd009642/tarpaulin#869]
**Describe the bug**
Running with arguments `--out Xml` on a library containing an examples folder produces a section in the cobertura.xml:
```
        <package name="examples" line-rate="NaN" branch-rate="0" complexity="0">
            <classes></classes>
        </package>
```
This causes the overall line-rate to be NaN too.

**Expected behavior**
Coverage for the examples should just be 0 if there are no tests.

**Comment by xd009642** [comment]
I've just found the offending code in question and when the CI finishes I'll merge into develop and probably do a new patch release :+1:

**Comment by xd009642** [comment]
And I'm an idiot who didn't actually commit and push their change...  I did recreate and test on a recreation project and confirm it but here's the actual code change PR https://github.com/xd009642/tarpaulin/pull/871

**Comment by xd009642** [comment]
I will also do that release tonight for version 0.18.4

**Comment by flaminggoat** [comment]
Thanks, It no longer generates NaN on my repo.
