### ISSUE TITLE
Add option to get coverage from examples (and maybe benchmarks)

### ISSUE THREAD

**Issue by daboross** [xd009642/tarpaulin#87]
I'm 90% sure that's what's happening, at least!

I have both a `tests/meta_logging.rs` file and `examples/meta-logging.rs`. None of the examples, including meta-logging, are actually run - but `meta-logging` is reported in results, so I assume this has to do with it having the same name as `tests/meta_logging`.

Here's the reported coverage:

```
Coverage Results
examples/meta-logging.rs: 0/1
src/builders.rs: 80/155
src/colors.rs: 6/44
src/errors.rs: 0/16
src/lib.rs: 2/2
src/log_impl.rs: 146/214
tests/channel_logging.rs: 9/9
tests/file_logging.rs: 38/40
tests/global_logging.rs: 37/39
tests/meta_logging.rs: 24/25
tests/support.rs: 2/2
```

Build log: https://travis-ci.org/daboross/fern/jobs/341220471

`meta_logging` is run, but it's the test meta_logging, not the example. Would be cool if examples could be run! But in the meantime, I thought it would be best to report this mis-reporting.

**Comment by xd009642** [comment]
So I've implemented ignoring the examples folder as they aren't ran, just looking into cargo documentation to see how easy to get examples instrumented and running. If i'ts quick and easy I'll do it otherwise I'll merge into develop, rename this issue to examples coverage and mark it as an enhancement :+1:

**Comment by xd009642** [comment]
Yeah it looks like it might be a faff, I'll try some things out but in the meantime I've pushed to develop so you can get this fix via cargo install from the repo. I've renamed the issue and put as an enhancement and also thought, if people may want coverage of examples they may also want coverage of their benchmarks as well!

**Comment by daboross** [comment]
Cool, thanks! Running examples isn't essential for me, but it would be nice to see if they're contributing to more coverage than just tests - I run the examples in CI as well as tests for some of my repositories.

**Comment by xd009642** [comment]
I've got coverage of benchmarks now but not examples and there is a more recent issue asking for that specifically so closing this as duplicate
