### ISSUE TITLE
Look into moving from syntex_syntax to syn 

### ISSUE THREAD

**Issue by xd009642** [xd009642/tarpaulin#88]
As syntex_syntax is no longer maintained consider moving syntax analysis over to use the syn crate. Syn may not be suitable so some investigation may have to occur.

**Comment by CAD97** [comment]
Ooh, this looks fun. I've already overloaded myself <sup><sub>(need to update two projects building against nom 4-alpha to nom 4-beta, a few outstanding PRs need finalization work, and real world responsibilities)</sub></sup> so I can't really promise anything, but I'll definitely share back if/when I do try something.

This comment is mainly so that GH marks this issue for me.

**Comment by xd009642** [comment]
Awesome, if you do get to it all the code in question is in src/source_analysis.rs and doesn't leak out anywhere else :+1:

**Comment by xd009642** [comment]
@CAD97 just wondering how likely you are to do this? The new nested imports trigger a panic in syntex so it's moved up the priority of this issue.

**Comment by CAD97** [comment]
(whoops)

This dropped below my radar recently; I mostly forgot about it.
A very small part of the start of the port is available at my branch's develop (as soon as I rebase onto it, anyway).

The interesting part is going to be moving away from `syntax::CodeMap`, as as far as I can tell, `syn` doesn't have an equivalent... The `Visit` transformation should mostly be mechanical.

**Comment by xd009642** [comment]
That doesn't sound too bad if `Visit` is fairly straight forward. If you'd like me to look into anything or explain any parts of tarpaulins rules let me know.

Also, don't forget to move over the tests as well, there's a bit of fiddling with `CodeMap` etc to avoid needing actual files to run the tests and keeping it all in memory! :+1:

**Comment by CAD97** [comment]
Well, I tried to link it, just to try it out, but something went wrong...

```
error[E0463]: can't find crate for `rustc_ap_syntax`
 --> src\lib.rs:4:1
  |
4 | extern crate rustc_ap_syntax;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

It is in `Cargo.toml` and even got built, so I don't know why it's complaining. Moving over to `syn` is the better move, in any case.

**Comment by xd009642** [comment]
I decided to play around and try it out to see if it was a fit and hit that as well, the crate name is actually `syntax`. I managed to get it to this point in about 20 minutes of work just fixing the pathbuf changes in the API 4b137aee13ab0f000af8c964841c2208529b0a21 had to go back to version 55.0.0 cause it's updated every rustc update regardless on whether they touch syntax!

If you're still interested in this, it would be probably best to pull my latest changes and work on the `rustc_syntax_switch` branch. Some methods have been removed from span and generics have completely changed so there's still a big chunk to do I just picked off the easy parts :smile: 

Also, the documentation is the syntax modules in the compiler, just a forewarning (although docs.rs might have autogenned ones for 55.0.0 I didn't actually check...)

**Comment by xd009642** [comment]
So I had the same thought with rustc-ap-syntax because the new nested imports cause a panic in syntex so it's fairly important an update gets out soonish before people start having to customise rustfmt defaults to get tarpaulin to work. I try to keep things working on stable as well, but once `proc_macro` is stable if you're interested in revisiting this I'm interested on whether it improves things. Plus it'll be more stable that the rustc internals!

In the meantime I'll continue with the generics/span/test porting that's left to do! Thanks for taking a look at this :+1:

**Comment by xd009642** [comment]
Moved it all to syn! Closing
