### ISSUE TITLE
Is it possible to support function coverage?

### ISSUE THREAD

**Issue by heisen-li** [xd009642/tarpaulin#897]
The result I got after running is only the row coverage, which is not enough in my work.
Branch coverage is in the roadmap, so is there a similar plan for function coverage?

**Comment by xd009642** [comment]
It's definitely possible, just no ones asked for it before! I guess the big questions would be how would the UX look like for function coverage, especially how would it interact with the current reporting types: coveralls, cobertura, lcov, etc.

I could probably quite trivially map the entire span of a function to a single logical line and then any lines hit in a function would be mapped to the first line of the function. But I'd rather not jump straight into the simplest solution in case it ends up being bad :sweat_smile:. 

Do you have any idea how you'd want this to look? And also anymore insights on your use case?

**Comment by xd009642** [comment]
So there is function coverage available via the lcov reports. It'll take a bit of post-processing but I do have the list of function names and number of times they're called so it's work-out-able for those who want to do some manual work.

If someone wants a less-manual reporting of this feel free to comment on this issue and I'll reopen it.
