### ISSUE TITLE
Docker nightly support

### ISSUE THREAD

**Issue by rubdos** [xd009642/tarpaulin#90]
Currently working on a project that depends on some nightly features (`impl Trait`, amongst others).

It would be nice if there was a Docker container tag that contains a tarpaulin version compiled on Rust nightly, e.g., `docker pull xd009642/tarpaulin:nightly`.

**Comment by xd009642** [comment]
This does sound like a good idea, I'll make sure to provide an image built on nightly with my next release (whenever that may be)!

**Comment by xd009642** [comment]
@robinst given you contributed the dockerfile for tarpaulin and I've no clue about docker do you fancy helping with this? No pressure I'm sure I can figure it out if you're busy!

**Comment by robinst** [comment]
Looks like we could use the nightly base image for that: https://hub.docker.com/r/rustlang/rust/

So we'd probably want to have two images, one that is based on stable rust, and another one on nightly. It looks like you could set that up by:

* Copying the `Dockerfile` to `Dockerfile-nightly`
* Changing the first line in `Dockerfile-nightly` to `FROM rustlang/rust:nightly`

Then set up the automated build on Docker hub like this:

<img width="898" alt="screen shot 2018-02-20 at 10 42 22" src="https://user-images.githubusercontent.com/16778/36401332-ff2fa1fa-162a-11e8-9d83-e1572037bf97.png">

Let me know if that works or not, I could try it out on my fork too.

**Comment by xd009642** [comment]
I'm trying out the above suggestions now, I'm also adding the tags `develop-nightly` and `develop` so users can get the new as-yet unreleased features if they don't want to wait for a new release. I don't know how long it takes for dockerhub to build an image but at some point you can see if it works with `docker pull xd009642/tarpaulin:develop-nightly`!

Let me know if it works, I can try to find out if it does myself later but I don't have docker on this machine and tbh I've never really used it so little clue on getting started so may take me a while.

**Comment by robinst** [comment]
@xd009642 just tested it here and it worked :)

    docker run --security-opt seccomp=unconfined -v "$PWD:/volume" xd009642/tarpaulin:develop-nightly

Don't forget adding it to the README. I also realized we should probably link to https://hub.docker.com/r/xd009642/tarpaulin/ somewhere in the README, and maybe add a [docker badge](https://img.shields.io/docker/automated/xd009642/tarpaulin.svg)?

**Comment by xd009642** [comment]
Thanks for the help, and I'll add it to the README and once that's done close this issue :+1:

**Comment by rubdos** [comment]
I'll go test it on my GitLab CI, thanks! :-)

**Comment by xd009642** [comment]
And the readme is updated. I'm keeping an eye on the rustc PR that should fix #23 and I'll let you know when it's merged. I'm hoping that will fix it because that issue is a pain

**Comment by rubdos** [comment]
@xd009642 no requirement to let me know; I'm subscribed to that issue. And secondly, I'll magically see a coverage percentage appear in my own README. Hehe.
