### ISSUE TITLE
Tarpaulin does not obey RUST_TEST_THREADS

### ISSUE THREAD

**Issue by orenbenkiki** [xd009642/tarpaulin#916]
Doing `export RUST_TEST_THREADS=1` affects `cargo test` but is ignored by `cargo tarpaulin`.

Using explicit flags `cargo test -- --test-threads 1` and `cargo tarpaulin -- --test-threads 1` does work.

**Comment by xd009642** [comment]
I pushed a PR for this, I'll test it later today and merge it once it works :+1: https://github.com/xd009642/tarpaulin/pull/917

**Comment by xd009642** [comment]
Just tested it and it works, once CI finishes I'll merge it and then it'll be available in the develop docker images or if you install by develop (pending next release).

**Comment by orenbenkiki** [comment]
Thanks!
