### ISSUE TITLE
Feature Request: Show only uncovered lines

### ISSUE THREAD

**Issue by jounathaen** [xd009642/tarpaulin#92]
Maybe it is possible to add a feature which only shows the uncovered lines of a `tarpaulin --verbose` run.
Basically something like:
 `cargo tarpaulin --verbose | grep "hits: 0"`

It would be even nicer, if the output summarizes adjacent lines without coverage like:
`src/mymod.rs: 20-40 - hits: 0`

**Comment by xd009642** [comment]
Hmm I'll have to have a think about this. Personally, I'd just use grep and also fancy HTML reports are in the works. If users want to see coverage in different layouts it's probably nicer from a design point to have that provided by the HTML reports which are going to contain more information anyway.

Don't discounting anything, I just need to have a think about this one a bit more, thanks for contributing ideas to tarpaulin  :smile:

**Comment by RadicalZephyr** [comment]
Hi there,

I want to second the request for this idea.

My use case is that I'm taking a codebase that currently is lacking in tests, and trying to get the test coverage to a reasonable level.  So my workflow is to run tarpaulin to see what lines are uncovered, and then figure out a reasonable test to write for that code path.  The current verbose output is very unsuited to this workflow, and indeed, I can't think of any workflow that it does support very well.  When I run a coverage tool, I want to know exactly two things right away: what's the total coverage, and which lines aren't covered.

This is important enough to me that I'm going to implement it myself, which looks to be fairly easy (thanks!).  If you're interested, I can submit what I write as a PR and we can discuss whether and how you might want it to change for inclusion in tarpaulin.

Cheers, and thanks for your work on tarpaulin!

**Comment by xd009642** [comment]
This is been merged into the latest develop so closing the issue! Thanks @RadicalZephyr :+1: .

I should have a new release out end of this weekend or start of next week if people want to keep to released versions instead
