### ISSUE TITLE
Tests in workspace are run from wrong current working directory

### ISSUE THREAD

**Issue by danieleades** [xd009642/tarpaulin#921]
I have a workspace repo with a root crate, and a nested crate.

as in,

```toml
[workspace]
members = [
    ".",
    "nested-crate",
]
```

I have some tests defined in the root crate which rely on being able to pull the current working directory from the environment in order to find some test input files. This works fine with `cargo test`, but fails with `tarpaulin`.

if I use `cargo tarpaulin --all-features --workspace --tests --doc` and add a `dbg!(std::env::current_dir());` call to the test, I can see that the 'root' crate's tests are being run from the *nested* crate directory. Curiously, I'm finding this only occurs locally- it works fine in CI

**Comment by danieleades** [comment]
the crate where I'm seeing this can be found here - https://github.com/danieleades/config2

**Comment by danieleades** [comment]
i'm using `cargo-tarpaulin version: 0.19.0` (and yes, i'm definitely running it from the root of the repo!)

**Comment by danieleades** [comment]
manually specifying the `--root` resolves it too, if that helps

**Comment by xd009642** [comment]
Hmm I'll take a look and try to figure it out, but as an aside for tests that rely on accessing file resources I tend to use `CARGO_MANIFEST_DIR` to get myself a known good path to go from

**Comment by xd009642** [comment]
Interestingly enough, cargo_metadata identifies that `test/default.rs` belongs to the `config2-derive` package which is what's causing the issue. Unsure on why as that seems to be incorrect to me :thinking:. I'll dig further to see if I can figure it out because that feels wrong to me

**Comment by xd009642** [comment]
I figured out the issue so I'll test the fix after work and hopefully get it done and sorted :+1:

**Comment by xd009642** [comment]
The fix https://github.com/xd009642/tarpaulin/pull/927
