### ISSUE TITLE
Uncovered line at the end of macro definition

### ISSUE THREAD

**Issue by sphinxc0re** [xd009642/tarpaulin#93]
Tarpaulin doesn't seem to detect hits at the end of a macro definition:

<img width="1130" alt="screen shot 2018-03-12 at 13 35 51" src="https://user-images.githubusercontent.com/3702016/37284067-7e0041cc-25fa-11e8-8622-9d3645113226.png">

Although everything of this macro is covered. This is not the only macro where this happens. The issue seems to be reproducable across all macros in my project

**Comment by xd009642** [comment]
Thanks for the issue, that'll be another rule in the syntax analysis module. I'll let you know when it's done and merged into develop!

**Comment by xd009642** [comment]
And it was super simple, I've bundled it in with changes for #63 so it might be a few days before that's ready for merging. If you install tarpaulin's develop branch version or use the latest tarpaulin development docker image you should see it appear this week or next.

**Comment by sphinxc0re** [comment]
@xd009642 Thanks! 😁
