### ISSUE TITLE
Display code with covered lines

### ISSUE THREAD

**Issue by PoignardAzur** [xd009642/tarpaulin#934]
**Describe the feature**

This might be something I missed.

I'd like for there to be an easy way to display which lines are covered by test code.

For instance, if I write this code:

```
fn foobar(x: i32) {
    if x != 0 {
        println!("foo");
    }
    println!("bar");
}
```

I'd want to be able to produce a coverage report that looks like this:

```
1 | fn foobar(x: i32) {
1 |     if x != 0 {
0 |         println!("foo");
- |     }
1 |     println!("bar");
- | }
```

Telling me that "bar" has been visited once, but "foo" hasn't.

**Comment by xd009642** [comment]
If you look at the `--out` argument, there's options like xml (cobertura.xml), html, lcov etc. Html is a custom report format done by tarpaulin, all the others integrate with other tools or services that can create a rendered report. so `--out Html` is probably the easiest way to get/see that.

**Comment by xd009642** [comment]
I'm just going to close this as tarpaulin can already do this, but let me know if there are any follow up questions
