### ISSUE TITLE
#[cfg(not(tarpaulin_include))] does not work on trait implementations

### ISSUE THREAD

**Issue by vberger** [xd009642/tarpaulin#947]
Consider this code extracted from one of my projects:

```rust
#[cfg(not(tarpaulin_include))]
impl<E> Debug for InsertError<E> {
    fn fmt(&self, formatter: &mut Formatter) -> Result<(), fmt::Error> {
        write!(formatter, "{:?}", self.error)
    }
}
```

In the coverage report, the `fmt` method is marked as uncovered, which is not expected given the `#[cfg(not(tarpaulin_include))]` annotation.

**Comment by xd009642** [comment]
So I tried this in an example project and added the example snippet you added to the source_analysis tests to see if it failed but it showed all the lines as marked to ignore. Do you have a public project I can check against?

**Comment by vberger** [comment]
Sure, this is triggered on my `calloop` project, for example all those implementations are reported as uncovered on the [codecov report](https://app.codecov.io/gh/Smithay/calloop/blob/master/src/loop_logic.rs) :

https://github.com/Smithay/calloop/blob/7198d715d056b05b490e4c907b609a3da8f650ae/src/loop_logic.rs#L71-L97

**Comment by xd009642** [comment]
Well just ran tarpaulin on it with `--ignore-tests --all-features` like in your CI and they weren't marked as covered. Potentially this is something already fixed but I forgot doing or maybe you're on an outdated tarpaulin version?

![Screenshot from 2022-01-28 14-37-04](https://user-images.githubusercontent.com/3472518/151565847-8280345e-dd93-4332-8e21-61b16c8834c8.png)

**Comment by vberger** [comment]
Ah, indeed, that report was generade using tarpaulin 0.18.5, I suppose this has been fixed since then. Sorry for the noise!
