### ISSUE TITLE
Covered lines are uncovered even though, they are tested

### ISSUE THREAD

**Issue by sphinxc0re** [xd009642/tarpaulin#95]
To make it easier: https://github.com/bakervm/melon/pull/16
This PR is fully tested. Every method ist triggered.

EDIT: The lines are in a macro and in a extention function of `Result`

**Comment by xd009642** [comment]
Okay, looking at your file `vm.rs` the issue that caused the false negatives on lines 77 and 78 has already been fixed. If you install the latest version on the `develop` branch you should see this issue disappear. Lines 254 etc with `.context(..)?;` seem like it might be related to the last item on the list of inaccuracies in #63.

I'll have a look into the failure crate and figure out if it's the same thing. If it is I'll close this issue as a duplicate. If I do close this and you want I can tag you in a comment when it's sorted :smile:

**Comment by sphinxc0re** [comment]
Thank you!
